services:
  db:
    build: ./docker/db
    container_name: biome-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: biomedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/
  adminer:
    image: adminer
    ports:
      - "8888:8080"

volumes:
  pgdata: