version: "3"

vars:
  TEST_DB_NAME: testing

includes:
  db:
    taskfile: ./db
    dir: ./db
  client:
    taskfile: ./client
    dir: ./client
  server:
    taskfile: ./server
    dir: ./server

output: group

tasks:
  sync:
    desc: "Install dependencies and apply migrations"
    deps:
      - task: server:install
      - task: client:install
      - task: db:migrate
  setup:
    desc: "Install dependencies, apply migrations and seed database content"
    cmds:
      - task: db:seed
    deps:
      - server:install
      - task: client:install
        silent: true
  lint:
    desc: "Run golangci-lint"
    deps: [server:lint]
