// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: abiotics.sql

package biomedb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAbioticMeasurement = `-- name: CreateAbioticMeasurement :one
INSERT INTO abiotic_measurements (
        sampling_id,
        param_id,
        value
    )
VALUES (
        $1,
        $2,
        $3
    )
RETURNING sampling_id, param_id, value
`

type CreateAbioticMeasurementParams struct {
	SamplingID     uuid.UUID      `json:"sampling_id"`
	AbioticParamID uuid.UUID      `json:"abiotic_param_id"`
	Value          pgtype.Numeric `json:"value"`
}

func (q *Queries) CreateAbioticMeasurement(ctx context.Context, arg CreateAbioticMeasurementParams) (AbioticMeasurement, error) {
	row := q.db.QueryRow(ctx, createAbioticMeasurement, arg.SamplingID, arg.AbioticParamID, arg.Value)
	var i AbioticMeasurement
	err := row.Scan(&i.SamplingID, &i.ParamID, &i.Value)
	return i, err
}

const createAbioticParam = `-- name: CreateAbioticParam :one
INSERT INTO abiotic_params (
        name,
        code,
        description,
        unit
    )
VALUES (
        $1,
        $2,
        $3,
        $4
    )
RETURNING id, name, code, description, unit
`

type CreateAbioticParamParams struct {
	Name        string  `json:"name"`
	Code        string  `json:"code"`
	Description *string `json:"description"`
	Unit        string  `json:"unit"`
}

func (q *Queries) CreateAbioticParam(ctx context.Context, arg CreateAbioticParamParams) (AbioticParam, error) {
	row := q.db.QueryRow(ctx, createAbioticParam,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Unit,
	)
	var i AbioticParam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Unit,
	)
	return i, err
}

const listAbioticParams = `-- name: ListAbioticParams :many
SELECT id, name, code, description, unit
FROM abiotic_params
ORDER BY name ASC
`

func (q *Queries) ListAbioticParams(ctx context.Context) ([]AbioticParam, error) {
	rows, err := q.db.Query(ctx, listAbioticParams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AbioticParam{}
	for rows.Next() {
		var i AbioticParam
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
