// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch_imports.sql

package biomedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimGBIFImport = `-- name: ClaimGBIFImport :execrows
UPDATE import_workflows
SET gbif_status = 'in_progress',
    gbif_claimed_at = now()
WHERE import_hash = $1::text
    AND (
        gbif_status IN ('pending', 'failed')
        OR (
            gbif_status = 'in_progress'
            AND gbif_claimed_at < now() - INTERVAL '10 minutes'
        )
    )
`

func (q *Queries) ClaimGBIFImport(ctx context.Context, importHash string) (int64, error) {
	result, err := q.db.Exec(ctx, claimGBIFImport, importHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanUpStagingImport = `-- name: CleanUpStagingImport :exec
DELETE FROM import_samplings_occurrences
WHERE import_hash = $1
`

func (q *Queries) CleanUpStagingImport(ctx context.Context, importHash string) error {
	_, err := q.db.Exec(ctx, cleanUpStagingImport, importHash)
	return err
}

const completeGBIFImport = `-- name: CompleteGBIFImport :one
UPDATE import_workflows
SET gbif_status = 'completed',
    completed_at = now()
WHERE import_hash = $1::text
    AND gbif_status = 'in_progress'
RETURNING gbif_status
`

func (q *Queries) CompleteGBIFImport(ctx context.Context, importHash string) (GbifImportStatus, error) {
	row := q.db.QueryRow(ctx, completeGBIFImport, importHash)
	var gbif_status GbifImportStatus
	err := row.Scan(&gbif_status)
	return gbif_status, err
}

type CopyImportStagingParams struct {
	ImportHash                  string                   `json:"import_hash"`
	SamplingHash                string                   `json:"sampling_hash"`
	RowNumber                   int32                    `json:"row_number"`
	SamplingComments            pgtype.Text              `json:"sampling_comments"`
	SiteCode                    pgtype.Text              `json:"site_code"`
	SiteName                    pgtype.Text              `json:"site_name"`
	SiteLocality                pgtype.Text              `json:"site_locality"`
	SiteCountryCode             pgtype.Text              `json:"site_country_code"`
	CoordinatesPrecision        pgtype.Int4              `json:"coordinates_precision"`
	Longitude                   float32                  `json:"longitude"`
	Latitude                    float32                  `json:"latitude"`
	Altitude                    pgtype.Int4              `json:"altitude"`
	EventDate                   pgtype.Date              `json:"event_date"`
	EventDatePrecision          NullEventDatePrecision   `json:"event_date_precision"`
	PerformedBy                 []string                 `json:"performed_by"`
	Duration                    pgtype.Int4              `json:"duration"`
	AccessPoints                []string                 `json:"access_points"`
	SamplingTargets             []string                 `json:"sampling_targets"`
	SamplingFixatives           []string                 `json:"sampling_fixatives"`
	SamplingMethods             []string                 `json:"sampling_methods"`
	Habitats                    []string                 `json:"habitats"`
	OccurrenceCode              pgtype.Text              `json:"occurrence_code"`
	TypeStatus                  NullOccurrenceTypeStatus `json:"type_status"`
	OccurrenceComments          pgtype.Text              `json:"occurrence_comments"`
	TaxonName                   string                   `json:"taxon_name"`
	TaxonRank                   pgtype.Text              `json:"taxon_rank"`
	TaxonAuthorship             pgtype.Text              `json:"taxon_authorship"`
	VerbatimIdentification      pgtype.Text              `json:"verbatim_identification"`
	IdentifiedBy                []string                 `json:"identified_by"`
	IdentificationDate          pgtype.Date              `json:"identification_date"`
	IdentificationDatePrecision NullEventDatePrecision   `json:"identification_date_precision"`
	IdentificationConfer        bool                     `json:"identification_confer"`
	IdentificationAddendum      pgtype.Text              `json:"identification_addendum"`
	ContentDescription          pgtype.Text              `json:"content_description"`
	QuantityExact               pgtype.Int4              `json:"quantity_exact"`
	QuantityLower               pgtype.Int4              `json:"quantity_lower"`
	QuantityUpper               pgtype.Int4              `json:"quantity_upper"`
	Sources                     []string                 `json:"sources"`
}

const failGBIFImport = `-- name: FailGBIFImport :one
UPDATE import_workflows
SET gbif_status = 'failed'
WHERE import_hash = $1::text
    AND gbif_status = 'in_progress'
RETURNING gbif_status
`

func (q *Queries) FailGBIFImport(ctx context.Context, importHash string) (GbifImportStatus, error) {
	row := q.db.QueryRow(ctx, failGBIFImport, importHash)
	var gbif_status GbifImportStatus
	err := row.Scan(&gbif_status)
	return gbif_status, err
}

const getGBIFImportStatus = `-- name: GetGBIFImportStatus :one
SELECT gbif_status,
    gbif_claimed_at
FROM import_workflows
WHERE import_hash = $1::TEXT
`

type GetGBIFImportStatusRow struct {
	GbifStatus    GbifImportStatus   `json:"gbif_status"`
	GbifClaimedAt pgtype.Timestamptz `json:"gbif_claimed_at"`
}

func (q *Queries) GetGBIFImportStatus(ctx context.Context, importHash string) (GetGBIFImportStatusRow, error) {
	row := q.db.QueryRow(ctx, getGBIFImportStatus, importHash)
	var i GetGBIFImportStatusRow
	err := row.Scan(&i.GbifStatus, &i.GbifClaimedAt)
	return i, err
}

const getImportState = `-- name: GetImportState :one
SELECT import_hash, label, gbif_status, gbif_candidates_total, gbif_candidates_fetched, gbif_claimed_at, gbif_updated_at, created_at, completed_at
FROM import_workflows
WHERE import_hash = $1::TEXT
`

func (q *Queries) GetImportState(ctx context.Context, importHash string) (ImportWorkflow, error) {
	row := q.db.QueryRow(ctx, getImportState, importHash)
	var i ImportWorkflow
	err := row.Scan(
		&i.ImportHash,
		&i.Label,
		&i.GbifStatus,
		&i.GbifCandidatesTotal,
		&i.GbifCandidatesFetched,
		&i.GbifClaimedAt,
		&i.GbifUpdatedAt,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const incrementGBIFCandidatesProgress = `-- name: IncrementGBIFCandidatesProgress :one
UPDATE import_workflows
SET gbif_candidates_fetched = gbif_candidates_fetched + 1,
    gbif_updated_at = now()
WHERE import_hash = $1::text
    AND gbif_status = 'in_progress'
RETURNING gbif_candidates_fetched,
    gbif_candidates_total
`

type IncrementGBIFCandidatesProgressRow struct {
	GbifCandidatesFetched pgtype.Int4 `json:"gbif_candidates_fetched"`
	GbifCandidatesTotal   pgtype.Int4 `json:"gbif_candidates_total"`
}

func (q *Queries) IncrementGBIFCandidatesProgress(ctx context.Context, importHash string) (IncrementGBIFCandidatesProgressRow, error) {
	row := q.db.QueryRow(ctx, incrementGBIFCandidatesProgress, importHash)
	var i IncrementGBIFCandidatesProgressRow
	err := row.Scan(&i.GbifCandidatesFetched, &i.GbifCandidatesTotal)
	return i, err
}

const initBatchImport = `-- name: InitBatchImport :one
INSERT INTO import_workflows (import_hash, label)
VALUES ($1::TEXT, $2::TEXT) ON CONFLICT (import_hash) DO NOTHING
RETURNING import_hash, label, gbif_status, gbif_candidates_total, gbif_candidates_fetched, gbif_claimed_at, gbif_updated_at, created_at, completed_at
`

func (q *Queries) InitBatchImport(ctx context.Context, importHash string, label string) (ImportWorkflow, error) {
	row := q.db.QueryRow(ctx, initBatchImport, importHash, label)
	var i ImportWorkflow
	err := row.Scan(
		&i.ImportHash,
		&i.Label,
		&i.GbifStatus,
		&i.GbifCandidatesTotal,
		&i.GbifCandidatesFetched,
		&i.GbifClaimedAt,
		&i.GbifUpdatedAt,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const initGBIFCandidatesProgress = `-- name: InitGBIFCandidatesProgress :exec
UPDATE import_workflows
SET gbif_candidates_total = $1::INTEGER,
    gbif_candidates_fetched = 0,
    gbif_updated_at = now()
WHERE import_hash = $2::text
    AND gbif_status = 'in_progress'
`

func (q *Queries) InitGBIFCandidatesProgress(ctx context.Context, total int32, importHash string) error {
	_, err := q.db.Exec(ctx, initGBIFCandidatesProgress, total, importHash)
	return err
}

const insertOccurrencesFromStaging = `-- name: InsertOccurrencesFromStaging :exec
INSERT INTO occurrences (
        id,
        code,
        sampling_id,
        type_status,
        comments,
        taxon_id,
        verbatim_identification,
        identified_by,
        identification_date,
        identification_date_precision,
        identification_confer,
        identification_addendum,
        content_description,
        quantity_exact,
        quantity_lower,
        quantity_upper,
        sources
    )
SELECT i.occurrence_id,
    i.occurrence_code,
    s.id,
    i.type_status,
    i.comments,
    r.taxon_id,
    i.verbatim_identification,
    i.identified_by,
    i.identification_date,
    i.identification_date_precision,
    i.identification_confer,
    i.identification_addendum,
    i.content_description,
    i.quantity_exact,
    i.quantity_lower,
    i.quantity_upper,
    i.sources
FROM import_samplings_occurrences i
    JOIN samplings s ON s.sampling_hash = i.sampling_hash
    JOIN taxon_candidates r ON r.import_hash = i.import_hash
    AND r.input_name = i.taxon_scientific_name
WHERE i.import_hash = $1
`

func (q *Queries) InsertOccurrencesFromStaging(ctx context.Context, importHash string) error {
	_, err := q.db.Exec(ctx, insertOccurrencesFromStaging, importHash)
	return err
}

const upsertSamplingsFromStaging = `-- name: UpsertSamplingsFromStaging :many
INSERT INTO samplings (
        sampling_hash,
        notes,
        site_code,
        site_name,
        site_locality,
        site_country_code,
        coordinates_precision,
        coordinates,
        altitude,
        event_date,
        event_date_precision,
        performed_by,
        duration,
        access_points
    )
SELECT DISTINCT sampling_hash,
    notes,
    site_code,
    site_name,
    site_locality,
    site_country_code,
    coordinates_precision,
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326),
    altitude,
    event_date,
    event_date_precision,
    performed_by,
    duration,
    access_points
FROM import_samplings_occurrences
WHERE import_hash = $1 ON CONFLICT (sampling_hash) DO
UPDATE
SET notes = EXCLUDED.notes
RETURNING id,
    sampling_hash
`

type UpsertSamplingsFromStagingRow struct {
	ID           pgtype.UUID `json:"id"`
	SamplingHash string      `json:"sampling_hash"`
}

func (q *Queries) UpsertSamplingsFromStaging(ctx context.Context, importHash string) ([]UpsertSamplingsFromStagingRow, error) {
	rows, err := q.db.Query(ctx, upsertSamplingsFromStaging, importHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpsertSamplingsFromStagingRow
	for rows.Next() {
		var i UpsertSamplingsFromStagingRow
		if err := rows.Scan(&i.ID, &i.SamplingHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
