// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch_taxon_resolution.sql

package biomedb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const autoResolveUnambiguousCandidates = `-- name: AutoResolveUnambiguousCandidates :exec
WITH winners AS (
    SELECT c.import_id,
        c.resolution_id,
        (array_agg(c.id)) [1] AS id
    FROM taxon_candidates c
    WHERE c.import_id = $1
        AND c.priority >= 100
    GROUP BY c.import_id,
        c.resolution_id
    HAVING COUNT(*) = 1
)
UPDATE taxon_resolution r
SET resolved_to = w.id,
    status = 'auto_resolved',
    gbif_status = (
        CASE
            WHEN r.gbif_status = 'completed' THEN r.gbif_status
            ELSE 'skipped'
        END
    )
FROM winners w
WHERE r.import_id = w.import_id
    AND r.id = w.resolution_id
    AND r.status = 'pending'
`

// Automatically resolve candidates where there is a single best match above the priority threshold.
func (q *Queries) AutoResolveUnambiguousCandidates(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, autoResolveUnambiguousCandidates, importID)
	return err
}

const cleanUpTaxonResolution = `-- name: CleanUpTaxonResolution :exec
DELETE FROM taxon_resolution
WHERE import_id = $1
`

func (q *Queries) CleanUpTaxonResolution(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cleanUpTaxonResolution, importID)
	return err
}

const cleanupTaxonCandidates = `-- name: CleanupTaxonCandidates :exec
DELETE FROM taxon_candidates
WHERE import_id = $1
`

func (q *Queries) CleanupTaxonCandidates(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cleanupTaxonCandidates, importID)
	return err
}

const createCandidateTaxaFuzzy = `-- name: CreateCandidateTaxaFuzzy :exec
WITH candidates AS (
    SELECT r.import_id,
        r.id AS resolution_id,
        t.id AS taxon_id,
        t.gbif_id,
        similarity(t.scientific_name, r.scientific_name) AS score,
        t.name,
        t.authorship,
        t.rank,
        t.status
    FROM taxon_resolution r
        JOIN taxa t ON t.scientific_name % r.scientific_name
    WHERE r.import_id = $2
)
INSERT INTO taxon_candidates (
        import_id,
        resolution_id,
        source,
        match_type,
        taxon_id,
        gbif_id,
        score,
        priority,
        name,
        authorship,
        rank,
        status
    )
SELECT c.import_id,
    c.resolution_id,
    'internal'::taxon_match_source,
    'fuzzy'::taxon_match_type,
    c.taxon_id,
    c.gbif_id,
    c.score,
    50,
    c.name,
    c.authorship,
    c.rank,
    c.status
FROM candidates c
WHERE c.score > COALESCE(NULLIF($1::double precision, 0), 0.6) ON CONFLICT DO NOTHING
`

func (q *Queries) CreateCandidateTaxaFuzzy(ctx context.Context, threshold float64, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createCandidateTaxaFuzzy, threshold, importID)
	return err
}

const createCandidateTaxaNameExact = `-- name: CreateCandidateTaxaNameExact :exec
INSERT INTO taxon_candidates (
        import_id,
        resolution_id,
        source,
        match_type,
        taxon_id,
        gbif_id,
        score,
        priority,
        name,
        authorship,
        rank,
        status
    )
SELECT DISTINCT i.import_id,
    i.id,
    'internal'::taxon_match_source,
    'exact'::taxon_match_type,
    t.id,
    t.gbif_id,
    1.0,
    100,
    t.name,
    t.authorship,
    t.rank,
    t.status
FROM taxon_resolution i
    JOIN taxa t ON (
        i.scientific_name = t.scientific_name
        OR (
            i.input_authorship IS NULL
            AND i.input_name = t.name
        )
    )
WHERE i.import_id = $1
`

// Create candidate matches based on exact name matches,
// using either the scientific name or the canonical name.
func (q *Queries) CreateCandidateTaxaNameExact(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createCandidateTaxaNameExact, importID)
	return err
}

const getTaxonResolution = `-- name: GetTaxonResolution :many
SELECT id, import_id, input_name, input_authorship, input_rank, scientific_name, status, gbif_status, resolved_to
FROM taxon_resolution
WHERE import_id = $1
`

func (q *Queries) GetTaxonResolution(ctx context.Context, importID uuid.UUID) ([]TaxonResolution, error) {
	rows, err := q.db.Query(ctx, getTaxonResolution, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxonResolution{}
	for rows.Next() {
		var i TaxonResolution
		if err := rows.Scan(
			&i.ID,
			&i.ImportID,
			&i.InputName,
			&i.InputAuthorship,
			&i.InputRank,
			&i.ScientificName,
			&i.Status,
			&i.GBIFStatus,
			&i.ResolvedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const initTaxonResolution = `-- name: InitTaxonResolution :many
INSERT INTO taxon_resolution (
        import_id,
        input_name,
        input_authorship,
        input_rank
    )
SELECT DISTINCT i.import_id,
    i.taxon_name,
    i.taxon_authorship,
    i.taxon_rank
FROM import_samplings_occurrences i
WHERE i.import_id = $1
RETURNING id, import_id, input_name, input_authorship, input_rank, scientific_name, status, gbif_status, resolved_to
`

func (q *Queries) InitTaxonResolution(ctx context.Context, importID uuid.UUID) ([]TaxonResolution, error) {
	rows, err := q.db.Query(ctx, initTaxonResolution, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxonResolution{}
	for rows.Next() {
		var i TaxonResolution
		if err := rows.Scan(
			&i.ID,
			&i.ImportID,
			&i.InputName,
			&i.InputAuthorship,
			&i.InputRank,
			&i.ScientificName,
			&i.Status,
			&i.GBIFStatus,
			&i.ResolvedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkTaxonResolutions = `-- name: LinkTaxonResolutions :exec
UPDATE import_samplings_occurrences i
SET taxon_resolution_id = r.id
FROM taxon_resolution r
WHERE i.import_id = $1
    AND i.import_id = r.import_id
    AND i.taxon_name = r.input_name
    AND (
        i.taxon_authorship = r.input_authorship
        OR (
            i.taxon_authorship IS NULL
            AND r.input_authorship IS NULL
        )
    )
`

func (q *Queries) LinkTaxonResolutions(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, linkTaxonResolutions, importID)
	return err
}

const listAllTaxonCandidates = `-- name: ListAllTaxonCandidates :many
WITH candidates AS (
    SELECT c.id,
        c.resolution_id,
        c.source,
        c.match_type,
        c.score,
        c.priority,
        t.id AS resolved_taxon_id,
        c.gbif_id AS resolved_gbif_id,
        COALESCE(t.name, g.canonical_name) AS resolved_name,
        COALESCE(t.authorship, g.authorship) AS resolved_authorship,
        COALESCE(t.rank, g.rank::taxon_rank) AS resolved_rank,
        COALESCE(t.status, g.status::taxon_status) AS resolved_status
    FROM taxon_candidates c
        LEFT JOIN taxa t ON (
            c.source = 'internal'
            AND t.id = c.taxon_id
        )
        LEFT JOIN gbif_staging g ON (
            c.source = 'gbif'
            AND g.key = c.gbif_id
        )
    WHERE c.import_id = $1
)
SELECT id, resolution_id, source, match_type, score, priority, resolved_taxon_id, resolved_gbif_id, resolved_name, resolved_authorship, resolved_rank, resolved_status,
    ROW_NUMBER() OVER (
        PARTITION BY resolution_id
        ORDER BY priority DESC,
            score DESC
    ) AS rank
FROM candidates
`

type ListAllTaxonCandidatesRow struct {
	ID                 uuid.UUID        `json:"id"`
	ResolutionID       uuid.UUID        `json:"resolution_id"`
	Source             TaxonMatchSource `json:"source"`
	MatchType          TaxonMatchType   `json:"match_type"`
	Score              *float64         `json:"score"`
	Priority           int32            `json:"priority"`
	ResolvedTaxonID    pgtype.UUID      `json:"resolved_taxon_id"`
	ResolvedGBIFID     *int32           `json:"resolved_gbif_id"`
	ResolvedName       string           `json:"resolved_name"`
	ResolvedAuthorship *string          `json:"resolved_authorship"`
	ResolvedRank       TaxonRank        `json:"resolved_rank"`
	ResolvedStatus     TaxonStatus      `json:"resolved_status"`
	Rank               int64            `json:"rank"`
}

func (q *Queries) ListAllTaxonCandidates(ctx context.Context, importID uuid.UUID) ([]ListAllTaxonCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAllTaxonCandidates, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTaxonCandidatesRow{}
	for rows.Next() {
		var i ListAllTaxonCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ResolutionID,
			&i.Source,
			&i.MatchType,
			&i.Score,
			&i.Priority,
			&i.ResolvedTaxonID,
			&i.ResolvedGBIFID,
			&i.ResolvedName,
			&i.ResolvedAuthorship,
			&i.ResolvedRank,
			&i.ResolvedStatus,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolutionsToFetchGBIFCandidates = `-- name: ListResolutionsToFetchGBIFCandidates :many
SELECT r.id, r.import_id, r.input_name, r.input_authorship, r.input_rank, r.scientific_name, r.status, r.gbif_status, r.resolved_to
FROM taxon_resolution r
WHERE r.import_id = $1
    AND r.gbif_status IN ('pending', 'failed')
ORDER BY r.scientific_name
`

func (q *Queries) ListResolutionsToFetchGBIFCandidates(ctx context.Context, importID uuid.UUID) ([]TaxonResolution, error) {
	rows, err := q.db.Query(ctx, listResolutionsToFetchGBIFCandidates, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxonResolution{}
	for rows.Next() {
		var i TaxonResolution
		if err := rows.Scan(
			&i.ID,
			&i.ImportID,
			&i.InputName,
			&i.InputAuthorship,
			&i.InputRank,
			&i.ScientificName,
			&i.Status,
			&i.GBIFStatus,
			&i.ResolvedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaxaGBIFImportCompleted = `-- name: MarkTaxaGBIFImportCompleted :exec
UPDATE taxon_resolution r
SET gbif_status = 'completed'
WHERE r.import_id = $1
    AND r.gbif_status NOT IN ('skipped', 'completed')
    AND r.id = ANY($2::UUID [])
`

func (q *Queries) MarkTaxaGBIFImportCompleted(ctx context.Context, importID uuid.UUID, resolutionsIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTaxaGBIFImportCompleted, importID, resolutionsIds)
	return err
}

const markTaxaNeedingGBIFCandidates = `-- name: MarkTaxaNeedingGBIFCandidates :exec
UPDATE taxon_resolution r
SET gbif_status = 'pending'
WHERE r.import_id = $1
    AND r.gbif_status NOT IN ('skipped', 'completed')
    AND NOT EXISTS (
        SELECT 1
        FROM taxon_candidates c
        WHERE c.import_id = r.import_id
            AND c.resolution_id = r.id
            AND (
                (
                    c.source = 'internal'
                    AND c.match_type = 'exact'
                )
                OR c.source = 'gbif'
            )
    )
`

func (q *Queries) MarkTaxaNeedingGBIFCandidates(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTaxaNeedingGBIFCandidates, importID)
	return err
}

const resolveTaxon = `-- name: ResolveTaxon :exec
UPDATE taxon_resolution
SET resolved_to = $1::uuid,
    status = 'user_resolved'
WHERE import_id = $2
    AND id = $3
`

type ResolveTaxonParams struct {
	ResolvedTo   uuid.UUID `json:"resolved_to"`
	ImportID     uuid.UUID `json:"import_id"`
	ResolutionID uuid.UUID `json:"resolution_id"`
}

func (q *Queries) ResolveTaxon(ctx context.Context, arg ResolveTaxonParams) error {
	_, err := q.db.Exec(ctx, resolveTaxon, arg.ResolvedTo, arg.ImportID, arg.ResolutionID)
	return err
}

const updateMaterializedTaxonCandidates = `-- name: UpdateMaterializedTaxonCandidates :exec
UPDATE taxon_candidates c
SET taxon_id = t.id
FROM taxa t
WHERE c.gbif_id = t.gbif_id
    AND c.import_id = $1
    AND c.taxon_id IS NULL
`

// Update the taxon_id field in taxon_candidates for candidates that have a matching gbif_id in the taxa table.
// This is necessary because the taxa table is populated after the taxon_candidates table,
// and we need to link the candidates to the actual taxa records.
func (q *Queries) UpdateMaterializedTaxonCandidates(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateMaterializedTaxonCandidates, importID)
	return err
}

const upsertTaxonResolution = `-- name: UpsertTaxonResolution :exec
INSERT INTO taxon_resolution (
        import_id,
        input_name,
        input_authorship,
        input_rank,
        resolved_to,
        status
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    ) ON CONFLICT (import_id, input_name) DO NOTHING
`

type UpsertTaxonResolutionParams struct {
	ImportID        uuid.UUID         `json:"import_id"`
	InputName       string            `json:"input_name"`
	InputAuthorship *string           `json:"input_authorship"`
	InputRank       *string           `json:"input_rank"`
	ResolvedTo      pgtype.UUID       `json:"resolved_to"`
	Status          *ResolutionStatus `json:"status"`
}

func (q *Queries) UpsertTaxonResolution(ctx context.Context, arg UpsertTaxonResolutionParams) error {
	_, err := q.db.Exec(ctx, upsertTaxonResolution,
		arg.ImportID,
		arg.InputName,
		arg.InputAuthorship,
		arg.InputRank,
		arg.ResolvedTo,
		arg.Status,
	)
	return err
}
