// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch_taxon_resolution.sql

package biomedb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const autoResolveUnambiguousCandidates = `-- name: AutoResolveUnambiguousCandidates :exec
WITH winners AS (
    SELECT c.import_id,
        c.resolution_id,
        (array_agg(c.id)) [1] AS id
    FROM taxon_candidates c
    WHERE c.import_id = $1
        AND c.priority >= $2
    GROUP BY c.import_id,
        c.resolution_id
    HAVING COUNT(*) = 1
)
UPDATE taxon_resolution r
SET resolved_candidate_id = w.id,
    status = 'auto_resolved',
    gbif_status = (
        CASE
            WHEN r.gbif_status = 'completed' THEN r.gbif_status
            ELSE 'skipped'
        END
    )
FROM winners w
WHERE r.import_id = w.import_id
    AND r.id = w.resolution_id
    AND r.status = 'pending'
`

// Automatically resolve candidates where there is a single best match above the priority threshold.
func (q *Queries) AutoResolveUnambiguousCandidates(ctx context.Context, importID uuid.UUID, threshold int32) error {
	_, err := q.db.Exec(ctx, autoResolveUnambiguousCandidates, importID, threshold)
	return err
}

const checkTaxaConsistencyInImport = `-- name: CheckTaxaConsistencyInImport :many
SELECT input_name,
    count(*),
    array_agg(DISTINCT taxon_authorship)::text [] AS authorships,
    array_agg(DISTINCT taxon_rank)::text [] AS ranks
FROM (
        SELECT DISTINCT i.import_id,
            i.taxon_name::citext AS input_name,
            i.taxon_authorship,
            i.taxon_rank
        FROM import_samplings_occurrences i
        WHERE i.import_id = $1
    ) t
GROUP BY input_name
HAVING count(*) > 1
`

type CheckTaxaConsistencyInImportRow struct {
	InputName   string   `json:"input_name"`
	Count       int64    `json:"count"`
	Authorships []string `json:"authorships"`
	Ranks       []string `json:"ranks"`
}

func (q *Queries) CheckTaxaConsistencyInImport(ctx context.Context, importID uuid.UUID) ([]CheckTaxaConsistencyInImportRow, error) {
	rows, err := q.db.Query(ctx, checkTaxaConsistencyInImport, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckTaxaConsistencyInImportRow{}
	for rows.Next() {
		var i CheckTaxaConsistencyInImportRow
		if err := rows.Scan(
			&i.InputName,
			&i.Count,
			&i.Authorships,
			&i.Ranks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanUpTaxonResolution = `-- name: CleanUpTaxonResolution :exec
DELETE FROM taxon_resolution
WHERE import_id = $1
`

func (q *Queries) CleanUpTaxonResolution(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cleanUpTaxonResolution, importID)
	return err
}

const cleanupTaxonCandidates = `-- name: CleanupTaxonCandidates :exec
DELETE FROM taxon_candidates
WHERE import_id = $1
`

func (q *Queries) CleanupTaxonCandidates(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cleanupTaxonCandidates, importID)
	return err
}

const createCandidateTaxaFuzzy = `-- name: CreateCandidateTaxaFuzzy :exec
WITH candidates AS (
    SELECT r.import_id,
        r.id AS resolution_id,
        t.id AS taxon_id,
        t.gbif_id,
        similarity(t.scientific_name, r.scientific_name) AS score,
        t.name,
        t.authorship,
        t.rank,
        t.status
    FROM taxon_resolution r
        JOIN taxa t ON t.scientific_name % r.scientific_name
    WHERE r.import_id = $2
)
INSERT INTO taxon_candidates (
        import_id,
        resolution_id,
        source,
        match_type,
        taxon_id,
        gbif_id,
        score,
        priority,
        name,
        authorship,
        rank,
        status
    )
SELECT c.import_id,
    c.resolution_id,
    'internal'::taxon_match_source,
    'fuzzy'::taxon_match_type,
    c.taxon_id,
    c.gbif_id,
    c.score,
    50,
    c.name,
    c.authorship,
    c.rank,
    c.status
FROM candidates c
WHERE c.score > COALESCE(NULLIF($1::double precision, 0), 0.6) ON CONFLICT DO NOTHING
`

func (q *Queries) CreateCandidateTaxaFuzzy(ctx context.Context, threshold float64, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createCandidateTaxaFuzzy, threshold, importID)
	return err
}

const createCandidateTaxaNameExact = `-- name: CreateCandidateTaxaNameExact :exec
INSERT INTO taxon_candidates (
        import_id,
        resolution_id,
        source,
        match_type,
        taxon_id,
        gbif_id,
        score,
        priority,
        name,
        authorship,
        rank,
        status
    )
SELECT DISTINCT i.import_id,
    i.id,
    'internal'::taxon_match_source,
    'exact'::taxon_match_type,
    t.id,
    t.gbif_id,
    1.0,
    100,
    t.name,
    t.authorship,
    t.rank,
    t.status
FROM taxon_resolution i
    JOIN taxa t ON (
        i.scientific_name = t.scientific_name
        OR (
            i.input_authorship IS NULL
            AND i.input_name = t.name
        )
    )
WHERE i.import_id = $1
`

// Create candidate matches based on exact name matches,
// using either the scientific name or the canonical name.
func (q *Queries) CreateCandidateTaxaNameExact(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createCandidateTaxaNameExact, importID)
	return err
}

const getTaxonResolution = `-- name: GetTaxonResolution :many
SELECT t.id, t.import_id, t.input_name, t.input_authorship, t.input_rank, t.scientific_name, t.status, t.gbif_status, t.from_resolution_id, t.sampling_target, t.resolved_candidate_id,
    parent.input_name as from_resolution_name
FROM taxon_resolution t
    LEFT JOIN taxon_resolution parent ON t.from_resolution_id = parent.id
WHERE t.import_id = $1
`

type GetTaxonResolutionRow struct {
	TaxonResolution    TaxonResolution `json:"taxon_resolution"`
	FromResolutionName *string         `json:"from_resolution_name"`
}

func (q *Queries) GetTaxonResolution(ctx context.Context, importID uuid.UUID) ([]GetTaxonResolutionRow, error) {
	rows, err := q.db.Query(ctx, getTaxonResolution, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaxonResolutionRow{}
	for rows.Next() {
		var i GetTaxonResolutionRow
		if err := rows.Scan(
			&i.TaxonResolution.ID,
			&i.TaxonResolution.ImportID,
			&i.TaxonResolution.InputName,
			&i.TaxonResolution.InputAuthorship,
			&i.TaxonResolution.InputRank,
			&i.TaxonResolution.ScientificName,
			&i.TaxonResolution.Status,
			&i.TaxonResolution.GBIFStatus,
			&i.TaxonResolution.FromResolutionID,
			&i.TaxonResolution.SamplingTarget,
			&i.TaxonResolution.ResolvedCandidateID,
			&i.FromResolutionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const initSamplingTargetResolution = `-- name: InitSamplingTargetResolution :exec
WITH all_sampling_targets AS (
    SELECT DISTINCT import_id,
        sampling_hash,
        sampling_target
    FROM import_samplings_occurrences iso
        CROSS JOIN LATERAL unnest(sampling_targets) AS sampling_target
    WHERE iso.import_id = $1
        AND sampling_target <> ''
),
new_resolutions AS (
    INSERT INTO taxon_resolution (import_id, input_name, sampling_target)
    SELECT import_id,
        sampling_target,
        true
    FROM all_sampling_targets ON CONFLICT (import_id, input_name) DO NOTHING
    RETURNING id, import_id, input_name, input_authorship, input_rank, scientific_name, status, gbif_status, from_resolution_id, sampling_target, resolved_candidate_id
)
INSERT INTO sampling_target_resolution (
        import_id,
        sampling_hash,
        resolution_id
    )
SELECT st.import_id,
    st.sampling_hash,
    r.id
FROM all_sampling_targets st
    JOIN taxon_resolution r ON r.import_id = st.import_id
    AND r.input_name = st.sampling_target ON CONFLICT (import_id, sampling_hash, resolution_id) DO NOTHING
`

func (q *Queries) InitSamplingTargetResolution(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, initSamplingTargetResolution, importID)
	return err
}

const initTaxonResolution = `-- name: InitTaxonResolution :many
INSERT INTO taxon_resolution (
        import_id,
        input_name,
        input_authorship,
        input_rank
    )
SELECT DISTINCT i.import_id,
    i.taxon_name,
    i.taxon_authorship,
    i.taxon_rank
FROM import_samplings_occurrences i
WHERE i.import_id = $1
RETURNING id, import_id, input_name, input_authorship, input_rank, scientific_name, status, gbif_status, from_resolution_id, sampling_target, resolved_candidate_id
`

func (q *Queries) InitTaxonResolution(ctx context.Context, importID uuid.UUID) ([]TaxonResolution, error) {
	rows, err := q.db.Query(ctx, initTaxonResolution, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxonResolution{}
	for rows.Next() {
		var i TaxonResolution
		if err := rows.Scan(
			&i.ID,
			&i.ImportID,
			&i.InputName,
			&i.InputAuthorship,
			&i.InputRank,
			&i.ScientificName,
			&i.Status,
			&i.GBIFStatus,
			&i.FromResolutionID,
			&i.SamplingTarget,
			&i.ResolvedCandidateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkTaxonResolutions = `-- name: LinkTaxonResolutions :exec
UPDATE import_samplings_occurrences i
SET taxon_resolution_id = r.id
FROM taxon_resolution r
WHERE i.import_id = $1
    AND i.import_id = r.import_id
    AND i.taxon_name = r.input_name
    AND (
        i.taxon_authorship = r.input_authorship
        OR (
            i.taxon_authorship IS NULL
            AND r.input_authorship IS NULL
        )
    )
`

func (q *Queries) LinkTaxonResolutions(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, linkTaxonResolutions, importID)
	return err
}

const listAllTaxonCandidates = `-- name: ListAllTaxonCandidates :many
WITH candidates AS (
    SELECT c.id,
        c.resolution_id,
        c.source,
        c.match_type,
        c.score,
        c.priority,
        t.id AS resolved_taxon_id,
        c.gbif_id AS resolved_gbif_id,
        COALESCE(t.name, g.canonical_name, s.name) AS resolved_name,
        COALESCE(t.authorship, g.authorship, s.authorship) AS resolved_authorship,
        COALESCE(t.rank, g.rank::taxon_rank, s.rank) AS resolved_rank,
        COALESCE(t.status, g.status::taxon_status, s.status) AS resolved_status
    FROM taxon_candidates c
        LEFT JOIN taxa t ON (
            c.source = 'internal'
            AND t.id = c.taxon_id
        )
        LEFT JOIN gbif_staging g ON (
            c.source = 'gbif'
            AND g.key = c.gbif_id
        )
        LEFT JOIN taxa_staging s ON (
            c.source = 'manual'
            AND s.id = c.staging_id
        )
    WHERE c.import_id = $1
)
SELECT id, resolution_id, source, match_type, score, priority, resolved_taxon_id, resolved_gbif_id, resolved_name, resolved_authorship, resolved_rank, resolved_status,
    ROW_NUMBER() OVER (
        PARTITION BY resolution_id
        ORDER BY priority DESC,
            score DESC
    ) AS rank
FROM candidates
`

type ListAllTaxonCandidatesRow struct {
	ID                 uuid.UUID        `json:"id"`
	ResolutionID       uuid.UUID        `json:"resolution_id"`
	Source             TaxonMatchSource `json:"source"`
	MatchType          TaxonMatchType   `json:"match_type"`
	Score              *float64         `json:"score"`
	Priority           int32            `json:"priority"`
	ResolvedTaxonID    pgtype.UUID      `json:"resolved_taxon_id"`
	ResolvedGBIFID     *int32           `json:"resolved_gbif_id"`
	ResolvedName       string           `json:"resolved_name"`
	ResolvedAuthorship *string          `json:"resolved_authorship"`
	ResolvedRank       TaxonRank        `json:"resolved_rank"`
	ResolvedStatus     TaxonStatus      `json:"resolved_status"`
	Rank               int64            `json:"rank"`
}

func (q *Queries) ListAllTaxonCandidates(ctx context.Context, importID uuid.UUID) ([]ListAllTaxonCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAllTaxonCandidates, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTaxonCandidatesRow{}
	for rows.Next() {
		var i ListAllTaxonCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ResolutionID,
			&i.Source,
			&i.MatchType,
			&i.Score,
			&i.Priority,
			&i.ResolvedTaxonID,
			&i.ResolvedGBIFID,
			&i.ResolvedName,
			&i.ResolvedAuthorship,
			&i.ResolvedRank,
			&i.ResolvedStatus,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolutionsToFetchGBIFCandidates = `-- name: ListResolutionsToFetchGBIFCandidates :many
SELECT r.id, r.import_id, r.input_name, r.input_authorship, r.input_rank, r.scientific_name, r.status, r.gbif_status, r.from_resolution_id, r.sampling_target, r.resolved_candidate_id
FROM taxon_resolution r
WHERE r.import_id = $1
    AND r.gbif_status IN ('pending', 'failed')
ORDER BY r.scientific_name
`

func (q *Queries) ListResolutionsToFetchGBIFCandidates(ctx context.Context, importID uuid.UUID) ([]TaxonResolution, error) {
	rows, err := q.db.Query(ctx, listResolutionsToFetchGBIFCandidates, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxonResolution{}
	for rows.Next() {
		var i TaxonResolution
		if err := rows.Scan(
			&i.ID,
			&i.ImportID,
			&i.InputName,
			&i.InputAuthorship,
			&i.InputRank,
			&i.ScientificName,
			&i.Status,
			&i.GBIFStatus,
			&i.FromResolutionID,
			&i.SamplingTarget,
			&i.ResolvedCandidateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxonResolutionsWithoutCandidates = `-- name: ListTaxonResolutionsWithoutCandidates :many
SELECT r.id, r.import_id, r.input_name, r.input_authorship, r.input_rank, r.scientific_name, r.status, r.gbif_status, r.from_resolution_id, r.sampling_target, r.resolved_candidate_id
FROM taxon_resolution r
WHERE r.import_id = $1
    AND r.status = 'pending'
    AND NOT EXISTS (
        SELECT 1
        FROM taxon_candidates c
        WHERE c.import_id = r.import_id
            AND c.resolution_id = r.id
    )
`

func (q *Queries) ListTaxonResolutionsWithoutCandidates(ctx context.Context, importID uuid.UUID) ([]TaxonResolution, error) {
	rows, err := q.db.Query(ctx, listTaxonResolutionsWithoutCandidates, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxonResolution{}
	for rows.Next() {
		var i TaxonResolution
		if err := rows.Scan(
			&i.ID,
			&i.ImportID,
			&i.InputName,
			&i.InputAuthorship,
			&i.InputRank,
			&i.ScientificName,
			&i.Status,
			&i.GBIFStatus,
			&i.FromResolutionID,
			&i.SamplingTarget,
			&i.ResolvedCandidateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaxaGBIFImportCompleted = `-- name: MarkTaxaGBIFImportCompleted :exec
UPDATE taxon_resolution r
SET gbif_status = CASE
        WHEN EXISTS (
            SELECT 1
            FROM taxon_candidates c
            WHERE c.import_id = r.import_id
                AND c.resolution_id = r.id
        ) THEN 'completed'::taxon_gbif_status
        ELSE 'no_candidates'::taxon_gbif_status
    END
WHERE r.import_id = $1
    AND r.gbif_status = 'pending'
`

func (q *Queries) MarkTaxaGBIFImportCompleted(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTaxaGBIFImportCompleted, importID)
	return err
}

const markTaxaNeedingGBIFCandidates = `-- name: MarkTaxaNeedingGBIFCandidates :exec
UPDATE taxon_resolution r
SET gbif_status = 'pending'
WHERE r.import_id = $1
    AND r.gbif_status = 'pending'
    AND NOT EXISTS (
        SELECT 1
        FROM taxon_candidates c
        WHERE c.import_id = r.import_id
            AND c.resolution_id = r.id
            AND (
                (
                    c.source = 'internal'
                    AND c.match_type = 'exact'
                )
                OR c.source = 'gbif'
            )
    )
`

func (q *Queries) MarkTaxaNeedingGBIFCandidates(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTaxaNeedingGBIFCandidates, importID)
	return err
}

const materializeTaxaStaging = `-- name: MaterializeTaxaStaging :exec
WITH resolved_candidates AS (
    SELECT s.id, s.import_id, s.name, s.authorship, s.rank, s.status, s.parent_resolution_id,
        parent_candidate.taxon_id AS parent_id
    FROM taxon_candidates c
        JOIN taxon_resolution r ON (
            r.import_id = c.import_id
            AND r.resolved_candidate_id = c.id
        )
        JOIN taxa_staging s ON (c.staging_id = s.id)
        JOIN taxon_resolution parent_resolution ON (
            parent_resolution.id = s.parent_resolution_id
            AND parent_resolution.import_id = s.import_id
        )
        JOIN taxon_candidates parent_candidate ON (
            parent_candidate.id = parent_resolution.resolved_candidate_id
            AND parent_candidate.import_id = s.import_id
        )
    WHERE c.import_id = $1
        AND c.source = 'manual'
        AND c.rank = $2
)
INSERT INTO taxa (
        name,
        authorship,
        rank,
        status,
        parent_id
    )
SELECT name,
    authorship,
    rank,
    status,
    parent_id
FROM resolved_candidates ON CONFLICT (name, COALESCE(authorship, '')) DO NOTHING
`

// Materialize taxa from the taxa_staging table into the main taxa table,
// based on the resolutions identified for a given import batch.
// Materialization of GBIF taxa must have been completed before this query is run,
// as it relies on the resolved candidates from the GBIF data.
// This query must be run for each rank separately,
// as the parent taxa must be materialized before the child taxa can be materialized.
// SyncMaterializedTaxa must be run after each rank is materialized
// to update the taxon_candidates table with the newly created taxa IDs.
func (q *Queries) MaterializeTaxaStaging(ctx context.Context, importID uuid.UUID, rank TaxonRank) error {
	_, err := q.db.Exec(ctx, materializeTaxaStaging, importID, rank)
	return err
}

const resolveTaxon = `-- name: ResolveTaxon :exec
UPDATE taxon_resolution
SET resolved_candidate_id = $1::uuid,
    status = 'user_resolved'
WHERE import_id = $2
    AND id = $3
`

type ResolveTaxonParams struct {
	CandidateID  uuid.UUID `json:"candidate_id"`
	ImportID     uuid.UUID `json:"import_id"`
	ResolutionID uuid.UUID `json:"resolution_id"`
}

func (q *Queries) ResolveTaxon(ctx context.Context, arg ResolveTaxonParams) error {
	_, err := q.db.Exec(ctx, resolveTaxon, arg.CandidateID, arg.ImportID, arg.ResolutionID)
	return err
}

const setNeedsResolutionForUnresolvedCandidates = `-- name: SetNeedsResolutionForUnresolvedCandidates :exec
UPDATE taxon_resolution r
SET status = 'needs_decision'
WHERE r.import_id = $1
    AND r.status = 'pending'
`

// Mark taxon resolutions as needing user resolution if they have candidates but are still unresolved.
func (q *Queries) SetNeedsResolutionForUnresolvedCandidates(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setNeedsResolutionForUnresolvedCandidates, importID)
	return err
}

const syncMaterializedTaxa = `-- name: SyncMaterializedTaxa :exec
UPDATE taxon_candidates c
SET taxon_id = t.id
FROM taxa_staging s
    JOIN taxa t ON (
        t.name = s.name
        AND t.authorship IS NOT DISTINCT
        FROM s.authorship
            AND t.rank = s.rank
    )
WHERE c.import_id = $1
    AND c.staging_id = s.id
    AND c.rank = $2
    AND c.source = 'manual'
`

func (q *Queries) SyncMaterializedTaxa(ctx context.Context, importID uuid.UUID, rank TaxonRank) error {
	_, err := q.db.Exec(ctx, syncMaterializedTaxa, importID, rank)
	return err
}

const updateMaterializedGBIFCandidates = `-- name: UpdateMaterializedGBIFCandidates :exec
UPDATE taxon_candidates c
SET taxon_id = t.id
FROM taxa t
WHERE c.gbif_id = t.gbif_id
    AND c.import_id = $1
    AND c.taxon_id IS NULL
`

// Update the taxon_id field in taxon_candidates for candidates that have a matching gbif_id in the taxa table.
// This is necessary because the taxa table is populated after the taxon_candidates table,
// and we need to link the candidates to the actual taxa records.
func (q *Queries) UpdateMaterializedGBIFCandidates(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateMaterializedGBIFCandidates, importID)
	return err
}

const upsertTaxonResolution = `-- name: UpsertTaxonResolution :exec
INSERT INTO taxon_resolution (
        import_id,
        input_name,
        input_authorship,
        input_rank,
        resolved_candidate_id,
        status
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    ) ON CONFLICT (import_id, input_name) DO NOTHING
`

type UpsertTaxonResolutionParams struct {
	ImportID            uuid.UUID         `json:"import_id"`
	InputName           string            `json:"input_name"`
	InputAuthorship     *string           `json:"input_authorship"`
	InputRank           *string           `json:"input_rank"`
	ResolvedCandidateID pgtype.UUID       `json:"resolved_candidate_id"`
	Status              *ResolutionStatus `json:"status"`
}

func (q *Queries) UpsertTaxonResolution(ctx context.Context, arg UpsertTaxonResolutionParams) error {
	_, err := q.db.Exec(ctx, upsertTaxonResolution,
		arg.ImportID,
		arg.InputName,
		arg.InputAuthorship,
		arg.InputRank,
		arg.ResolvedCandidateID,
		arg.Status,
	)
	return err
}
