// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch_imports.sql

package biomedb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanUpStagingImport = `-- name: CleanUpStagingImport :exec
DELETE FROM import_samplings_occurrences
WHERE import_id = $1
`

func (q *Queries) CleanUpStagingImport(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cleanUpStagingImport, importID)
	return err
}

type CopyImportStagingParams struct {
	ImportID                    uuid.UUID             `json:"import_id"`
	SamplingHash                string                `json:"sampling_hash"`
	RowNumber                   int32                 `json:"row_number"`
	SamplingComments            *string               `json:"sampling_comments"`
	SiteCode                    *string               `json:"site_code"`
	SiteName                    *string               `json:"site_name"`
	SiteLocality                *string               `json:"site_locality"`
	SiteCountryCode             string                `json:"site_country_code"`
	CoordinatesPrecision        *int32                `json:"coordinates_precision"`
	Longitude                   float32               `json:"longitude"`
	Latitude                    float32               `json:"latitude"`
	Altitude                    *int32                `json:"altitude"`
	EventDate                   pgtype.Date           `json:"event_date"`
	EventDatePrecision          *EventDatePrecision   `json:"event_date_precision"`
	PerformedBy                 []string              `json:"performed_by"`
	Duration                    *int32                `json:"duration"`
	AccessPoints                []string              `json:"access_points"`
	SamplingTargets             []string              `json:"sampling_targets"`
	SamplingFixatives           []string              `json:"sampling_fixatives"`
	SamplingMethods             []string              `json:"sampling_methods"`
	Habitats                    []string              `json:"habitats"`
	OccurrenceCode              *string               `json:"occurrence_code"`
	TypeStatus                  *OccurrenceTypeStatus `json:"type_status"`
	OccurrenceComments          *string               `json:"occurrence_comments"`
	TaxonName                   string                `json:"taxon_name"`
	TaxonRank                   *string               `json:"taxon_rank"`
	TaxonAuthorship             *string               `json:"taxon_authorship"`
	VerbatimIdentification      *string               `json:"verbatim_identification"`
	IdentifiedBy                []string              `json:"identified_by"`
	IdentificationDate          pgtype.Date           `json:"identification_date"`
	IdentificationDatePrecision *EventDatePrecision   `json:"identification_date_precision"`
	IdentificationConfer        bool                  `json:"identification_confer"`
	IdentificationAddendum      *string               `json:"identification_addendum"`
	ContentDescription          *string               `json:"content_description"`
	QuantityExact               *int32                `json:"quantity_exact"`
	QuantityLower               *int32                `json:"quantity_lower"`
	QuantityUpper               *int32                `json:"quantity_upper"`
	Sources                     []string              `json:"sources"`
}

const getImportState = `-- name: GetImportState :one
SELECT import_id, label, created_at, completed_at
FROM import_workflows
WHERE import_id = $1::uuid
`

func (q *Queries) GetImportState(ctx context.Context, importID uuid.UUID) (ImportWorkflow, error) {
	row := q.db.QueryRow(ctx, getImportState, importID)
	var i ImportWorkflow
	err := row.Scan(
		&i.ImportID,
		&i.Label,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const initBatchImport = `-- name: InitBatchImport :one
INSERT INTO import_workflows (label)
VALUES ($1::TEXT)
RETURNING import_id, label, created_at, completed_at
`

func (q *Queries) InitBatchImport(ctx context.Context, label string) (ImportWorkflow, error) {
	row := q.db.QueryRow(ctx, initBatchImport, label)
	var i ImportWorkflow
	err := row.Scan(
		&i.ImportID,
		&i.Label,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertOccurrencesFromStaging = `-- name: InsertOccurrencesFromStaging :exec
INSERT INTO occurrences (
        id,
        code,
        sampling_id,
        type_status,
        comments,
        taxon_id,
        verbatim_identification,
        identified_by,
        identification_date,
        identification_date_precision,
        identification_confer,
        identification_addendum,
        content_description,
        quantity_exact,
        quantity_lower,
        quantity_upper,
        sources
    )
SELECT i.occurrence_id,
    i.occurrence_code,
    s.id,
    i.type_status,
    i.comments,
    r.taxon_id,
    i.verbatim_identification,
    i.identified_by,
    i.identification_date,
    i.identification_date_precision,
    i.identification_confer,
    i.identification_addendum,
    i.content_description,
    i.quantity_exact,
    i.quantity_lower,
    i.quantity_upper,
    i.sources
FROM import_samplings_occurrences i
    JOIN samplings s ON s.sampling_hash = i.sampling_hash
    JOIN taxon_candidates r ON r.import_id = i.import_id
    AND r.input_name = i.taxon_scientific_name
WHERE i.import_id = $1
`

func (q *Queries) InsertOccurrencesFromStaging(ctx context.Context, importID uuid.UUID) error {
	_, err := q.db.Exec(ctx, insertOccurrencesFromStaging, importID)
	return err
}

const listImportWorkflows = `-- name: ListImportWorkflows :many
SELECT import_id, label, created_at, completed_at
FROM import_workflows
ORDER BY created_at DESC
`

func (q *Queries) ListImportWorkflows(ctx context.Context) ([]ImportWorkflow, error) {
	rows, err := q.db.Query(ctx, listImportWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportWorkflow{}
	for rows.Next() {
		var i ImportWorkflow
		if err := rows.Scan(
			&i.ImportID,
			&i.Label,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSamplingsFromStaging = `-- name: UpsertSamplingsFromStaging :many
INSERT INTO samplings (
        sampling_hash,
        notes,
        site_code,
        site_name,
        site_locality,
        site_country_code,
        coordinates_precision,
        coordinates,
        altitude,
        event_date,
        event_date_precision,
        performed_by,
        duration,
        access_points
    )
SELECT DISTINCT sampling_hash,
    notes,
    site_code,
    site_name,
    site_locality,
    site_country_code,
    coordinates_precision,
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326),
    altitude,
    event_date,
    event_date_precision,
    performed_by,
    duration,
    access_points
FROM import_samplings_occurrences
WHERE import_id = $1 ON CONFLICT (sampling_hash) DO
UPDATE
SET notes = EXCLUDED.notes
RETURNING id
`

func (q *Queries) UpsertSamplingsFromStaging(ctx context.Context, importID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, upsertSamplingsFromStaging, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
