// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countries.sql

package biomedb

import (
	"context"
)

const coordinatesToCountry = `-- name: CoordinatesToCountry :many
SELECT c.code, c.name, c.continent, c.subcontinent, c.geom
FROM countries c
WHERE ST_Contains(
        c.geom,
        ST_SetSRID(
            ST_Point(
                $1::double precision,
                $2::double precision
            ),
            4326
        )
    )
LIMIT 1
`

func (q *Queries) CoordinatesToCountry(ctx context.Context, latitude float64, longitude float64) ([]Country, error) {
	rows, err := q.db.Query(ctx, coordinatesToCountry, latitude, longitude)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Continent,
			&i.Subcontinent,
			&i.Geom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCountry = `-- name: InsertCountry :exec
INSERT INTO countries (code, name, continent, subcontinent, geom)
VALUES (
        $1,
        $2,
        $3,
        $4,
        ST_SetSRID(ST_GeomFromGeoJSON($5::json), 4326)
    )
`

type InsertCountryParams struct {
	Code         string `json:"code"`
	Name         string `json:"name"`
	Continent    string `json:"continent"`
	Subcontinent string `json:"subcontinent"`
	Geom         []byte `json:"geom"`
}

func (q *Queries) InsertCountry(ctx context.Context, arg InsertCountryParams) error {
	_, err := q.db.Exec(ctx, insertCountry,
		arg.Code,
		arg.Name,
		arg.Continent,
		arg.Subcontinent,
		arg.Geom,
	)
	return err
}

const listCountries = `-- name: ListCountries :many
SELECT code, name, continent, subcontinent, geom
FROM countries
ORDER BY name
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Continent,
			&i.Subcontinent,
			&i.Geom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountriesSummary = `-- name: ListCountriesSummary :many
SELECT c.name,
    c.code,
    c.continent,
    c.subcontinent,
    COUNT(DISTINCT s.id) AS sampling_count,
    COUNT(DISTINCT o.id) AS occurrence_count
FROM countries c
    LEFT JOIN samplings s ON s.site_country_code = c.code
    LEFT JOIN occurrences o ON o.sampling_id = s.id
GROUP BY c.code
ORDER BY c.name
`

type ListCountriesSummaryRow struct {
	Name            string `json:"name"`
	Code            string `json:"code"`
	Continent       string `json:"continent"`
	Subcontinent    string `json:"subcontinent"`
	SamplingCount   int64  `json:"sampling_count"`
	OccurrenceCount int64  `json:"occurrence_count"`
}

func (q *Queries) ListCountriesSummary(ctx context.Context) ([]ListCountriesSummaryRow, error) {
	rows, err := q.db.Query(ctx, listCountriesSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountriesSummaryRow{}
	for rows.Next() {
		var i ListCountriesSummaryRow
		if err := rows.Scan(
			&i.Name,
			&i.Code,
			&i.Continent,
			&i.Subcontinent,
			&i.SamplingCount,
			&i.OccurrenceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
