// Code generated by enumgen. DO NOT EDIT.

package biomedb

import (
	"fmt"
	"reflect"

	"github.com/danielgtaylor/huma/v2"
)

var CoordinatesPrecisionValues = []CoordinatesPrecision{
	CoordinatesPrecision100m,
	CoordinatesPrecision1km,
	CoordinatesPrecision10km,
	CoordinatesPrecision10100km,
}

var CoordinatesPrecisionHierarchy = map[CoordinatesPrecision]int{
	CoordinatesPrecision100m:    0,
	CoordinatesPrecision1km:     1,
	CoordinatesPrecision10km:    2,
	CoordinatesPrecision10100km: 3,
}

func (u *CoordinatesPrecision) UnmarshalCSV(v []byte) error {
	e := CoordinatesPrecision(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid CoordinatesPrecision value: %s", v)
}

func (u CoordinatesPrecision) IsGreater(v CoordinatesPrecision) bool {
	return CoordinatesPrecisionHierarchy[u] > CoordinatesPrecisionHierarchy[v]
}

func (u CoordinatesPrecision) IsGreaterEqual(v CoordinatesPrecision) bool {
	return CoordinatesPrecisionHierarchy[u] >= CoordinatesPrecisionHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u CoordinatesPrecision) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["CoordinatesPrecision"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "CoordinatesPrecision")
		schemaRef.Title = "CoordinatesPrecision"

		for _, v := range CoordinatesPrecisionValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["CoordinatesPrecision"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/CoordinatesPrecision",
	}
}
func (u NullCoordinatesPrecision) Get() (CoordinatesPrecision, bool) {
	return u.CoordinatesPrecision, u.Valid
}

var DuplicateSourceValues = []DuplicateSource{
	DuplicateSourceExisting,
	DuplicateSourceStaging,
}

var DuplicateSourceHierarchy = map[DuplicateSource]int{
	DuplicateSourceExisting: 0,
	DuplicateSourceStaging:  1,
}

func (u *DuplicateSource) UnmarshalCSV(v []byte) error {
	e := DuplicateSource(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid DuplicateSource value: %s", v)
}

func (u DuplicateSource) IsGreater(v DuplicateSource) bool {
	return DuplicateSourceHierarchy[u] > DuplicateSourceHierarchy[v]
}

func (u DuplicateSource) IsGreaterEqual(v DuplicateSource) bool {
	return DuplicateSourceHierarchy[u] >= DuplicateSourceHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u DuplicateSource) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["DuplicateSource"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "DuplicateSource")
		schemaRef.Title = "DuplicateSource"

		for _, v := range DuplicateSourceValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["DuplicateSource"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/DuplicateSource",
	}
}
func (u NullDuplicateSource) Get() (DuplicateSource, bool) {
	return u.DuplicateSource, u.Valid
}

var EventDatePrecisionValues = []EventDatePrecision{
	EventDatePrecisionDay,
	EventDatePrecisionMonth,
	EventDatePrecisionYear,
}

var EventDatePrecisionHierarchy = map[EventDatePrecision]int{
	EventDatePrecisionDay:   0,
	EventDatePrecisionMonth: 1,
	EventDatePrecisionYear:  2,
}

func (u *EventDatePrecision) UnmarshalCSV(v []byte) error {
	e := EventDatePrecision(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid EventDatePrecision value: %s", v)
}

func (u EventDatePrecision) IsGreater(v EventDatePrecision) bool {
	return EventDatePrecisionHierarchy[u] > EventDatePrecisionHierarchy[v]
}

func (u EventDatePrecision) IsGreaterEqual(v EventDatePrecision) bool {
	return EventDatePrecisionHierarchy[u] >= EventDatePrecisionHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u EventDatePrecision) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["EventDatePrecision"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "EventDatePrecision")
		schemaRef.Title = "EventDatePrecision"

		for _, v := range EventDatePrecisionValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["EventDatePrecision"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/EventDatePrecision",
	}
}
func (u NullEventDatePrecision) Get() (EventDatePrecision, bool) {
	return u.EventDatePrecision, u.Valid
}

var InvitationStatusValues = []InvitationStatus{
	InvitationStatusPending,
	InvitationStatusRedeemed,
	InvitationStatusCancelled,
	InvitationStatusExpired,
}

var InvitationStatusHierarchy = map[InvitationStatus]int{
	InvitationStatusPending:   0,
	InvitationStatusRedeemed:  1,
	InvitationStatusCancelled: 2,
	InvitationStatusExpired:   3,
}

func (u *InvitationStatus) UnmarshalCSV(v []byte) error {
	e := InvitationStatus(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid InvitationStatus value: %s", v)
}

func (u InvitationStatus) IsGreater(v InvitationStatus) bool {
	return InvitationStatusHierarchy[u] > InvitationStatusHierarchy[v]
}

func (u InvitationStatus) IsGreaterEqual(v InvitationStatus) bool {
	return InvitationStatusHierarchy[u] >= InvitationStatusHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u InvitationStatus) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["InvitationStatus"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "InvitationStatus")
		schemaRef.Title = "InvitationStatus"

		for _, v := range InvitationStatusValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["InvitationStatus"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/InvitationStatus",
	}
}
func (u NullInvitationStatus) Get() (InvitationStatus, bool) {
	return u.InvitationStatus, u.Valid
}

var OccurrenceOrderByValues = []OccurrenceOrderBy{
	OccurrenceOrderByCode,
	OccurrenceOrderBySiteName,
	OccurrenceOrderBySiteCode,
	OccurrenceOrderByEventDate,
	OccurrenceOrderByTaxonName,
	OccurrenceOrderByCreatedAt,
	OccurrenceOrderByUpdatedAt,
}

var OccurrenceOrderByHierarchy = map[OccurrenceOrderBy]int{
	OccurrenceOrderByCode:      0,
	OccurrenceOrderBySiteName:  1,
	OccurrenceOrderBySiteCode:  2,
	OccurrenceOrderByEventDate: 3,
	OccurrenceOrderByTaxonName: 4,
	OccurrenceOrderByCreatedAt: 5,
	OccurrenceOrderByUpdatedAt: 6,
}

func (u *OccurrenceOrderBy) UnmarshalCSV(v []byte) error {
	e := OccurrenceOrderBy(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid OccurrenceOrderBy value: %s", v)
}

func (u OccurrenceOrderBy) IsGreater(v OccurrenceOrderBy) bool {
	return OccurrenceOrderByHierarchy[u] > OccurrenceOrderByHierarchy[v]
}

func (u OccurrenceOrderBy) IsGreaterEqual(v OccurrenceOrderBy) bool {
	return OccurrenceOrderByHierarchy[u] >= OccurrenceOrderByHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u OccurrenceOrderBy) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["OccurrenceOrderBy"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "OccurrenceOrderBy")
		schemaRef.Title = "OccurrenceOrderBy"

		for _, v := range OccurrenceOrderByValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["OccurrenceOrderBy"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/OccurrenceOrderBy",
	}
}
func (u NullOccurrenceOrderBy) Get() (OccurrenceOrderBy, bool) {
	return u.OccurrenceOrderBy, u.Valid
}

var OccurrenceTypeStatusValues = []OccurrenceTypeStatus{
	OccurrenceTypeStatusHOLOTYPE,
	OccurrenceTypeStatusNEOTYPE,
	OccurrenceTypeStatusTOPOTYPE,
}

var OccurrenceTypeStatusHierarchy = map[OccurrenceTypeStatus]int{
	OccurrenceTypeStatusHOLOTYPE: 0,
	OccurrenceTypeStatusNEOTYPE:  1,
	OccurrenceTypeStatusTOPOTYPE: 2,
}

func (u *OccurrenceTypeStatus) UnmarshalCSV(v []byte) error {
	e := OccurrenceTypeStatus(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid OccurrenceTypeStatus value: %s", v)
}

func (u OccurrenceTypeStatus) IsGreater(v OccurrenceTypeStatus) bool {
	return OccurrenceTypeStatusHierarchy[u] > OccurrenceTypeStatusHierarchy[v]
}

func (u OccurrenceTypeStatus) IsGreaterEqual(v OccurrenceTypeStatus) bool {
	return OccurrenceTypeStatusHierarchy[u] >= OccurrenceTypeStatusHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u OccurrenceTypeStatus) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["OccurrenceTypeStatus"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "OccurrenceTypeStatus")
		schemaRef.Title = "OccurrenceTypeStatus"

		for _, v := range OccurrenceTypeStatusValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["OccurrenceTypeStatus"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/OccurrenceTypeStatus",
	}
}
func (u NullOccurrenceTypeStatus) Get() (OccurrenceTypeStatus, bool) {
	return u.OccurrenceTypeStatus, u.Valid
}

var PublicationResolutionStatusValues = []PublicationResolutionStatus{
	PublicationResolutionStatusPending,
	PublicationResolutionStatusResolved,
	PublicationResolutionStatusFailed,
	PublicationResolutionStatusManualRequired,
}

var PublicationResolutionStatusHierarchy = map[PublicationResolutionStatus]int{
	PublicationResolutionStatusPending:        0,
	PublicationResolutionStatusResolved:       1,
	PublicationResolutionStatusFailed:         2,
	PublicationResolutionStatusManualRequired: 3,
}

func (u *PublicationResolutionStatus) UnmarshalCSV(v []byte) error {
	e := PublicationResolutionStatus(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid PublicationResolutionStatus value: %s", v)
}

func (u PublicationResolutionStatus) IsGreater(v PublicationResolutionStatus) bool {
	return PublicationResolutionStatusHierarchy[u] > PublicationResolutionStatusHierarchy[v]
}

func (u PublicationResolutionStatus) IsGreaterEqual(v PublicationResolutionStatus) bool {
	return PublicationResolutionStatusHierarchy[u] >= PublicationResolutionStatusHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u PublicationResolutionStatus) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["PublicationResolutionStatus"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "PublicationResolutionStatus")
		schemaRef.Title = "PublicationResolutionStatus"

		for _, v := range PublicationResolutionStatusValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["PublicationResolutionStatus"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/PublicationResolutionStatus",
	}
}
func (u NullPublicationResolutionStatus) Get() (PublicationResolutionStatus, bool) {
	return u.PublicationResolutionStatus, u.Valid
}

var PublicationResolutionTypeValues = []PublicationResolutionType{
	PublicationResolutionTypeCrossref,
	PublicationResolutionTypeDoi,
	PublicationResolutionTypeVerbatim,
	PublicationResolutionTypeManual,
}

var PublicationResolutionTypeHierarchy = map[PublicationResolutionType]int{
	PublicationResolutionTypeCrossref: 0,
	PublicationResolutionTypeDoi:      1,
	PublicationResolutionTypeVerbatim: 2,
	PublicationResolutionTypeManual:   3,
}

func (u *PublicationResolutionType) UnmarshalCSV(v []byte) error {
	e := PublicationResolutionType(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid PublicationResolutionType value: %s", v)
}

func (u PublicationResolutionType) IsGreater(v PublicationResolutionType) bool {
	return PublicationResolutionTypeHierarchy[u] > PublicationResolutionTypeHierarchy[v]
}

func (u PublicationResolutionType) IsGreaterEqual(v PublicationResolutionType) bool {
	return PublicationResolutionTypeHierarchy[u] >= PublicationResolutionTypeHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u PublicationResolutionType) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["PublicationResolutionType"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "PublicationResolutionType")
		schemaRef.Title = "PublicationResolutionType"

		for _, v := range PublicationResolutionTypeValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["PublicationResolutionType"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/PublicationResolutionType",
	}
}
func (u NullPublicationResolutionType) Get() (PublicationResolutionType, bool) {
	return u.PublicationResolutionType, u.Valid
}

var ResolutionStatusValues = []ResolutionStatus{
	ResolutionStatusPending,
	ResolutionStatusAutoResolved,
	ResolutionStatusUserResolved,
	ResolutionStatusNeedsDecision,
}

var ResolutionStatusHierarchy = map[ResolutionStatus]int{
	ResolutionStatusPending:       0,
	ResolutionStatusAutoResolved:  1,
	ResolutionStatusUserResolved:  2,
	ResolutionStatusNeedsDecision: 3,
}

func (u *ResolutionStatus) UnmarshalCSV(v []byte) error {
	e := ResolutionStatus(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid ResolutionStatus value: %s", v)
}

func (u ResolutionStatus) IsGreater(v ResolutionStatus) bool {
	return ResolutionStatusHierarchy[u] > ResolutionStatusHierarchy[v]
}

func (u ResolutionStatus) IsGreaterEqual(v ResolutionStatus) bool {
	return ResolutionStatusHierarchy[u] >= ResolutionStatusHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u ResolutionStatus) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["ResolutionStatus"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "ResolutionStatus")
		schemaRef.Title = "ResolutionStatus"

		for _, v := range ResolutionStatusValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["ResolutionStatus"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/ResolutionStatus",
	}
}
func (u NullResolutionStatus) Get() (ResolutionStatus, bool) {
	return u.ResolutionStatus, u.Valid
}

var SortDirectionValues = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

var SortDirectionHierarchy = map[SortDirection]int{
	SortDirectionAsc:  0,
	SortDirectionDesc: 1,
}

func (u *SortDirection) UnmarshalCSV(v []byte) error {
	e := SortDirection(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid SortDirection value: %s", v)
}

func (u SortDirection) IsGreater(v SortDirection) bool {
	return SortDirectionHierarchy[u] > SortDirectionHierarchy[v]
}

func (u SortDirection) IsGreaterEqual(v SortDirection) bool {
	return SortDirectionHierarchy[u] >= SortDirectionHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u SortDirection) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["SortDirection"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "SortDirection")
		schemaRef.Title = "SortDirection"

		for _, v := range SortDirectionValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["SortDirection"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/SortDirection",
	}
}
func (u NullSortDirection) Get() (SortDirection, bool) {
	return u.SortDirection, u.Valid
}

var TaxonGBIFStatusValues = []TaxonGBIFStatus{
	TaxonGBIFStatusSkipped,
	TaxonGBIFStatusPending,
	TaxonGBIFStatusCompleted,
	TaxonGBIFStatusFailed,
}

var TaxonGBIFStatusHierarchy = map[TaxonGBIFStatus]int{
	TaxonGBIFStatusSkipped:   0,
	TaxonGBIFStatusPending:   1,
	TaxonGBIFStatusCompleted: 2,
	TaxonGBIFStatusFailed:    3,
}

func (u *TaxonGBIFStatus) UnmarshalCSV(v []byte) error {
	e := TaxonGBIFStatus(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid TaxonGBIFStatus value: %s", v)
}

func (u TaxonGBIFStatus) IsGreater(v TaxonGBIFStatus) bool {
	return TaxonGBIFStatusHierarchy[u] > TaxonGBIFStatusHierarchy[v]
}

func (u TaxonGBIFStatus) IsGreaterEqual(v TaxonGBIFStatus) bool {
	return TaxonGBIFStatusHierarchy[u] >= TaxonGBIFStatusHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u TaxonGBIFStatus) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["TaxonGBIFStatus"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "TaxonGBIFStatus")
		schemaRef.Title = "TaxonGBIFStatus"

		for _, v := range TaxonGBIFStatusValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["TaxonGBIFStatus"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/TaxonGBIFStatus",
	}
}
func (u NullTaxonGBIFStatus) Get() (TaxonGBIFStatus, bool) {
	return u.TaxonGBIFStatus, u.Valid
}

var TaxonMatchSourceValues = []TaxonMatchSource{
	TaxonMatchSourceInternal,
	TaxonMatchSourceGBIF,
	TaxonMatchSourceManual,
}

var TaxonMatchSourceHierarchy = map[TaxonMatchSource]int{
	TaxonMatchSourceInternal: 0,
	TaxonMatchSourceGBIF:     1,
	TaxonMatchSourceManual:   2,
}

func (u *TaxonMatchSource) UnmarshalCSV(v []byte) error {
	e := TaxonMatchSource(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid TaxonMatchSource value: %s", v)
}

func (u TaxonMatchSource) IsGreater(v TaxonMatchSource) bool {
	return TaxonMatchSourceHierarchy[u] > TaxonMatchSourceHierarchy[v]
}

func (u TaxonMatchSource) IsGreaterEqual(v TaxonMatchSource) bool {
	return TaxonMatchSourceHierarchy[u] >= TaxonMatchSourceHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u TaxonMatchSource) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["TaxonMatchSource"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "TaxonMatchSource")
		schemaRef.Title = "TaxonMatchSource"

		for _, v := range TaxonMatchSourceValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["TaxonMatchSource"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/TaxonMatchSource",
	}
}
func (u NullTaxonMatchSource) Get() (TaxonMatchSource, bool) {
	return u.TaxonMatchSource, u.Valid
}

var TaxonMatchTypeValues = []TaxonMatchType{
	TaxonMatchTypeExact,
	TaxonMatchTypeFuzzy,
	TaxonMatchTypeNameOnly,
}

var TaxonMatchTypeHierarchy = map[TaxonMatchType]int{
	TaxonMatchTypeExact:    0,
	TaxonMatchTypeFuzzy:    1,
	TaxonMatchTypeNameOnly: 2,
}

func (u *TaxonMatchType) UnmarshalCSV(v []byte) error {
	e := TaxonMatchType(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid TaxonMatchType value: %s", v)
}

func (u TaxonMatchType) IsGreater(v TaxonMatchType) bool {
	return TaxonMatchTypeHierarchy[u] > TaxonMatchTypeHierarchy[v]
}

func (u TaxonMatchType) IsGreaterEqual(v TaxonMatchType) bool {
	return TaxonMatchTypeHierarchy[u] >= TaxonMatchTypeHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u TaxonMatchType) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["TaxonMatchType"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "TaxonMatchType")
		schemaRef.Title = "TaxonMatchType"

		for _, v := range TaxonMatchTypeValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["TaxonMatchType"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/TaxonMatchType",
	}
}
func (u NullTaxonMatchType) Get() (TaxonMatchType, bool) {
	return u.TaxonMatchType, u.Valid
}

var TaxonRankValues = []TaxonRank{
	TaxonRankSUBSPECIES,
	TaxonRankSPECIES,
	TaxonRankSUBGENUS,
	TaxonRankGENUS,
	TaxonRankFAMILY,
	TaxonRankORDER,
	TaxonRankCLASS,
	TaxonRankPHYLUM,
	TaxonRankKINGDOM,
}

var TaxonRankHierarchy = map[TaxonRank]int{
	TaxonRankSUBSPECIES: 0,
	TaxonRankSPECIES:    1,
	TaxonRankSUBGENUS:   2,
	TaxonRankGENUS:      3,
	TaxonRankFAMILY:     4,
	TaxonRankORDER:      5,
	TaxonRankCLASS:      6,
	TaxonRankPHYLUM:     7,
	TaxonRankKINGDOM:    8,
}

func (u *TaxonRank) UnmarshalCSV(v []byte) error {
	e := TaxonRank(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid TaxonRank value: %s", v)
}

func (u TaxonRank) IsGreater(v TaxonRank) bool {
	return TaxonRankHierarchy[u] > TaxonRankHierarchy[v]
}

func (u TaxonRank) IsGreaterEqual(v TaxonRank) bool {
	return TaxonRankHierarchy[u] >= TaxonRankHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u TaxonRank) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["TaxonRank"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "TaxonRank")
		schemaRef.Title = "TaxonRank"

		for _, v := range TaxonRankValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["TaxonRank"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/TaxonRank",
	}
}
func (u NullTaxonRank) Get() (TaxonRank, bool) {
	return u.TaxonRank, u.Valid
}

var TaxonStatusValues = []TaxonStatus{
	TaxonStatusACCEPTED,
	TaxonStatusSYNONYM,
	TaxonStatusDOUBTFUL,
	TaxonStatusUNREFERENCED,
	TaxonStatusUNCLASSIFIED,
}

var TaxonStatusHierarchy = map[TaxonStatus]int{
	TaxonStatusACCEPTED:     0,
	TaxonStatusSYNONYM:      1,
	TaxonStatusDOUBTFUL:     2,
	TaxonStatusUNREFERENCED: 3,
	TaxonStatusUNCLASSIFIED: 4,
}

func (u *TaxonStatus) UnmarshalCSV(v []byte) error {
	e := TaxonStatus(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid TaxonStatus value: %s", v)
}

func (u TaxonStatus) IsGreater(v TaxonStatus) bool {
	return TaxonStatusHierarchy[u] > TaxonStatusHierarchy[v]
}

func (u TaxonStatus) IsGreaterEqual(v TaxonStatus) bool {
	return TaxonStatusHierarchy[u] >= TaxonStatusHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u TaxonStatus) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["TaxonStatus"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "TaxonStatus")
		schemaRef.Title = "TaxonStatus"

		for _, v := range TaxonStatusValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["TaxonStatus"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/TaxonStatus",
	}
}
func (u NullTaxonStatus) Get() (TaxonStatus, bool) {
	return u.TaxonStatus, u.Valid
}

var UserAccountRequestStatusValues = []UserAccountRequestStatus{
	UserAccountRequestStatusPending,
	UserAccountRequestStatusVerified,
	UserAccountRequestStatusCancelled,
	UserAccountRequestStatusExpired,
}

var UserAccountRequestStatusHierarchy = map[UserAccountRequestStatus]int{
	UserAccountRequestStatusPending:   0,
	UserAccountRequestStatusVerified:  1,
	UserAccountRequestStatusCancelled: 2,
	UserAccountRequestStatusExpired:   3,
}

func (u *UserAccountRequestStatus) UnmarshalCSV(v []byte) error {
	e := UserAccountRequestStatus(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid UserAccountRequestStatus value: %s", v)
}

func (u UserAccountRequestStatus) IsGreater(v UserAccountRequestStatus) bool {
	return UserAccountRequestStatusHierarchy[u] > UserAccountRequestStatusHierarchy[v]
}

func (u UserAccountRequestStatus) IsGreaterEqual(v UserAccountRequestStatus) bool {
	return UserAccountRequestStatusHierarchy[u] >= UserAccountRequestStatusHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u UserAccountRequestStatus) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["UserAccountRequestStatus"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "UserAccountRequestStatus")
		schemaRef.Title = "UserAccountRequestStatus"

		for _, v := range UserAccountRequestStatusValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["UserAccountRequestStatus"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/UserAccountRequestStatus",
	}
}
func (u NullUserAccountRequestStatus) Get() (UserAccountRequestStatus, bool) {
	return u.UserAccountRequestStatus, u.Valid
}

var UserEmailChangeRequestStatusValues = []UserEmailChangeRequestStatus{
	UserEmailChangeRequestStatusPending,
	UserEmailChangeRequestStatusVerified,
	UserEmailChangeRequestStatusApplied,
	UserEmailChangeRequestStatusCancelled,
	UserEmailChangeRequestStatusExpired,
}

var UserEmailChangeRequestStatusHierarchy = map[UserEmailChangeRequestStatus]int{
	UserEmailChangeRequestStatusPending:   0,
	UserEmailChangeRequestStatusVerified:  1,
	UserEmailChangeRequestStatusApplied:   2,
	UserEmailChangeRequestStatusCancelled: 3,
	UserEmailChangeRequestStatusExpired:   4,
}

func (u *UserEmailChangeRequestStatus) UnmarshalCSV(v []byte) error {
	e := UserEmailChangeRequestStatus(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid UserEmailChangeRequestStatus value: %s", v)
}

func (u UserEmailChangeRequestStatus) IsGreater(v UserEmailChangeRequestStatus) bool {
	return UserEmailChangeRequestStatusHierarchy[u] > UserEmailChangeRequestStatusHierarchy[v]
}

func (u UserEmailChangeRequestStatus) IsGreaterEqual(v UserEmailChangeRequestStatus) bool {
	return UserEmailChangeRequestStatusHierarchy[u] >= UserEmailChangeRequestStatusHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u UserEmailChangeRequestStatus) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["UserEmailChangeRequestStatus"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "UserEmailChangeRequestStatus")
		schemaRef.Title = "UserEmailChangeRequestStatus"

		for _, v := range UserEmailChangeRequestStatusValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["UserEmailChangeRequestStatus"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/UserEmailChangeRequestStatus",
	}
}
func (u NullUserEmailChangeRequestStatus) Get() (UserEmailChangeRequestStatus, bool) {
	return u.UserEmailChangeRequestStatus, u.Valid
}

var UserRoleValues = []UserRole{
	UserRoleVisitor,
	UserRoleContributor,
	UserRoleMaintainer,
	UserRoleAdmin,
}

var UserRoleHierarchy = map[UserRole]int{
	UserRoleVisitor:     0,
	UserRoleContributor: 1,
	UserRoleMaintainer:  2,
	UserRoleAdmin:       3,
}

func (u *UserRole) UnmarshalCSV(v []byte) error {
	e := UserRole(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid UserRole value: %s", v)
}

func (u UserRole) IsGreater(v UserRole) bool {
	return UserRoleHierarchy[u] > UserRoleHierarchy[v]
}

func (u UserRole) IsGreaterEqual(v UserRole) bool {
	return UserRoleHierarchy[u] >= UserRoleHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u UserRole) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["UserRole"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "UserRole")
		schemaRef.Title = "UserRole"

		for _, v := range UserRoleValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["UserRole"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/UserRole",
	}
}
func (u NullUserRole) Get() (UserRole, bool) {
	return u.UserRole, u.Valid
}

var VocabResolutionStatusValues = []VocabResolutionStatus{
	VocabResolutionStatusAuto,
	VocabResolutionStatusSelected,
	VocabResolutionStatusPending,
	VocabResolutionStatusRequestCreation,
	VocabResolutionStatusDiscard,
}

var VocabResolutionStatusHierarchy = map[VocabResolutionStatus]int{
	VocabResolutionStatusAuto:            0,
	VocabResolutionStatusSelected:        1,
	VocabResolutionStatusPending:         2,
	VocabResolutionStatusRequestCreation: 3,
	VocabResolutionStatusDiscard:         4,
}

func (u *VocabResolutionStatus) UnmarshalCSV(v []byte) error {
	e := VocabResolutionStatus(v)
	if e.Valid() {
		*u = e
		return nil
	}
	return fmt.Errorf("invalid VocabResolutionStatus value: %s", v)
}

func (u VocabResolutionStatus) IsGreater(v VocabResolutionStatus) bool {
	return VocabResolutionStatusHierarchy[u] > VocabResolutionStatusHierarchy[v]
}

func (u VocabResolutionStatus) IsGreaterEqual(v VocabResolutionStatus) bool {
	return VocabResolutionStatusHierarchy[u] >= VocabResolutionStatusHierarchy[v]
}

// Register enum in OpenAPI specification.
func (u VocabResolutionStatus) Schema(r huma.Registry) *huma.Schema {
	if r.Map()["VocabResolutionStatus"] == nil {
		schemaRef := r.Schema(reflect.TypeOf(""), true, "VocabResolutionStatus")
		schemaRef.Title = "VocabResolutionStatus"

		for _, v := range VocabResolutionStatusValues {
			schemaRef.Enum = append(schemaRef.Enum, string(v))
		}

		r.Map()["VocabResolutionStatus"] = schemaRef
	}

	return &huma.Schema{
		Ref: "#/components/schemas/VocabResolutionStatus",
	}
}
func (u NullVocabResolutionStatus) Get() (VocabResolutionStatus, bool) {
	return u.VocabResolutionStatus, u.Valid
}
