// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package biomedb

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	ulid "github.com/oklog/ulid/v2"
)

type CoordinatesPrecision string

const (
	CoordinatesPrecision100m    CoordinatesPrecision = "<100m"
	CoordinatesPrecision1km     CoordinatesPrecision = "<1km"
	CoordinatesPrecision10km    CoordinatesPrecision = "<10km"
	CoordinatesPrecision10100km CoordinatesPrecision = "10-100km"
)

func (e *CoordinatesPrecision) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoordinatesPrecision(s)
	case string:
		*e = CoordinatesPrecision(s)
	default:
		return fmt.Errorf("unsupported scan type for CoordinatesPrecision: %T", src)
	}
	return nil
}

type NullCoordinatesPrecision struct {
	CoordinatesPrecision CoordinatesPrecision `json:"coordinates_precision"`
	Valid                bool                 `json:"valid"` // Valid is true if CoordinatesPrecision is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoordinatesPrecision) Scan(value interface{}) error {
	if value == nil {
		ns.CoordinatesPrecision, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoordinatesPrecision.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoordinatesPrecision) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoordinatesPrecision), nil
}

func (e CoordinatesPrecision) Valid() bool {
	switch e {
	case CoordinatesPrecision100m,
		CoordinatesPrecision1km,
		CoordinatesPrecision10km,
		CoordinatesPrecision10100km:
		return true
	}
	return false
}

func AllCoordinatesPrecisionValues() []CoordinatesPrecision {
	return []CoordinatesPrecision{
		CoordinatesPrecision100m,
		CoordinatesPrecision1km,
		CoordinatesPrecision10km,
		CoordinatesPrecision10100km,
	}
}

type DuplicateSource string

const (
	DuplicateSourceExisting DuplicateSource = "existing"
	DuplicateSourceStaging  DuplicateSource = "staging"
)

func (e *DuplicateSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DuplicateSource(s)
	case string:
		*e = DuplicateSource(s)
	default:
		return fmt.Errorf("unsupported scan type for DuplicateSource: %T", src)
	}
	return nil
}

type NullDuplicateSource struct {
	DuplicateSource DuplicateSource `json:"duplicate_source"`
	Valid           bool            `json:"valid"` // Valid is true if DuplicateSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDuplicateSource) Scan(value interface{}) error {
	if value == nil {
		ns.DuplicateSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DuplicateSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDuplicateSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DuplicateSource), nil
}

func (e DuplicateSource) Valid() bool {
	switch e {
	case DuplicateSourceExisting,
		DuplicateSourceStaging:
		return true
	}
	return false
}

func AllDuplicateSourceValues() []DuplicateSource {
	return []DuplicateSource{
		DuplicateSourceExisting,
		DuplicateSourceStaging,
	}
}

type EventDatePrecision string

const (
	EventDatePrecisionDay   EventDatePrecision = "day"
	EventDatePrecisionMonth EventDatePrecision = "month"
	EventDatePrecisionYear  EventDatePrecision = "year"
)

func (e *EventDatePrecision) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventDatePrecision(s)
	case string:
		*e = EventDatePrecision(s)
	default:
		return fmt.Errorf("unsupported scan type for EventDatePrecision: %T", src)
	}
	return nil
}

type NullEventDatePrecision struct {
	EventDatePrecision EventDatePrecision `json:"event_date_precision"`
	Valid              bool               `json:"valid"` // Valid is true if EventDatePrecision is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventDatePrecision) Scan(value interface{}) error {
	if value == nil {
		ns.EventDatePrecision, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventDatePrecision.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventDatePrecision) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventDatePrecision), nil
}

func (e EventDatePrecision) Valid() bool {
	switch e {
	case EventDatePrecisionDay,
		EventDatePrecisionMonth,
		EventDatePrecisionYear:
		return true
	}
	return false
}

func AllEventDatePrecisionValues() []EventDatePrecision {
	return []EventDatePrecision{
		EventDatePrecisionDay,
		EventDatePrecisionMonth,
		EventDatePrecisionYear,
	}
}

type GBIFImportStatus string

const (
	GBIFImportStatusPending    GBIFImportStatus = "pending"
	GBIFImportStatusInProgress GBIFImportStatus = "in_progress"
	GBIFImportStatusCompleted  GBIFImportStatus = "completed"
	GBIFImportStatusFailed     GBIFImportStatus = "failed"
)

func (e *GBIFImportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GBIFImportStatus(s)
	case string:
		*e = GBIFImportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GBIFImportStatus: %T", src)
	}
	return nil
}

type NullGBIFImportStatus struct {
	GBIFImportStatus GBIFImportStatus `json:"gbif_import_status"`
	Valid            bool             `json:"valid"` // Valid is true if GBIFImportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGBIFImportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GBIFImportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GBIFImportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGBIFImportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GBIFImportStatus), nil
}

func (e GBIFImportStatus) Valid() bool {
	switch e {
	case GBIFImportStatusPending,
		GBIFImportStatusInProgress,
		GBIFImportStatusCompleted,
		GBIFImportStatusFailed:
		return true
	}
	return false
}

func AllGBIFImportStatusValues() []GBIFImportStatus {
	return []GBIFImportStatus{
		GBIFImportStatusPending,
		GBIFImportStatusInProgress,
		GBIFImportStatusCompleted,
		GBIFImportStatusFailed,
	}
}

type InvitationStatus string

const (
	InvitationStatusPending   InvitationStatus = "pending"
	InvitationStatusRedeemed  InvitationStatus = "redeemed"
	InvitationStatusCancelled InvitationStatus = "cancelled"
	InvitationStatusExpired   InvitationStatus = "expired"
)

func (e *InvitationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitationStatus(s)
	case string:
		*e = InvitationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitationStatus: %T", src)
	}
	return nil
}

type NullInvitationStatus struct {
	InvitationStatus InvitationStatus `json:"invitation_status"`
	Valid            bool             `json:"valid"` // Valid is true if InvitationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvitationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitationStatus), nil
}

func (e InvitationStatus) Valid() bool {
	switch e {
	case InvitationStatusPending,
		InvitationStatusRedeemed,
		InvitationStatusCancelled,
		InvitationStatusExpired:
		return true
	}
	return false
}

func AllInvitationStatusValues() []InvitationStatus {
	return []InvitationStatus{
		InvitationStatusPending,
		InvitationStatusRedeemed,
		InvitationStatusCancelled,
		InvitationStatusExpired,
	}
}

type OccurrenceOrderBy string

const (
	OccurrenceOrderByCode      OccurrenceOrderBy = "code"
	OccurrenceOrderBySiteName  OccurrenceOrderBy = "site_name"
	OccurrenceOrderBySiteCode  OccurrenceOrderBy = "site_code"
	OccurrenceOrderByEventDate OccurrenceOrderBy = "event_date"
	OccurrenceOrderByTaxonName OccurrenceOrderBy = "taxon_name"
	OccurrenceOrderByCreatedAt OccurrenceOrderBy = "created_at"
	OccurrenceOrderByUpdatedAt OccurrenceOrderBy = "updated_at"
)

func (e *OccurrenceOrderBy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OccurrenceOrderBy(s)
	case string:
		*e = OccurrenceOrderBy(s)
	default:
		return fmt.Errorf("unsupported scan type for OccurrenceOrderBy: %T", src)
	}
	return nil
}

type NullOccurrenceOrderBy struct {
	OccurrenceOrderBy OccurrenceOrderBy `json:"occurrence_order_by"`
	Valid             bool              `json:"valid"` // Valid is true if OccurrenceOrderBy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOccurrenceOrderBy) Scan(value interface{}) error {
	if value == nil {
		ns.OccurrenceOrderBy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OccurrenceOrderBy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOccurrenceOrderBy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OccurrenceOrderBy), nil
}

func (e OccurrenceOrderBy) Valid() bool {
	switch e {
	case OccurrenceOrderByCode,
		OccurrenceOrderBySiteName,
		OccurrenceOrderBySiteCode,
		OccurrenceOrderByEventDate,
		OccurrenceOrderByTaxonName,
		OccurrenceOrderByCreatedAt,
		OccurrenceOrderByUpdatedAt:
		return true
	}
	return false
}

func AllOccurrenceOrderByValues() []OccurrenceOrderBy {
	return []OccurrenceOrderBy{
		OccurrenceOrderByCode,
		OccurrenceOrderBySiteName,
		OccurrenceOrderBySiteCode,
		OccurrenceOrderByEventDate,
		OccurrenceOrderByTaxonName,
		OccurrenceOrderByCreatedAt,
		OccurrenceOrderByUpdatedAt,
	}
}

type OccurrenceTypeStatus string

const (
	OccurrenceTypeStatusHOLOTYPE OccurrenceTypeStatus = "HOLOTYPE"
	OccurrenceTypeStatusNEOTYPE  OccurrenceTypeStatus = "NEOTYPE"
	OccurrenceTypeStatusTOPOTYPE OccurrenceTypeStatus = "TOPOTYPE"
)

func (e *OccurrenceTypeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OccurrenceTypeStatus(s)
	case string:
		*e = OccurrenceTypeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OccurrenceTypeStatus: %T", src)
	}
	return nil
}

type NullOccurrenceTypeStatus struct {
	OccurrenceTypeStatus OccurrenceTypeStatus `json:"occurrence_type_status"`
	Valid                bool                 `json:"valid"` // Valid is true if OccurrenceTypeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOccurrenceTypeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OccurrenceTypeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OccurrenceTypeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOccurrenceTypeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OccurrenceTypeStatus), nil
}

func (e OccurrenceTypeStatus) Valid() bool {
	switch e {
	case OccurrenceTypeStatusHOLOTYPE,
		OccurrenceTypeStatusNEOTYPE,
		OccurrenceTypeStatusTOPOTYPE:
		return true
	}
	return false
}

func AllOccurrenceTypeStatusValues() []OccurrenceTypeStatus {
	return []OccurrenceTypeStatus{
		OccurrenceTypeStatusHOLOTYPE,
		OccurrenceTypeStatusNEOTYPE,
		OccurrenceTypeStatusTOPOTYPE,
	}
}

type ResolutionStatus string

const (
	ResolutionStatusPending       ResolutionStatus = "pending"
	ResolutionStatusAutoResolved  ResolutionStatus = "auto_resolved"
	ResolutionStatusUserResolved  ResolutionStatus = "user_resolved"
	ResolutionStatusNeedsDecision ResolutionStatus = "needs_decision"
)

func (e *ResolutionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResolutionStatus(s)
	case string:
		*e = ResolutionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ResolutionStatus: %T", src)
	}
	return nil
}

type NullResolutionStatus struct {
	ResolutionStatus ResolutionStatus `json:"resolution_status"`
	Valid            bool             `json:"valid"` // Valid is true if ResolutionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResolutionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ResolutionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResolutionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResolutionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResolutionStatus), nil
}

func (e ResolutionStatus) Valid() bool {
	switch e {
	case ResolutionStatusPending,
		ResolutionStatusAutoResolved,
		ResolutionStatusUserResolved,
		ResolutionStatusNeedsDecision:
		return true
	}
	return false
}

func AllResolutionStatusValues() []ResolutionStatus {
	return []ResolutionStatus{
		ResolutionStatusPending,
		ResolutionStatusAutoResolved,
		ResolutionStatusUserResolved,
		ResolutionStatusNeedsDecision,
	}
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "asc"
	SortDirectionDesc SortDirection = "desc"
)

func (e *SortDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SortDirection(s)
	case string:
		*e = SortDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for SortDirection: %T", src)
	}
	return nil
}

type NullSortDirection struct {
	SortDirection SortDirection `json:"sort_direction"`
	Valid         bool          `json:"valid"` // Valid is true if SortDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSortDirection) Scan(value interface{}) error {
	if value == nil {
		ns.SortDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SortDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSortDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SortDirection), nil
}

func (e SortDirection) Valid() bool {
	switch e {
	case SortDirectionAsc,
		SortDirectionDesc:
		return true
	}
	return false
}

func AllSortDirectionValues() []SortDirection {
	return []SortDirection{
		SortDirectionAsc,
		SortDirectionDesc,
	}
}

type TaxonGBIFStatus string

const (
	TaxonGBIFStatusSkipped   TaxonGBIFStatus = "skipped"
	TaxonGBIFStatusPending   TaxonGBIFStatus = "pending"
	TaxonGBIFStatusCompleted TaxonGBIFStatus = "completed"
	TaxonGBIFStatusFailed    TaxonGBIFStatus = "failed"
)

func (e *TaxonGBIFStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaxonGBIFStatus(s)
	case string:
		*e = TaxonGBIFStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaxonGBIFStatus: %T", src)
	}
	return nil
}

type NullTaxonGBIFStatus struct {
	TaxonGBIFStatus TaxonGBIFStatus `json:"taxon_gbif_status"`
	Valid           bool            `json:"valid"` // Valid is true if TaxonGBIFStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaxonGBIFStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaxonGBIFStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaxonGBIFStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaxonGBIFStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaxonGBIFStatus), nil
}

func (e TaxonGBIFStatus) Valid() bool {
	switch e {
	case TaxonGBIFStatusSkipped,
		TaxonGBIFStatusPending,
		TaxonGBIFStatusCompleted,
		TaxonGBIFStatusFailed:
		return true
	}
	return false
}

func AllTaxonGBIFStatusValues() []TaxonGBIFStatus {
	return []TaxonGBIFStatus{
		TaxonGBIFStatusSkipped,
		TaxonGBIFStatusPending,
		TaxonGBIFStatusCompleted,
		TaxonGBIFStatusFailed,
	}
}

type TaxonMatchSource string

const (
	TaxonMatchSourceInternal TaxonMatchSource = "internal"
	TaxonMatchSourceGBIF     TaxonMatchSource = "gbif"
	TaxonMatchSourceManual   TaxonMatchSource = "manual"
)

func (e *TaxonMatchSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaxonMatchSource(s)
	case string:
		*e = TaxonMatchSource(s)
	default:
		return fmt.Errorf("unsupported scan type for TaxonMatchSource: %T", src)
	}
	return nil
}

type NullTaxonMatchSource struct {
	TaxonMatchSource TaxonMatchSource `json:"taxon_match_source"`
	Valid            bool             `json:"valid"` // Valid is true if TaxonMatchSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaxonMatchSource) Scan(value interface{}) error {
	if value == nil {
		ns.TaxonMatchSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaxonMatchSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaxonMatchSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaxonMatchSource), nil
}

func (e TaxonMatchSource) Valid() bool {
	switch e {
	case TaxonMatchSourceInternal,
		TaxonMatchSourceGBIF,
		TaxonMatchSourceManual:
		return true
	}
	return false
}

func AllTaxonMatchSourceValues() []TaxonMatchSource {
	return []TaxonMatchSource{
		TaxonMatchSourceInternal,
		TaxonMatchSourceGBIF,
		TaxonMatchSourceManual,
	}
}

type TaxonMatchType string

const (
	TaxonMatchTypeExact    TaxonMatchType = "exact"
	TaxonMatchTypeFuzzy    TaxonMatchType = "fuzzy"
	TaxonMatchTypeNameOnly TaxonMatchType = "name_only"
)

func (e *TaxonMatchType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaxonMatchType(s)
	case string:
		*e = TaxonMatchType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaxonMatchType: %T", src)
	}
	return nil
}

type NullTaxonMatchType struct {
	TaxonMatchType TaxonMatchType `json:"taxon_match_type"`
	Valid          bool           `json:"valid"` // Valid is true if TaxonMatchType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaxonMatchType) Scan(value interface{}) error {
	if value == nil {
		ns.TaxonMatchType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaxonMatchType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaxonMatchType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaxonMatchType), nil
}

func (e TaxonMatchType) Valid() bool {
	switch e {
	case TaxonMatchTypeExact,
		TaxonMatchTypeFuzzy,
		TaxonMatchTypeNameOnly:
		return true
	}
	return false
}

func AllTaxonMatchTypeValues() []TaxonMatchType {
	return []TaxonMatchType{
		TaxonMatchTypeExact,
		TaxonMatchTypeFuzzy,
		TaxonMatchTypeNameOnly,
	}
}

type TaxonRank string

const (
	TaxonRankSUBSPECIES TaxonRank = "SUBSPECIES"
	TaxonRankSPECIES    TaxonRank = "SPECIES"
	TaxonRankSUBGENUS   TaxonRank = "SUBGENUS"
	TaxonRankGENUS      TaxonRank = "GENUS"
	TaxonRankFAMILY     TaxonRank = "FAMILY"
	TaxonRankORDER      TaxonRank = "ORDER"
	TaxonRankCLASS      TaxonRank = "CLASS"
	TaxonRankPHYLUM     TaxonRank = "PHYLUM"
	TaxonRankKINGDOM    TaxonRank = "KINGDOM"
)

func (e *TaxonRank) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaxonRank(s)
	case string:
		*e = TaxonRank(s)
	default:
		return fmt.Errorf("unsupported scan type for TaxonRank: %T", src)
	}
	return nil
}

type NullTaxonRank struct {
	TaxonRank TaxonRank `json:"taxon_rank"`
	Valid     bool      `json:"valid"` // Valid is true if TaxonRank is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaxonRank) Scan(value interface{}) error {
	if value == nil {
		ns.TaxonRank, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaxonRank.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaxonRank) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaxonRank), nil
}

func (e TaxonRank) Valid() bool {
	switch e {
	case TaxonRankSUBSPECIES,
		TaxonRankSPECIES,
		TaxonRankSUBGENUS,
		TaxonRankGENUS,
		TaxonRankFAMILY,
		TaxonRankORDER,
		TaxonRankCLASS,
		TaxonRankPHYLUM,
		TaxonRankKINGDOM:
		return true
	}
	return false
}

func AllTaxonRankValues() []TaxonRank {
	return []TaxonRank{
		TaxonRankSUBSPECIES,
		TaxonRankSPECIES,
		TaxonRankSUBGENUS,
		TaxonRankGENUS,
		TaxonRankFAMILY,
		TaxonRankORDER,
		TaxonRankCLASS,
		TaxonRankPHYLUM,
		TaxonRankKINGDOM,
	}
}

type TaxonStatus string

const (
	TaxonStatusACCEPTED     TaxonStatus = "ACCEPTED"
	TaxonStatusSYNONYM      TaxonStatus = "SYNONYM"
	TaxonStatusDOUBTFUL     TaxonStatus = "DOUBTFUL"
	TaxonStatusUNREFERENCED TaxonStatus = "UNREFERENCED"
	TaxonStatusUNCLASSIFIED TaxonStatus = "UNCLASSIFIED"
)

func (e *TaxonStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaxonStatus(s)
	case string:
		*e = TaxonStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaxonStatus: %T", src)
	}
	return nil
}

type NullTaxonStatus struct {
	TaxonStatus TaxonStatus `json:"taxon_status"`
	Valid       bool        `json:"valid"` // Valid is true if TaxonStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaxonStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaxonStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaxonStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaxonStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaxonStatus), nil
}

func (e TaxonStatus) Valid() bool {
	switch e {
	case TaxonStatusACCEPTED,
		TaxonStatusSYNONYM,
		TaxonStatusDOUBTFUL,
		TaxonStatusUNREFERENCED,
		TaxonStatusUNCLASSIFIED:
		return true
	}
	return false
}

func AllTaxonStatusValues() []TaxonStatus {
	return []TaxonStatus{
		TaxonStatusACCEPTED,
		TaxonStatusSYNONYM,
		TaxonStatusDOUBTFUL,
		TaxonStatusUNREFERENCED,
		TaxonStatusUNCLASSIFIED,
	}
}

type UserAccountRequestStatus string

const (
	UserAccountRequestStatusPending   UserAccountRequestStatus = "pending"
	UserAccountRequestStatusVerified  UserAccountRequestStatus = "verified"
	UserAccountRequestStatusCancelled UserAccountRequestStatus = "cancelled"
	UserAccountRequestStatusExpired   UserAccountRequestStatus = "expired"
)

func (e *UserAccountRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserAccountRequestStatus(s)
	case string:
		*e = UserAccountRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserAccountRequestStatus: %T", src)
	}
	return nil
}

type NullUserAccountRequestStatus struct {
	UserAccountRequestStatus UserAccountRequestStatus `json:"user_account_request_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if UserAccountRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserAccountRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserAccountRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserAccountRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserAccountRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserAccountRequestStatus), nil
}

func (e UserAccountRequestStatus) Valid() bool {
	switch e {
	case UserAccountRequestStatusPending,
		UserAccountRequestStatusVerified,
		UserAccountRequestStatusCancelled,
		UserAccountRequestStatusExpired:
		return true
	}
	return false
}

func AllUserAccountRequestStatusValues() []UserAccountRequestStatus {
	return []UserAccountRequestStatus{
		UserAccountRequestStatusPending,
		UserAccountRequestStatusVerified,
		UserAccountRequestStatusCancelled,
		UserAccountRequestStatusExpired,
	}
}

type UserEmailChangeRequestStatus string

const (
	UserEmailChangeRequestStatusPending   UserEmailChangeRequestStatus = "pending"
	UserEmailChangeRequestStatusVerified  UserEmailChangeRequestStatus = "verified"
	UserEmailChangeRequestStatusApplied   UserEmailChangeRequestStatus = "applied"
	UserEmailChangeRequestStatusCancelled UserEmailChangeRequestStatus = "cancelled"
	UserEmailChangeRequestStatusExpired   UserEmailChangeRequestStatus = "expired"
)

func (e *UserEmailChangeRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserEmailChangeRequestStatus(s)
	case string:
		*e = UserEmailChangeRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserEmailChangeRequestStatus: %T", src)
	}
	return nil
}

type NullUserEmailChangeRequestStatus struct {
	UserEmailChangeRequestStatus UserEmailChangeRequestStatus `json:"user_email_change_request_status"`
	Valid                        bool                         `json:"valid"` // Valid is true if UserEmailChangeRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserEmailChangeRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserEmailChangeRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserEmailChangeRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserEmailChangeRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserEmailChangeRequestStatus), nil
}

func (e UserEmailChangeRequestStatus) Valid() bool {
	switch e {
	case UserEmailChangeRequestStatusPending,
		UserEmailChangeRequestStatusVerified,
		UserEmailChangeRequestStatusApplied,
		UserEmailChangeRequestStatusCancelled,
		UserEmailChangeRequestStatusExpired:
		return true
	}
	return false
}

func AllUserEmailChangeRequestStatusValues() []UserEmailChangeRequestStatus {
	return []UserEmailChangeRequestStatus{
		UserEmailChangeRequestStatusPending,
		UserEmailChangeRequestStatusVerified,
		UserEmailChangeRequestStatusApplied,
		UserEmailChangeRequestStatusCancelled,
		UserEmailChangeRequestStatusExpired,
	}
}

type UserRole string

const (
	UserRoleVisitor     UserRole = "Visitor"
	UserRoleContributor UserRole = "Contributor"
	UserRoleMaintainer  UserRole = "Maintainer"
	UserRoleAdmin       UserRole = "Admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

func (e UserRole) Valid() bool {
	switch e {
	case UserRoleVisitor,
		UserRoleContributor,
		UserRoleMaintainer,
		UserRoleAdmin:
		return true
	}
	return false
}

func AllUserRoleValues() []UserRole {
	return []UserRole{
		UserRoleVisitor,
		UserRoleContributor,
		UserRoleMaintainer,
		UserRoleAdmin,
	}
}

type VocabResolutionStatus string

const (
	VocabResolutionStatusAuto            VocabResolutionStatus = "auto"
	VocabResolutionStatusSelected        VocabResolutionStatus = "selected"
	VocabResolutionStatusPending         VocabResolutionStatus = "pending"
	VocabResolutionStatusRequestCreation VocabResolutionStatus = "request_creation"
	VocabResolutionStatusDiscard         VocabResolutionStatus = "discard"
)

func (e *VocabResolutionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VocabResolutionStatus(s)
	case string:
		*e = VocabResolutionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VocabResolutionStatus: %T", src)
	}
	return nil
}

type NullVocabResolutionStatus struct {
	VocabResolutionStatus VocabResolutionStatus `json:"vocab_resolution_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if VocabResolutionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVocabResolutionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VocabResolutionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VocabResolutionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVocabResolutionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VocabResolutionStatus), nil
}

func (e VocabResolutionStatus) Valid() bool {
	switch e {
	case VocabResolutionStatusAuto,
		VocabResolutionStatusSelected,
		VocabResolutionStatusPending,
		VocabResolutionStatusRequestCreation,
		VocabResolutionStatusDiscard:
		return true
	}
	return false
}

func AllVocabResolutionStatusValues() []VocabResolutionStatus {
	return []VocabResolutionStatus{
		VocabResolutionStatusAuto,
		VocabResolutionStatusSelected,
		VocabResolutionStatusPending,
		VocabResolutionStatusRequestCreation,
		VocabResolutionStatusDiscard,
	}
}

type AbioticMeasurement struct {
	SamplingID uuid.UUID      `json:"sampling_id"`
	ParamID    uuid.UUID      `json:"param_id"`
	Value      pgtype.Numeric `json:"value"`
}

type AbioticParam struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Code        string    `json:"code"`
	Description *string   `json:"description"`
	Unit        string    `json:"unit"`
}

type Article struct {
	ID       uuid.UUID `json:"id"`
	Authors  []string  `json:"authors"`
	Year     int32     `json:"year"`
	Title    *string   `json:"title"`
	Journal  *string   `json:"journal"`
	Verbatim *string   `json:"verbatim"`
	Doi      *string   `json:"doi"`
	Comments *string   `json:"comments"`
}

type Country struct {
	Code         string      `json:"code"`
	Name         string      `json:"name"`
	Continent    string      `json:"continent"`
	Subcontinent string      `json:"subcontinent"`
	Geom         interface{} `json:"geom"`
}

type Dataset struct {
	ID          ulid.ULID `json:"id"`
	Label       string    `json:"label"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description"`
	Pinned      bool      `json:"pinned"`
	CreatedAt   time.Time `json:"created_at"`
}

type DatasetsCurator struct {
	DatasetID ulid.ULID `json:"dataset_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type DatasetsPublication struct {
	DatasetID ulid.ULID `json:"dataset_id"`
	ArticleID uuid.UUID `json:"article_id"`
}

type EventsSamplingMethod struct {
	SamplingID uuid.UUID `json:"sampling_id"`
	MethodID   uuid.UUID `json:"method_id"`
}

type Fixative struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

type GBIFDependency struct {
	ImportHash string `json:"import_hash"`
	Key        int32  `json:"key"`
}

type GBIFStaging struct {
	Key              int32    `json:"key"`
	Parent           *string  `json:"parent"`
	ParentKey        *int32   `json:"parent_key"`
	CanonicalName    string   `json:"canonical_name"`
	ScientificName   string   `json:"scientific_name"`
	Status           string   `json:"status"`
	Rank             string   `json:"rank"`
	NameType         string   `json:"name_type"`
	KingdomKey       *int32   `json:"kingdom_key"`
	PhylumKey        *int32   `json:"phylum_key"`
	ClassKey         *int32   `json:"class_key"`
	OrderKey         *int32   `json:"order_key"`
	FamilyKey        *int32   `json:"family_key"`
	GenusKey         *int32   `json:"genus_key"`
	SpeciesKey       *int32   `json:"species_key"`
	HigherTaxonKeys  []int32  `json:"higher_taxon_keys"`
	HigherTaxonNames []string `json:"higher_taxon_names"`
	Authorship       *string  `json:"authorship"`
	NumDescendants   *int32   `json:"num_descendants"`
	AcceptedKey      *int32   `json:"accepted_key"`
	AcceptedName     *string  `json:"accepted_name"`
}

type GeoapifyUsage struct {
	ID            int32     `json:"id"`
	UsageDate     time.Time `json:"usage_date"`
	RequestsCount int32     `json:"requests_count"`
}

type Habitat struct {
	ID             uuid.UUID `json:"id"`
	Label          string    `json:"label"`
	Description    *string   `json:"description"`
	HabitatGroupID uuid.UUID `json:"habitat_group_id"`
}

type HabitatGroup struct {
	ID                uuid.UUID   `json:"id"`
	Label             string      `json:"label"`
	Description       *string     `json:"description"`
	ExclusiveElements bool        `json:"exclusive_elements"`
	ParentHabitatID   pgtype.UUID `json:"parent_habitat_id"`
}

type ImportBatch struct {
	ID          ulid.ULID `json:"id"`
	Label       string    `json:"label"`
	Slug        string    `json:"slug"`
	Description *string   `json:"description"`
	SubmittedBy *string   `json:"submitted_by"`
	AssembledBy []string  `json:"assembled_by"`
	CreatedAt   time.Time `json:"created_at"`
}

type ImportSamplingsOccurrence struct {
	ImportHash                  string                `json:"import_hash"`
	ImportedAt                  time.Time             `json:"imported_at"`
	RowNumber                   int32                 `json:"row_number"`
	SamplingHash                string                `json:"sampling_hash"`
	SamplingComments            *string               `json:"sampling_comments"`
	SiteCode                    *string               `json:"site_code"`
	SiteName                    *string               `json:"site_name"`
	SiteLocality                *string               `json:"site_locality"`
	SiteCountryCode             string                `json:"site_country_code"`
	CoordinatesPrecision        *int32                `json:"coordinates_precision"`
	Longitude                   float32               `json:"longitude"`
	Latitude                    float32               `json:"latitude"`
	Coordinates                 interface{}           `json:"coordinates"`
	Altitude                    *int32                `json:"altitude"`
	EventDate                   pgtype.Date           `json:"event_date"`
	EventDatePrecision          *EventDatePrecision   `json:"event_date_precision"`
	PerformedBy                 []string              `json:"performed_by"`
	Duration                    *int32                `json:"duration"`
	AccessPoints                []string              `json:"access_points"`
	SamplingTargets             []string              `json:"sampling_targets"`
	SamplingFixatives           []string              `json:"sampling_fixatives"`
	SamplingMethods             []string              `json:"sampling_methods"`
	Habitats                    []string              `json:"habitats"`
	OccurrenceCode              *string               `json:"occurrence_code"`
	TypeStatus                  *OccurrenceTypeStatus `json:"type_status"`
	TaxonName                   string                `json:"taxon_name"`
	TaxonAuthorship             *string               `json:"taxon_authorship"`
	TaxonScientificName         string                `json:"taxon_scientific_name"`
	TaxonRank                   *string               `json:"taxon_rank"`
	VerbatimIdentification      *string               `json:"verbatim_identification"`
	IdentifiedBy                []string              `json:"identified_by"`
	IdentificationDate          pgtype.Date           `json:"identification_date"`
	IdentificationDatePrecision *EventDatePrecision   `json:"identification_date_precision"`
	IdentificationConfer        bool                  `json:"identification_confer"`
	IdentificationAddendum      *string               `json:"identification_addendum"`
	ContentDescription          *string               `json:"content_description"`
	QuantityExact               *int32                `json:"quantity_exact"`
	QuantityLower               *int32                `json:"quantity_lower"`
	QuantityUpper               *int32                `json:"quantity_upper"`
	Sources                     []string              `json:"sources"`
	OccurrenceComments          *string               `json:"occurrence_comments"`
}

type ImportWorkflow struct {
	ImportHash            string             `json:"import_hash"`
	Label                 *string            `json:"label"`
	GBIFStatus            GBIFImportStatus   `json:"gbif_status"`
	GBIFCandidatesTotal   *int32             `json:"gbif_candidates_total"`
	GBIFCandidatesFetched *int32             `json:"gbif_candidates_fetched"`
	GBIFClaimedAt         pgtype.Timestamptz `json:"gbif_claimed_at"`
	GBIFUpdatedAt         pgtype.Timestamptz `json:"gbif_updated_at"`
	CreatedAt             time.Time          `json:"created_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
}

type Invitation struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	InviteeName string             `json:"invitee_name"`
	Role        UserRole           `json:"role"`
	Message     *string            `json:"message"`
	InviterID   pgtype.UUID        `json:"inviter_id"`
	Status      InvitationStatus   `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	ExpiresAt   time.Time          `json:"expires_at"`
	RedeemedAt  pgtype.Timestamptz `json:"redeemed_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	RevokedBy   pgtype.UUID        `json:"revoked_by"`
}

type InvitationToken struct {
	ID           uuid.UUID          `json:"id"`
	InvitationID uuid.UUID          `json:"invitation_id"`
	TokenHash    string             `json:"token_hash"`
	CreatedAt    time.Time          `json:"created_at"`
	Consumed     bool               `json:"consumed"`
	ConsumedBy   pgtype.UUID        `json:"consumed_by"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
}

type Occurrence struct {
	ID                          ulid.ULID             `json:"id"`
	Code                        string                `json:"code"`
	SamplingID                  uuid.UUID             `json:"sampling_id"`
	TypeStatus                  *OccurrenceTypeStatus `json:"type_status"`
	Comments                    *string               `json:"comments"`
	TaxonID                     uuid.UUID             `json:"taxon_id"`
	VerbatimIdentification      *string               `json:"verbatim_identification"`
	IdentifiedBy                []string              `json:"identified_by"`
	IdentificationDate          pgtype.Date           `json:"identification_date"`
	IdentificationDatePrecision *EventDatePrecision   `json:"identification_date_precision"`
	IdentificationConfer        bool                  `json:"identification_confer"`
	IdentificationAddendum      *string               `json:"identification_addendum"`
	ContentDescription          *string               `json:"content_description"`
	QuantityExact               *int32                `json:"quantity_exact"`
	QuantityLower               *int32                `json:"quantity_lower"`
	QuantityUpper               *int32                `json:"quantity_upper"`
	Sources                     []string              `json:"sources"`
	CreatedAt                   time.Time             `json:"created_at"`
	UpdatedAt                   time.Time             `json:"updated_at"`
	ImportBatchID               interface{}           `json:"import_batch_id"`
}

type OccurrenceCodeHistory struct {
	ID           uuid.UUID `json:"id"`
	OccurrenceID ulid.ULID `json:"occurrence_id"`
	Code         string    `json:"code"`
	CreatedAt    time.Time `json:"created_at"`
}

type OccurrenceCollection struct {
	OccurrenceID ulid.ULID `json:"occurrence_id"`
	Name         string    `json:"name"`
	Vouchers     []string  `json:"vouchers"`
}

type OccurrencesArticle struct {
	OccurrenceID ulid.ULID `json:"occurrence_id"`
	ArticleID    uuid.UUID `json:"article_id"`
}

type OccurrencesDataset struct {
	DatasetID    ulid.ULID `json:"dataset_id"`
	OccurrenceID ulid.ULID `json:"occurrence_id"`
}

type Sampling struct {
	ID                   uuid.UUID           `json:"id"`
	SamplingHash         string              `json:"sampling_hash"`
	Notes                *string             `json:"notes"`
	SiteCode             *string             `json:"site_code"`
	SiteName             *string             `json:"site_name"`
	SiteLocality         *string             `json:"site_locality"`
	SiteCountryCode      *string             `json:"site_country_code"`
	CoordinatesPrecision *int32              `json:"coordinates_precision"`
	Coordinates          interface{}         `json:"coordinates"`
	Latitude             float32             `json:"latitude"`
	Longitude            float32             `json:"longitude"`
	Altitude             *int32              `json:"altitude"`
	EventDate            pgtype.Date         `json:"event_date"`
	EventDatePrecision   *EventDatePrecision `json:"event_date_precision"`
	PerformedBy          []string            `json:"performed_by"`
	Duration             *int32              `json:"duration"`
	AccessPoints         []string            `json:"access_points"`
	H3Index              int64               `json:"h3_index"`
	SearchVector         interface{}         `json:"search_vector"`
}

type SamplingMethod struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

type SamplingMethodsResolution struct {
	ImportHash       string                `json:"import_hash"`
	InputText        string                `json:"input_text"`
	ResolvedMethodID pgtype.UUID           `json:"resolved_method_id"`
	Status           VocabResolutionStatus `json:"status"`
}

type SamplingTargetTaxa struct {
	SamplingID uuid.UUID `json:"sampling_id"`
	TaxonID    uuid.UUID `json:"taxon_id"`
}

type SamplingsFixative struct {
	SamplingID uuid.UUID `json:"sampling_id"`
	FixativeID uuid.UUID `json:"fixative_id"`
}

type SamplingsHabitat struct {
	SamplingID uuid.UUID `json:"sampling_id"`
	HabitatID  uuid.UUID `json:"habitat_id"`
}

type Setting struct {
	ID                     int32   `json:"id"`
	AppName                string  `json:"app_name"`
	AppSubtitle            *string `json:"app_subtitle"`
	AppDescription         *string `json:"app_description"`
	IsPublic               bool    `json:"is_public"`
	AccountRequestsEnabled bool    `json:"account_requests_enabled"`
	AdminEmail             string  `json:"admin_email"`
	MailFromAddress        string  `json:"mail_from_address"`
	MailFromName           string  `json:"mail_from_name"`
}

type TaxaStaging struct {
	ID              uuid.UUID        `json:"id"`
	ImportHash      string           `json:"import_hash"`
	Name            string           `json:"name"`
	Authorship      *string          `json:"authorship"`
	Rank            TaxonRank        `json:"rank"`
	Status          TaxonStatus      `json:"status"`
	ParentSource    TaxonMatchSource `json:"parent_source"`
	ParentTaxaID    pgtype.UUID      `json:"parent_taxa_id"`
	ParentGBIFID    *int32           `json:"parent_gbif_id"`
	ParentInputName *string          `json:"parent_input_name"`
}

type Taxon struct {
	ID              uuid.UUID   `json:"id"`
	GBIFID          *int32      `json:"gbif_id"`
	Name            string      `json:"name"`
	ScientificName  string      `json:"scientific_name"`
	Rank            TaxonRank   `json:"rank"`
	Status          TaxonStatus `json:"status"`
	Authorship      *string     `json:"authorship"`
	AcceptedTaxonID pgtype.UUID `json:"accepted_taxon_id"`
	ParentID        pgtype.UUID `json:"parent_id"`
	SearchVector    interface{} `json:"search_vector"`
	Comments        *string     `json:"comments"`
}

type TaxonCandidate struct {
	ImportHash string           `json:"import_hash"`
	InputName  string           `json:"input_name"`
	Source     TaxonMatchSource `json:"source"`
	MatchType  TaxonMatchType   `json:"match_type"`
	TaxonID    pgtype.UUID      `json:"taxon_id"`
	GBIFID     *int32           `json:"gbif_id"`
	Score      *float64         `json:"score"`
	Priority   int32            `json:"priority"`
	Name       string           `json:"name"`
	Authorship *string          `json:"authorship"`
	Rank       TaxonRank        `json:"rank"`
	Status     TaxonStatus      `json:"status"`
}

type TaxonClosure struct {
	AncestorID   uuid.UUID `json:"ancestor_id"`
	DescendantID uuid.UUID `json:"descendant_id"`
	Depth        int32     `json:"depth"`
}

type TaxonHierarchy struct {
	ID         uuid.UUID   `json:"id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Name       string      `json:"name"`
	Authorship *string     `json:"authorship"`
	Rank       TaxonRank   `json:"rank"`
	Status     TaxonStatus `json:"status"`
	Comments   *string     `json:"comments"`
	RootID     uuid.UUID   `json:"root_id"`
	Path       interface{} `json:"path"`
	Depth      int32       `json:"depth"`
}

type TaxonResolution struct {
	ImportHash string            `json:"import_hash"`
	InputName  string            `json:"input_name"`
	Source     *TaxonMatchSource `json:"source"`
	GBIFID     *int32            `json:"gbif_id"`
	TaxonID    pgtype.UUID       `json:"taxon_id"`
	StagingID  pgtype.UUID       `json:"staging_id"`
	Status     *ResolutionStatus `json:"status"`
	GBIFStatus *TaxonGBIFStatus  `json:"gbif_status"`
}

type TaxonSynonym struct {
	AcceptedTaxonID   uuid.UUID `json:"accepted_taxon_id"`
	AcceptedTaxonName string    `json:"accepted_taxon_name"`
	SynonymTaxonID    uuid.UUID `json:"synonym_taxon_id"`
	SynonymTaxonName  string    `json:"synonym_taxon_name"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Login           string             `json:"login"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Role            UserRole           `json:"role"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Organisation    *string            `json:"organisation"`
	Contact         *string            `json:"contact"`
	Bio             *string            `json:"bio"`
	FullName        string             `json:"full_name"`
	Active          bool               `json:"active"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

type UserAccountRequest struct {
	ID          uuid.UUID                `json:"id"`
	Email       string                   `json:"email"`
	Name        string                   `json:"name"`
	Motivations *string                  `json:"motivations"`
	Status      UserAccountRequestStatus `json:"status"`
	CreatedAt   time.Time                `json:"created_at"`
	ExpiresAt   time.Time                `json:"expires_at"`
	VerifiedAt  pgtype.Timestamptz       `json:"verified_at"`
	CancelledAt pgtype.Timestamptz       `json:"cancelled_at"`
}

type UserAccountRequestToken struct {
	ID                   uuid.UUID          `json:"id"`
	UserAccountRequestID uuid.UUID          `json:"user_account_request_id"`
	TokenHash            string             `json:"token_hash"`
	CreatedAt            time.Time          `json:"created_at"`
	Consumed             bool               `json:"consumed"`
	ConsumedAt           pgtype.Timestamptz `json:"consumed_at"`
}

type UserEmailChangeRequest struct {
	ID          uuid.UUID                    `json:"id"`
	UserID      uuid.UUID                    `json:"user_id"`
	Email       string                       `json:"email"`
	Status      UserEmailChangeRequestStatus `json:"status"`
	CreatedAt   time.Time                    `json:"created_at"`
	ExpiresAt   time.Time                    `json:"expires_at"`
	VerifiedAt  pgtype.Timestamptz           `json:"verified_at"`
	AppliedAt   pgtype.Timestamptz           `json:"applied_at"`
	CancelledAt pgtype.Timestamptz           `json:"cancelled_at"`
}

type UserEmailChangeRequestToken struct {
	ID                       uuid.UUID          `json:"id"`
	UserEmailChangeRequestID uuid.UUID          `json:"user_email_change_request_id"`
	TokenHash                string             `json:"token_hash"`
	CreatedAt                time.Time          `json:"created_at"`
	Consumed                 bool               `json:"consumed"`
	ConsumedBy               pgtype.UUID        `json:"consumed_by"`
	ConsumedAt               pgtype.Timestamptz `json:"consumed_at"`
}

type UserSession struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	CreatedAt        time.Time          `json:"created_at"`
	ExpiresAt        time.Time          `json:"expires_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	UserAgent        *string            `json:"user_agent"`
	IPAddress        *netip.Addr        `json:"ip_address"`
}
