// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: occurrences_summary_gen.sql

package biomedb

import (
	"context"

	"github.com/google/uuid"
)

const listOccurrencesByCountry = `-- name: ListOccurrencesByCountry :many
SELECT o.id, o.code, o.sampling_id, o.type_status, o.comments, o.taxon_id, o.verbatim_identification, o.identified_by, o.identification_date, o.identification_date_precision, o.identification_confer, o.identification_addendum, o.content_description, o.quantity_exact, o.quantity_lower, o.quantity_upper, o.sources, o.created_at, o.updated_at, o.import_batch_id,
    s.id, s.source_sampling_hash, s.comments, s.site_code, s.site_name, s.site_locality, s.site_country_code, s.coordinates_precision, s.coordinates, s.latitude, s.longitude, s.altitude, s.event_date, s.event_date_precision, s.performed_by, s.duration, s.access_points, s.import_batch_id, s.h3_index, s.search_vector,
    t.id, t.gbif_id, t.name, t.scientific_name, t.rank, t.status, t.authorship, t.accepted_taxon_id, t.parent_id, t.search_vector, t.comments,
    c.code, c.name, c.continent, c.subcontinent, c.geom
FROM occurrences o
INNER JOIN samplings s ON s.id = o.sampling_id
LEFT JOIN countries c ON c.code = s.site_country_code
INNER JOIN taxa t ON t.id = o.taxon_id
WHERE (
    $1::uuid[] IS NULL
    OR o.id = ANY($1)
)
ORDER BY c.name ASC, s.event_date DESC, t.name ASC, o.id ASC
LIMIT CASE
    WHEN $3::INTEGER IS NULL THEN NULL
    ELSE $3::INTEGER
END
OFFSET COALESCE($2::INTEGER, 0)
`

type ListOccurrencesByCountryParams struct {
	OccurrenceIDs []uuid.UUID `json:"occurrence_ids"`
	PageOffset    *int32      `json:"page_offset"`
	PageLimit     *int32      `json:"page_limit"`
}

type ListOccurrencesByCountryRow struct {
	Occurrence Occurrence `json:"occurrence"`
	Sampling   Sampling   `json:"sampling"`
	Taxon      Taxon      `json:"taxon"`
	Country    Country    `json:"country"`
}

func (q *Queries) ListOccurrencesByCountry(ctx context.Context, arg ListOccurrencesByCountryParams) ([]ListOccurrencesByCountryRow, error) {
	rows, err := q.db.Query(ctx, listOccurrencesByCountry, arg.OccurrenceIDs, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOccurrencesByCountryRow{}
	for rows.Next() {
		var i ListOccurrencesByCountryRow
		if err := rows.Scan(
			&i.Occurrence.ID,
			&i.Occurrence.Code,
			&i.Occurrence.SamplingID,
			&i.Occurrence.TypeStatus,
			&i.Occurrence.Comments,
			&i.Occurrence.TaxonID,
			&i.Occurrence.VerbatimIdentification,
			&i.Occurrence.IdentifiedBy,
			&i.Occurrence.IdentificationDate,
			&i.Occurrence.IdentificationDatePrecision,
			&i.Occurrence.IdentificationConfer,
			&i.Occurrence.IdentificationAddendum,
			&i.Occurrence.ContentDescription,
			&i.Occurrence.QuantityExact,
			&i.Occurrence.QuantityLower,
			&i.Occurrence.QuantityUpper,
			&i.Occurrence.Sources,
			&i.Occurrence.CreatedAt,
			&i.Occurrence.UpdatedAt,
			&i.Occurrence.ImportBatchID,
			&i.Sampling.ID,
			&i.Sampling.SourceSamplingHash,
			&i.Sampling.Comments,
			&i.Sampling.SiteCode,
			&i.Sampling.SiteName,
			&i.Sampling.SiteLocality,
			&i.Sampling.SiteCountryCode,
			&i.Sampling.CoordinatesPrecision,
			&i.Sampling.Coordinates,
			&i.Sampling.Latitude,
			&i.Sampling.Longitude,
			&i.Sampling.Altitude,
			&i.Sampling.EventDate,
			&i.Sampling.EventDatePrecision,
			&i.Sampling.PerformedBy,
			&i.Sampling.Duration,
			&i.Sampling.AccessPoints,
			&i.Sampling.ImportBatchID,
			&i.Sampling.H3Index,
			&i.Sampling.SearchVector,
			&i.Taxon.ID,
			&i.Taxon.GBIFID,
			&i.Taxon.Name,
			&i.Taxon.ScientificName,
			&i.Taxon.Rank,
			&i.Taxon.Status,
			&i.Taxon.Authorship,
			&i.Taxon.AcceptedTaxonID,
			&i.Taxon.ParentID,
			&i.Taxon.SearchVector,
			&i.Taxon.Comments,
			&i.Country.Code,
			&i.Country.Name,
			&i.Country.Continent,
			&i.Country.Subcontinent,
			&i.Country.Geom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOccurrencesByTaxon = `-- name: ListOccurrencesByTaxon :many
SELECT o.id, o.code, o.sampling_id, o.type_status, o.comments, o.taxon_id, o.verbatim_identification, o.identified_by, o.identification_date, o.identification_date_precision, o.identification_confer, o.identification_addendum, o.content_description, o.quantity_exact, o.quantity_lower, o.quantity_upper, o.sources, o.created_at, o.updated_at, o.import_batch_id,
    s.id, s.source_sampling_hash, s.comments, s.site_code, s.site_name, s.site_locality, s.site_country_code, s.coordinates_precision, s.coordinates, s.latitude, s.longitude, s.altitude, s.event_date, s.event_date_precision, s.performed_by, s.duration, s.access_points, s.import_batch_id, s.h3_index, s.search_vector,
    t.id, t.gbif_id, t.name, t.scientific_name, t.rank, t.status, t.authorship, t.accepted_taxon_id, t.parent_id, t.search_vector, t.comments,
    c.code, c.name, c.continent, c.subcontinent, c.geom
FROM occurrences o
INNER JOIN samplings s ON s.id = o.sampling_id
LEFT JOIN countries c ON c.code = s.site_country_code
INNER JOIN taxa t ON t.id = o.taxon_id
WHERE (
    $1::uuid[] IS NULL
    OR o.id = ANY($1)
)
ORDER BY t.name ASC, s.event_date DESC, c.name ASC, o.id ASC
LIMIT CASE
    WHEN $3::INTEGER IS NULL THEN NULL
    ELSE $3::INTEGER
END
OFFSET COALESCE($2::INTEGER, 0)
`

type ListOccurrencesByTaxonParams struct {
	OccurrenceIDs []uuid.UUID `json:"occurrence_ids"`
	PageOffset    *int32      `json:"page_offset"`
	PageLimit     *int32      `json:"page_limit"`
}

type ListOccurrencesByTaxonRow struct {
	Occurrence Occurrence `json:"occurrence"`
	Sampling   Sampling   `json:"sampling"`
	Taxon      Taxon      `json:"taxon"`
	Country    Country    `json:"country"`
}

func (q *Queries) ListOccurrencesByTaxon(ctx context.Context, arg ListOccurrencesByTaxonParams) ([]ListOccurrencesByTaxonRow, error) {
	rows, err := q.db.Query(ctx, listOccurrencesByTaxon, arg.OccurrenceIDs, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOccurrencesByTaxonRow{}
	for rows.Next() {
		var i ListOccurrencesByTaxonRow
		if err := rows.Scan(
			&i.Occurrence.ID,
			&i.Occurrence.Code,
			&i.Occurrence.SamplingID,
			&i.Occurrence.TypeStatus,
			&i.Occurrence.Comments,
			&i.Occurrence.TaxonID,
			&i.Occurrence.VerbatimIdentification,
			&i.Occurrence.IdentifiedBy,
			&i.Occurrence.IdentificationDate,
			&i.Occurrence.IdentificationDatePrecision,
			&i.Occurrence.IdentificationConfer,
			&i.Occurrence.IdentificationAddendum,
			&i.Occurrence.ContentDescription,
			&i.Occurrence.QuantityExact,
			&i.Occurrence.QuantityLower,
			&i.Occurrence.QuantityUpper,
			&i.Occurrence.Sources,
			&i.Occurrence.CreatedAt,
			&i.Occurrence.UpdatedAt,
			&i.Occurrence.ImportBatchID,
			&i.Sampling.ID,
			&i.Sampling.SourceSamplingHash,
			&i.Sampling.Comments,
			&i.Sampling.SiteCode,
			&i.Sampling.SiteName,
			&i.Sampling.SiteLocality,
			&i.Sampling.SiteCountryCode,
			&i.Sampling.CoordinatesPrecision,
			&i.Sampling.Coordinates,
			&i.Sampling.Latitude,
			&i.Sampling.Longitude,
			&i.Sampling.Altitude,
			&i.Sampling.EventDate,
			&i.Sampling.EventDatePrecision,
			&i.Sampling.PerformedBy,
			&i.Sampling.Duration,
			&i.Sampling.AccessPoints,
			&i.Sampling.ImportBatchID,
			&i.Sampling.H3Index,
			&i.Sampling.SearchVector,
			&i.Taxon.ID,
			&i.Taxon.GBIFID,
			&i.Taxon.Name,
			&i.Taxon.ScientificName,
			&i.Taxon.Rank,
			&i.Taxon.Status,
			&i.Taxon.Authorship,
			&i.Taxon.AcceptedTaxonID,
			&i.Taxon.ParentID,
			&i.Taxon.SearchVector,
			&i.Taxon.Comments,
			&i.Country.Code,
			&i.Country.Name,
			&i.Country.Continent,
			&i.Country.Subcontinent,
			&i.Country.Geom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOccurrencesSortByEventDateASC = `-- name: ListOccurrencesSortByEventDateASC :many
SELECT o.id, o.code, o.sampling_id, o.type_status, o.comments, o.taxon_id, o.verbatim_identification, o.identified_by, o.identification_date, o.identification_date_precision, o.identification_confer, o.identification_addendum, o.content_description, o.quantity_exact, o.quantity_lower, o.quantity_upper, o.sources, o.created_at, o.updated_at, o.import_batch_id,
    s.id, s.source_sampling_hash, s.comments, s.site_code, s.site_name, s.site_locality, s.site_country_code, s.coordinates_precision, s.coordinates, s.latitude, s.longitude, s.altitude, s.event_date, s.event_date_precision, s.performed_by, s.duration, s.access_points, s.import_batch_id, s.h3_index, s.search_vector,
    t.id, t.gbif_id, t.name, t.scientific_name, t.rank, t.status, t.authorship, t.accepted_taxon_id, t.parent_id, t.search_vector, t.comments,
    c.code, c.name, c.continent, c.subcontinent, c.geom
FROM occurrences o
INNER JOIN samplings s ON s.id = o.sampling_id
LEFT JOIN countries c ON c.code = s.site_country_code
INNER JOIN taxa t ON t.id = o.taxon_id
WHERE (
    $1::uuid[] IS NULL
    OR o.id = ANY($1)
)
ORDER BY s.event_date ASC, t.name ASC, c.name ASC, o.id ASC
LIMIT CASE
    WHEN $3::INTEGER IS NULL THEN NULL
    ELSE $3::INTEGER
END
OFFSET COALESCE($2::INTEGER, 0)
`

type ListOccurrencesSortByEventDateASCParams struct {
	OccurrenceIDs []uuid.UUID `json:"occurrence_ids"`
	PageOffset    *int32      `json:"page_offset"`
	PageLimit     *int32      `json:"page_limit"`
}

type ListOccurrencesSortByEventDateASCRow struct {
	Occurrence Occurrence `json:"occurrence"`
	Sampling   Sampling   `json:"sampling"`
	Taxon      Taxon      `json:"taxon"`
	Country    Country    `json:"country"`
}

func (q *Queries) ListOccurrencesSortByEventDateASC(ctx context.Context, arg ListOccurrencesSortByEventDateASCParams) ([]ListOccurrencesSortByEventDateASCRow, error) {
	rows, err := q.db.Query(ctx, listOccurrencesSortByEventDateASC, arg.OccurrenceIDs, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOccurrencesSortByEventDateASCRow{}
	for rows.Next() {
		var i ListOccurrencesSortByEventDateASCRow
		if err := rows.Scan(
			&i.Occurrence.ID,
			&i.Occurrence.Code,
			&i.Occurrence.SamplingID,
			&i.Occurrence.TypeStatus,
			&i.Occurrence.Comments,
			&i.Occurrence.TaxonID,
			&i.Occurrence.VerbatimIdentification,
			&i.Occurrence.IdentifiedBy,
			&i.Occurrence.IdentificationDate,
			&i.Occurrence.IdentificationDatePrecision,
			&i.Occurrence.IdentificationConfer,
			&i.Occurrence.IdentificationAddendum,
			&i.Occurrence.ContentDescription,
			&i.Occurrence.QuantityExact,
			&i.Occurrence.QuantityLower,
			&i.Occurrence.QuantityUpper,
			&i.Occurrence.Sources,
			&i.Occurrence.CreatedAt,
			&i.Occurrence.UpdatedAt,
			&i.Occurrence.ImportBatchID,
			&i.Sampling.ID,
			&i.Sampling.SourceSamplingHash,
			&i.Sampling.Comments,
			&i.Sampling.SiteCode,
			&i.Sampling.SiteName,
			&i.Sampling.SiteLocality,
			&i.Sampling.SiteCountryCode,
			&i.Sampling.CoordinatesPrecision,
			&i.Sampling.Coordinates,
			&i.Sampling.Latitude,
			&i.Sampling.Longitude,
			&i.Sampling.Altitude,
			&i.Sampling.EventDate,
			&i.Sampling.EventDatePrecision,
			&i.Sampling.PerformedBy,
			&i.Sampling.Duration,
			&i.Sampling.AccessPoints,
			&i.Sampling.ImportBatchID,
			&i.Sampling.H3Index,
			&i.Sampling.SearchVector,
			&i.Taxon.ID,
			&i.Taxon.GBIFID,
			&i.Taxon.Name,
			&i.Taxon.ScientificName,
			&i.Taxon.Rank,
			&i.Taxon.Status,
			&i.Taxon.Authorship,
			&i.Taxon.AcceptedTaxonID,
			&i.Taxon.ParentID,
			&i.Taxon.SearchVector,
			&i.Taxon.Comments,
			&i.Country.Code,
			&i.Country.Name,
			&i.Country.Continent,
			&i.Country.Subcontinent,
			&i.Country.Geom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOccurrencesSortByEventDateDESC = `-- name: ListOccurrencesSortByEventDateDESC :many
SELECT o.id, o.code, o.sampling_id, o.type_status, o.comments, o.taxon_id, o.verbatim_identification, o.identified_by, o.identification_date, o.identification_date_precision, o.identification_confer, o.identification_addendum, o.content_description, o.quantity_exact, o.quantity_lower, o.quantity_upper, o.sources, o.created_at, o.updated_at, o.import_batch_id,
    s.id, s.source_sampling_hash, s.comments, s.site_code, s.site_name, s.site_locality, s.site_country_code, s.coordinates_precision, s.coordinates, s.latitude, s.longitude, s.altitude, s.event_date, s.event_date_precision, s.performed_by, s.duration, s.access_points, s.import_batch_id, s.h3_index, s.search_vector,
    t.id, t.gbif_id, t.name, t.scientific_name, t.rank, t.status, t.authorship, t.accepted_taxon_id, t.parent_id, t.search_vector, t.comments,
    c.code, c.name, c.continent, c.subcontinent, c.geom
FROM occurrences o
INNER JOIN samplings s ON s.id = o.sampling_id
LEFT JOIN countries c ON c.code = s.site_country_code
INNER JOIN taxa t ON t.id = o.taxon_id
WHERE (
    $1::uuid[] IS NULL
    OR o.id = ANY($1)
)
ORDER BY s.event_date DESC, t.name ASC, c.name ASC, o.id ASC
LIMIT CASE
    WHEN $3::INTEGER IS NULL THEN NULL
    ELSE $3::INTEGER
END
OFFSET COALESCE($2::INTEGER, 0)
`

type ListOccurrencesSortByEventDateDESCParams struct {
	OccurrenceIDs []uuid.UUID `json:"occurrence_ids"`
	PageOffset    *int32      `json:"page_offset"`
	PageLimit     *int32      `json:"page_limit"`
}

type ListOccurrencesSortByEventDateDESCRow struct {
	Occurrence Occurrence `json:"occurrence"`
	Sampling   Sampling   `json:"sampling"`
	Taxon      Taxon      `json:"taxon"`
	Country    Country    `json:"country"`
}

func (q *Queries) ListOccurrencesSortByEventDateDESC(ctx context.Context, arg ListOccurrencesSortByEventDateDESCParams) ([]ListOccurrencesSortByEventDateDESCRow, error) {
	rows, err := q.db.Query(ctx, listOccurrencesSortByEventDateDESC, arg.OccurrenceIDs, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOccurrencesSortByEventDateDESCRow{}
	for rows.Next() {
		var i ListOccurrencesSortByEventDateDESCRow
		if err := rows.Scan(
			&i.Occurrence.ID,
			&i.Occurrence.Code,
			&i.Occurrence.SamplingID,
			&i.Occurrence.TypeStatus,
			&i.Occurrence.Comments,
			&i.Occurrence.TaxonID,
			&i.Occurrence.VerbatimIdentification,
			&i.Occurrence.IdentifiedBy,
			&i.Occurrence.IdentificationDate,
			&i.Occurrence.IdentificationDatePrecision,
			&i.Occurrence.IdentificationConfer,
			&i.Occurrence.IdentificationAddendum,
			&i.Occurrence.ContentDescription,
			&i.Occurrence.QuantityExact,
			&i.Occurrence.QuantityLower,
			&i.Occurrence.QuantityUpper,
			&i.Occurrence.Sources,
			&i.Occurrence.CreatedAt,
			&i.Occurrence.UpdatedAt,
			&i.Occurrence.ImportBatchID,
			&i.Sampling.ID,
			&i.Sampling.SourceSamplingHash,
			&i.Sampling.Comments,
			&i.Sampling.SiteCode,
			&i.Sampling.SiteName,
			&i.Sampling.SiteLocality,
			&i.Sampling.SiteCountryCode,
			&i.Sampling.CoordinatesPrecision,
			&i.Sampling.Coordinates,
			&i.Sampling.Latitude,
			&i.Sampling.Longitude,
			&i.Sampling.Altitude,
			&i.Sampling.EventDate,
			&i.Sampling.EventDatePrecision,
			&i.Sampling.PerformedBy,
			&i.Sampling.Duration,
			&i.Sampling.AccessPoints,
			&i.Sampling.ImportBatchID,
			&i.Sampling.H3Index,
			&i.Sampling.SearchVector,
			&i.Taxon.ID,
			&i.Taxon.GBIFID,
			&i.Taxon.Name,
			&i.Taxon.ScientificName,
			&i.Taxon.Rank,
			&i.Taxon.Status,
			&i.Taxon.Authorship,
			&i.Taxon.AcceptedTaxonID,
			&i.Taxon.ParentID,
			&i.Taxon.SearchVector,
			&i.Taxon.Comments,
			&i.Country.Code,
			&i.Country.Name,
			&i.Country.Continent,
			&i.Country.Subcontinent,
			&i.Country.Geom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
