// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: occurrences_summary_gen.sql

package biomedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fetchOccurrencesByCountry = `-- name: FetchOccurrencesByCountry :many
SELECT o.id,
    s.id as sampling_id,
    s.latitude,
    s.longitude,
    s.coordinates_precision,
    s.altitude,
    s.site_code,
    s.site_name,
    s.site_locality,
    c.code as country_code,
    c.name as country_name,
    s.event_date,
    s.event_date_precision,
    t.id AS taxon_id,
    t.name AS taxon_name,
    t.authorship AS taxon_authorship,
    t.rank AS taxon_rank,
    t.GBIF_ID AS taxon_gbif_id,
    t.status AS taxon_status,
    o.identification_confer,
    o.identification_addendum,
    o.identification_date,
    o.identification_date_precision,
    o.identified_by,
    o.type_status
FROM occurrences o
INNER JOIN samplings s ON s.id = o.sampling_id
LEFT JOIN countries c ON c.code = s.site_country_code
INNER JOIN taxa t ON t.id = o.taxon_id
WHERE (
    $1::uuid[] IS NULL
    OR o.id = ANY($1)
)
ORDER BY c.name ASC, s.event_date DESC, t.name ASC, o.id ASC
LIMIT CASE
    WHEN $3::INTEGER IS NULL THEN NULL
    ELSE $3::INTEGER
END
OFFSET COALESCE($2::INTEGER, 0)
`

type FetchOccurrencesByCountryParams struct {
	OccurrenceIds []pgtype.UUID `json:"occurrence_ids"`
	PageOffset    pgtype.Int4   `json:"page_offset"`
	PageLimit     pgtype.Int4   `json:"page_limit"`
}

type FetchOccurrencesByCountryRow struct {
	ID                          string                   `json:"id"`
	SamplingID                  pgtype.UUID              `json:"sampling_id"`
	Latitude                    float32                  `json:"latitude"`
	Longitude                   float32                  `json:"longitude"`
	CoordinatesPrecision        pgtype.Int4              `json:"coordinates_precision"`
	Altitude                    pgtype.Int4              `json:"altitude"`
	SiteCode                    pgtype.Text              `json:"site_code"`
	SiteName                    pgtype.Text              `json:"site_name"`
	SiteLocality                pgtype.Text              `json:"site_locality"`
	CountryCode                 pgtype.Text              `json:"country_code"`
	CountryName                 pgtype.Text              `json:"country_name"`
	EventDate                   pgtype.Date              `json:"event_date"`
	EventDatePrecision          NullEventDatePrecision   `json:"event_date_precision"`
	TaxonID                     pgtype.UUID              `json:"taxon_id"`
	TaxonName                   string                   `json:"taxon_name"`
	TaxonAuthorship             pgtype.Text              `json:"taxon_authorship"`
	TaxonRank                   TaxonRank                `json:"taxon_rank"`
	TaxonGbifID                 pgtype.Int4              `json:"taxon_gbif_id"`
	TaxonStatus                 TaxonStatus              `json:"taxon_status"`
	IdentificationConfer        bool                     `json:"identification_confer"`
	IdentificationAddendum      pgtype.Text              `json:"identification_addendum"`
	IdentificationDate          pgtype.Date              `json:"identification_date"`
	IdentificationDatePrecision NullEventDatePrecision   `json:"identification_date_precision"`
	IdentifiedBy                []string                 `json:"identified_by"`
	TypeStatus                  NullOccurrenceTypeStatus `json:"type_status"`
}

func (q *Queries) FetchOccurrencesByCountry(ctx context.Context, arg FetchOccurrencesByCountryParams) ([]FetchOccurrencesByCountryRow, error) {
	rows, err := q.db.Query(ctx, fetchOccurrencesByCountry, arg.OccurrenceIds, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchOccurrencesByCountryRow
	for rows.Next() {
		var i FetchOccurrencesByCountryRow
		if err := rows.Scan(
			&i.ID,
			&i.SamplingID,
			&i.Latitude,
			&i.Longitude,
			&i.CoordinatesPrecision,
			&i.Altitude,
			&i.SiteCode,
			&i.SiteName,
			&i.SiteLocality,
			&i.CountryCode,
			&i.CountryName,
			&i.EventDate,
			&i.EventDatePrecision,
			&i.TaxonID,
			&i.TaxonName,
			&i.TaxonAuthorship,
			&i.TaxonRank,
			&i.TaxonGbifID,
			&i.TaxonStatus,
			&i.IdentificationConfer,
			&i.IdentificationAddendum,
			&i.IdentificationDate,
			&i.IdentificationDatePrecision,
			&i.IdentifiedBy,
			&i.TypeStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchOccurrencesByTaxon = `-- name: FetchOccurrencesByTaxon :many
SELECT o.id,
    s.id as sampling_id,
    s.latitude,
    s.longitude,
    s.coordinates_precision,
    s.altitude,
    s.site_code,
    s.site_name,
    s.site_locality,
    c.code as country_code,
    c.name as country_name,
    s.event_date,
    s.event_date_precision,
    t.id AS taxon_id,
    t.name AS taxon_name,
    t.authorship AS taxon_authorship,
    t.rank AS taxon_rank,
    t.GBIF_ID AS taxon_gbif_id,
    t.status AS taxon_status,
    o.identification_confer,
    o.identification_addendum,
    o.identification_date,
    o.identification_date_precision,
    o.identified_by,
    o.type_status
FROM occurrences o
INNER JOIN samplings s ON s.id = o.sampling_id
LEFT JOIN countries c ON c.code = s.site_country_code
INNER JOIN taxa t ON t.id = o.taxon_id
WHERE (
    $1::uuid[] IS NULL
    OR o.id = ANY($1)
)
ORDER BY t.name ASC, s.event_date DESC, c.name ASC, o.id ASC
LIMIT CASE
    WHEN $3::INTEGER IS NULL THEN NULL
    ELSE $3::INTEGER
END
OFFSET COALESCE($2::INTEGER, 0)
`

type FetchOccurrencesByTaxonParams struct {
	OccurrenceIds []pgtype.UUID `json:"occurrence_ids"`
	PageOffset    pgtype.Int4   `json:"page_offset"`
	PageLimit     pgtype.Int4   `json:"page_limit"`
}

type FetchOccurrencesByTaxonRow struct {
	ID                          string                   `json:"id"`
	SamplingID                  pgtype.UUID              `json:"sampling_id"`
	Latitude                    float32                  `json:"latitude"`
	Longitude                   float32                  `json:"longitude"`
	CoordinatesPrecision        pgtype.Int4              `json:"coordinates_precision"`
	Altitude                    pgtype.Int4              `json:"altitude"`
	SiteCode                    pgtype.Text              `json:"site_code"`
	SiteName                    pgtype.Text              `json:"site_name"`
	SiteLocality                pgtype.Text              `json:"site_locality"`
	CountryCode                 pgtype.Text              `json:"country_code"`
	CountryName                 pgtype.Text              `json:"country_name"`
	EventDate                   pgtype.Date              `json:"event_date"`
	EventDatePrecision          NullEventDatePrecision   `json:"event_date_precision"`
	TaxonID                     pgtype.UUID              `json:"taxon_id"`
	TaxonName                   string                   `json:"taxon_name"`
	TaxonAuthorship             pgtype.Text              `json:"taxon_authorship"`
	TaxonRank                   TaxonRank                `json:"taxon_rank"`
	TaxonGbifID                 pgtype.Int4              `json:"taxon_gbif_id"`
	TaxonStatus                 TaxonStatus              `json:"taxon_status"`
	IdentificationConfer        bool                     `json:"identification_confer"`
	IdentificationAddendum      pgtype.Text              `json:"identification_addendum"`
	IdentificationDate          pgtype.Date              `json:"identification_date"`
	IdentificationDatePrecision NullEventDatePrecision   `json:"identification_date_precision"`
	IdentifiedBy                []string                 `json:"identified_by"`
	TypeStatus                  NullOccurrenceTypeStatus `json:"type_status"`
}

func (q *Queries) FetchOccurrencesByTaxon(ctx context.Context, arg FetchOccurrencesByTaxonParams) ([]FetchOccurrencesByTaxonRow, error) {
	rows, err := q.db.Query(ctx, fetchOccurrencesByTaxon, arg.OccurrenceIds, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchOccurrencesByTaxonRow
	for rows.Next() {
		var i FetchOccurrencesByTaxonRow
		if err := rows.Scan(
			&i.ID,
			&i.SamplingID,
			&i.Latitude,
			&i.Longitude,
			&i.CoordinatesPrecision,
			&i.Altitude,
			&i.SiteCode,
			&i.SiteName,
			&i.SiteLocality,
			&i.CountryCode,
			&i.CountryName,
			&i.EventDate,
			&i.EventDatePrecision,
			&i.TaxonID,
			&i.TaxonName,
			&i.TaxonAuthorship,
			&i.TaxonRank,
			&i.TaxonGbifID,
			&i.TaxonStatus,
			&i.IdentificationConfer,
			&i.IdentificationAddendum,
			&i.IdentificationDate,
			&i.IdentificationDatePrecision,
			&i.IdentifiedBy,
			&i.TypeStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchOccurrencesSortByEventDateASC = `-- name: FetchOccurrencesSortByEventDateASC :many
SELECT o.id,
    s.id as sampling_id,
    s.latitude,
    s.longitude,
    s.coordinates_precision,
    s.altitude,
    s.site_code,
    s.site_name,
    s.site_locality,
    c.code as country_code,
    c.name as country_name,
    s.event_date,
    s.event_date_precision,
    t.id AS taxon_id,
    t.name AS taxon_name,
    t.authorship AS taxon_authorship,
    t.rank AS taxon_rank,
    t.GBIF_ID AS taxon_gbif_id,
    t.status AS taxon_status,
    o.identification_confer,
    o.identification_addendum,
    o.identification_date,
    o.identification_date_precision,
    o.identified_by,
    o.type_status
FROM occurrences o
INNER JOIN samplings s ON s.id = o.sampling_id
LEFT JOIN countries c ON c.code = s.site_country_code
INNER JOIN taxa t ON t.id = o.taxon_id
WHERE (
    $1::uuid[] IS NULL
    OR o.id = ANY($1)
)
ORDER BY s.event_date ASC, t.name ASC, c.name ASC, o.id ASC
LIMIT CASE
    WHEN $3::INTEGER IS NULL THEN NULL
    ELSE $3::INTEGER
END
OFFSET COALESCE($2::INTEGER, 0)
`

type FetchOccurrencesSortByEventDateASCParams struct {
	OccurrenceIds []pgtype.UUID `json:"occurrence_ids"`
	PageOffset    pgtype.Int4   `json:"page_offset"`
	PageLimit     pgtype.Int4   `json:"page_limit"`
}

type FetchOccurrencesSortByEventDateASCRow struct {
	ID                          string                   `json:"id"`
	SamplingID                  pgtype.UUID              `json:"sampling_id"`
	Latitude                    float32                  `json:"latitude"`
	Longitude                   float32                  `json:"longitude"`
	CoordinatesPrecision        pgtype.Int4              `json:"coordinates_precision"`
	Altitude                    pgtype.Int4              `json:"altitude"`
	SiteCode                    pgtype.Text              `json:"site_code"`
	SiteName                    pgtype.Text              `json:"site_name"`
	SiteLocality                pgtype.Text              `json:"site_locality"`
	CountryCode                 pgtype.Text              `json:"country_code"`
	CountryName                 pgtype.Text              `json:"country_name"`
	EventDate                   pgtype.Date              `json:"event_date"`
	EventDatePrecision          NullEventDatePrecision   `json:"event_date_precision"`
	TaxonID                     pgtype.UUID              `json:"taxon_id"`
	TaxonName                   string                   `json:"taxon_name"`
	TaxonAuthorship             pgtype.Text              `json:"taxon_authorship"`
	TaxonRank                   TaxonRank                `json:"taxon_rank"`
	TaxonGbifID                 pgtype.Int4              `json:"taxon_gbif_id"`
	TaxonStatus                 TaxonStatus              `json:"taxon_status"`
	IdentificationConfer        bool                     `json:"identification_confer"`
	IdentificationAddendum      pgtype.Text              `json:"identification_addendum"`
	IdentificationDate          pgtype.Date              `json:"identification_date"`
	IdentificationDatePrecision NullEventDatePrecision   `json:"identification_date_precision"`
	IdentifiedBy                []string                 `json:"identified_by"`
	TypeStatus                  NullOccurrenceTypeStatus `json:"type_status"`
}

func (q *Queries) FetchOccurrencesSortByEventDateASC(ctx context.Context, arg FetchOccurrencesSortByEventDateASCParams) ([]FetchOccurrencesSortByEventDateASCRow, error) {
	rows, err := q.db.Query(ctx, fetchOccurrencesSortByEventDateASC, arg.OccurrenceIds, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchOccurrencesSortByEventDateASCRow
	for rows.Next() {
		var i FetchOccurrencesSortByEventDateASCRow
		if err := rows.Scan(
			&i.ID,
			&i.SamplingID,
			&i.Latitude,
			&i.Longitude,
			&i.CoordinatesPrecision,
			&i.Altitude,
			&i.SiteCode,
			&i.SiteName,
			&i.SiteLocality,
			&i.CountryCode,
			&i.CountryName,
			&i.EventDate,
			&i.EventDatePrecision,
			&i.TaxonID,
			&i.TaxonName,
			&i.TaxonAuthorship,
			&i.TaxonRank,
			&i.TaxonGbifID,
			&i.TaxonStatus,
			&i.IdentificationConfer,
			&i.IdentificationAddendum,
			&i.IdentificationDate,
			&i.IdentificationDatePrecision,
			&i.IdentifiedBy,
			&i.TypeStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchOccurrencesSortByEventDateDESC = `-- name: FetchOccurrencesSortByEventDateDESC :many
SELECT o.id,
    s.id as sampling_id,
    s.latitude,
    s.longitude,
    s.coordinates_precision,
    s.altitude,
    s.site_code,
    s.site_name,
    s.site_locality,
    c.code as country_code,
    c.name as country_name,
    s.event_date,
    s.event_date_precision,
    t.id AS taxon_id,
    t.name AS taxon_name,
    t.authorship AS taxon_authorship,
    t.rank AS taxon_rank,
    t.GBIF_ID AS taxon_gbif_id,
    t.status AS taxon_status,
    o.identification_confer,
    o.identification_addendum,
    o.identification_date,
    o.identification_date_precision,
    o.identified_by,
    o.type_status
FROM occurrences o
INNER JOIN samplings s ON s.id = o.sampling_id
LEFT JOIN countries c ON c.code = s.site_country_code
INNER JOIN taxa t ON t.id = o.taxon_id
WHERE (
    $1::uuid[] IS NULL
    OR o.id = ANY($1)
)
ORDER BY s.event_date DESC, t.name ASC, c.name ASC, o.id ASC
LIMIT CASE
    WHEN $3::INTEGER IS NULL THEN NULL
    ELSE $3::INTEGER
END
OFFSET COALESCE($2::INTEGER, 0)
`

type FetchOccurrencesSortByEventDateDESCParams struct {
	OccurrenceIds []pgtype.UUID `json:"occurrence_ids"`
	PageOffset    pgtype.Int4   `json:"page_offset"`
	PageLimit     pgtype.Int4   `json:"page_limit"`
}

type FetchOccurrencesSortByEventDateDESCRow struct {
	ID                          string                   `json:"id"`
	SamplingID                  pgtype.UUID              `json:"sampling_id"`
	Latitude                    float32                  `json:"latitude"`
	Longitude                   float32                  `json:"longitude"`
	CoordinatesPrecision        pgtype.Int4              `json:"coordinates_precision"`
	Altitude                    pgtype.Int4              `json:"altitude"`
	SiteCode                    pgtype.Text              `json:"site_code"`
	SiteName                    pgtype.Text              `json:"site_name"`
	SiteLocality                pgtype.Text              `json:"site_locality"`
	CountryCode                 pgtype.Text              `json:"country_code"`
	CountryName                 pgtype.Text              `json:"country_name"`
	EventDate                   pgtype.Date              `json:"event_date"`
	EventDatePrecision          NullEventDatePrecision   `json:"event_date_precision"`
	TaxonID                     pgtype.UUID              `json:"taxon_id"`
	TaxonName                   string                   `json:"taxon_name"`
	TaxonAuthorship             pgtype.Text              `json:"taxon_authorship"`
	TaxonRank                   TaxonRank                `json:"taxon_rank"`
	TaxonGbifID                 pgtype.Int4              `json:"taxon_gbif_id"`
	TaxonStatus                 TaxonStatus              `json:"taxon_status"`
	IdentificationConfer        bool                     `json:"identification_confer"`
	IdentificationAddendum      pgtype.Text              `json:"identification_addendum"`
	IdentificationDate          pgtype.Date              `json:"identification_date"`
	IdentificationDatePrecision NullEventDatePrecision   `json:"identification_date_precision"`
	IdentifiedBy                []string                 `json:"identified_by"`
	TypeStatus                  NullOccurrenceTypeStatus `json:"type_status"`
}

func (q *Queries) FetchOccurrencesSortByEventDateDESC(ctx context.Context, arg FetchOccurrencesSortByEventDateDESCParams) ([]FetchOccurrencesSortByEventDateDESCRow, error) {
	rows, err := q.db.Query(ctx, fetchOccurrencesSortByEventDateDESC, arg.OccurrenceIds, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchOccurrencesSortByEventDateDESCRow
	for rows.Next() {
		var i FetchOccurrencesSortByEventDateDESCRow
		if err := rows.Scan(
			&i.ID,
			&i.SamplingID,
			&i.Latitude,
			&i.Longitude,
			&i.CoordinatesPrecision,
			&i.Altitude,
			&i.SiteCode,
			&i.SiteName,
			&i.SiteLocality,
			&i.CountryCode,
			&i.CountryName,
			&i.EventDate,
			&i.EventDatePrecision,
			&i.TaxonID,
			&i.TaxonName,
			&i.TaxonAuthorship,
			&i.TaxonRank,
			&i.TaxonGbifID,
			&i.TaxonStatus,
			&i.IdentificationConfer,
			&i.IdentificationAddendum,
			&i.IdentificationDate,
			&i.IdentificationDatePrecision,
			&i.IdentifiedBy,
			&i.TypeStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
