// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sampling_methods.sql

package biomedb

import (
	"context"

	"github.com/google/uuid"
)

const createSamplingMethod = `-- name: CreateSamplingMethod :one
INSERT INTO sampling_methods (
        code,
        name,
        description
    )
VALUES (
        $1,
        $2,
        $3
    )
RETURNING id, code, name, description
`

type CreateSamplingMethodParams struct {
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateSamplingMethod(ctx context.Context, arg CreateSamplingMethodParams) (SamplingMethod, error) {
	row := q.db.QueryRow(ctx, createSamplingMethod, arg.Code, arg.Name, arg.Description)
	var i SamplingMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const deleteSamplingMethod = `-- name: DeleteSamplingMethod :exec
DELETE FROM sampling_methods
WHERE code = $1
RETURNING id, code, name, description
`

func (q *Queries) DeleteSamplingMethod(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deleteSamplingMethod, code)
	return err
}

const getSamplingMethodByCode = `-- name: GetSamplingMethodByCode :one
SELECT id, code, name, description
FROM sampling_methods
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetSamplingMethodByCode(ctx context.Context, code string) (SamplingMethod, error) {
	row := q.db.QueryRow(ctx, getSamplingMethodByCode, code)
	var i SamplingMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const listSamplingMethods = `-- name: ListSamplingMethods :many
SELECT id, code, name, description
FROM sampling_methods
ORDER BY name,
    code
`

func (q *Queries) ListSamplingMethods(ctx context.Context) ([]SamplingMethod, error) {
	rows, err := q.db.Query(ctx, listSamplingMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SamplingMethod{}
	for rows.Next() {
		var i SamplingMethod
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnknownSamplingMethodCodes = `-- name: ListUnknownSamplingMethodCodes :many
SELECT c.code::TEXT
FROM unnest($1::text []) AS c(code)
    LEFT JOIN sampling_methods sm ON sm.code = c.code
WHERE sm.id IS NULL
`

func (q *Queries) ListUnknownSamplingMethodCodes(ctx context.Context, methodCodes []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUnknownSamplingMethodCodes, methodCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var c_code string
		if err := rows.Scan(&c_code); err != nil {
			return nil, err
		}
		items = append(items, c_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceMethodsAtSampling = `-- name: ReplaceMethodsAtSampling :exec
WITH deleted AS (
    DELETE FROM events_sampling_methods
    WHERE sampling_id = $1::uuid
)
INSERT INTO events_sampling_methods (sampling_id, method_id)
SELECT $1::uuid,
    sm.id
FROM sampling_methods sm
WHERE sm.code = ANY($2::text [])
`

func (q *Queries) ReplaceMethodsAtSampling(ctx context.Context, samplingID uuid.UUID, methodCodes []string) error {
	_, err := q.db.Exec(ctx, replaceMethodsAtSampling, samplingID, methodCodes)
	return err
}

const updateSamplingMethod = `-- name: UpdateSamplingMethod :one
UPDATE sampling_methods
SET code = COALESCE($1, code),
    name = COALESCE($2, name),
    description = CASE
        WHEN $3::bool THEN $4
        ELSE description
    END
WHERE code = $5
RETURNING id, code, name, description
`

type UpdateSamplingMethodParams struct {
	Code           *string `json:"code"`
	Name           *string `json:"name"`
	SetDescription bool    `json:"set_description"`
	Description    *string `json:"description"`
	OldCode        string  `json:"old_code"`
}

func (q *Queries) UpdateSamplingMethod(ctx context.Context, arg UpdateSamplingMethodParams) (SamplingMethod, error) {
	row := q.db.QueryRow(ctx, updateSamplingMethod,
		arg.Code,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.OldCode,
	)
	var i SamplingMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
	)
	return i, err
}
