// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package biomedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyUserEmailChangeRequest = `-- name: ApplyUserEmailChangeRequest :one
WITH request_row AS (
    SELECT r.id,
        r.user_id,
        r.email
    FROM user_email_change_requests r
    WHERE r.id = $1
        AND r.status IN ('pending', 'verified')
        AND r.expires_at > now()
    LIMIT 1
), updated_user AS (
    UPDATE users
    SET email = (
            SELECT email
            FROM request_row
        ),
        email_verified_at = now()
    WHERE id = (
            SELECT user_id
            FROM request_row
        )
    RETURNING id, login, email, password_hash, role, first_name, last_name, organisation, contact, comments, full_name, active, email_verified_at
),
updated_request AS (
    UPDATE user_email_change_requests
    SET status = 'applied',
        verified_at = COALESCE(verified_at, now()),
        applied_at = now()
    WHERE id = (
            SELECT id
            FROM request_row
        )
    RETURNING id
)
SELECT id, login, email, password_hash, role, first_name, last_name, organisation, contact, comments, full_name, active, email_verified_at
FROM updated_user
`

type ApplyUserEmailChangeRequestRow struct {
	ID              pgtype.UUID        `json:"id"`
	Login           string             `json:"login"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Role            UserRole           `json:"role"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Organisation    pgtype.Text        `json:"organisation"`
	Contact         pgtype.Text        `json:"contact"`
	Comments        pgtype.Text        `json:"comments"`
	FullName        pgtype.Text        `json:"full_name"`
	Active          bool               `json:"active"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

func (q *Queries) ApplyUserEmailChangeRequest(ctx context.Context, userEmailChangeRequestID pgtype.UUID) (ApplyUserEmailChangeRequestRow, error) {
	row := q.db.QueryRow(ctx, applyUserEmailChangeRequest, userEmailChangeRequestID)
	var i ApplyUserEmailChangeRequestRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Organisation,
		&i.Contact,
		&i.Comments,
		&i.FullName,
		&i.Active,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const authenticateUser = `-- name: AuthenticateUser :one
SELECT id, login, email, password_hash, role, first_name, last_name, organisation, contact, comments, full_name, active, email_verified_at
FROM users
WHERE active = true
    AND password_hash = $1
    AND (
        login = $2
        OR email = $2
    )
LIMIT 1
`

func (q *Queries) AuthenticateUser(ctx context.Context, passwordHash string, identifier string) (User, error) {
	row := q.db.QueryRow(ctx, authenticateUser, passwordHash, identifier)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Organisation,
		&i.Contact,
		&i.Comments,
		&i.FullName,
		&i.Active,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const cancelUserAccountRequest = `-- name: CancelUserAccountRequest :one
UPDATE user_account_requests
SET status = 'cancelled',
    cancelled_at = now()
WHERE id = $1
    AND status = 'pending'
RETURNING id, email, name, motivations, status, created_at, expires_at, verified_at, cancelled_at
`

func (q *Queries) CancelUserAccountRequest(ctx context.Context, userAccountRequestID pgtype.UUID) (UserAccountRequest, error) {
	row := q.db.QueryRow(ctx, cancelUserAccountRequest, userAccountRequestID)
	var i UserAccountRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Motivations,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CancelledAt,
	)
	return i, err
}

const consumeUserAccountRequestToken = `-- name: ConsumeUserAccountRequestToken :exec
UPDATE user_account_request_tokens
SET consumed = true,
    consumed_at = now()
WHERE token_hash = $1
    AND consumed = false
`

func (q *Queries) ConsumeUserAccountRequestToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, consumeUserAccountRequestToken, tokenHash)
	return err
}

const consumeUserEmailChangeRequestToken = `-- name: ConsumeUserEmailChangeRequestToken :exec
UPDATE user_email_change_request_tokens
SET consumed = true,
    consumed_at = now(),
    consumed_by = $1
WHERE token_hash = $2
    AND consumed = false
`

func (q *Queries) ConsumeUserEmailChangeRequestToken(ctx context.Context, consumedBy pgtype.UUID, tokenHash string) error {
	_, err := q.db.Exec(ctx, consumeUserEmailChangeRequestToken, consumedBy, tokenHash)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (
        email,
        invitee_name,
        organisation,
        role,
        message,
        inviter_id,
        expires_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    )
RETURNING id, email, invitee_name, organisation, role, message, inviter_id, status, created_at, expires_at, redeemed_at, revoked_at, revoked_by
`

type CreateInvitationParams struct {
	Email        string             `json:"email"`
	InviteeName  pgtype.Text        `json:"invitee_name"`
	Organisation pgtype.Text        `json:"organisation"`
	Role         UserRole           `json:"role"`
	Message      pgtype.Text        `json:"message"`
	InviterID    pgtype.UUID        `json:"inviter_id"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Email,
		arg.InviteeName,
		arg.Organisation,
		arg.Role,
		arg.Message,
		arg.InviterID,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviteeName,
		&i.Organisation,
		&i.Role,
		&i.Message,
		&i.InviterID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const createInvitationToken = `-- name: CreateInvitationToken :one
INSERT INTO invitation_tokens (invitation_id, token_hash)
VALUES (
        $1,
        $2
    )
RETURNING id, invitation_id, token_hash, created_at, consumed, consumed_by, consumed_at
`

func (q *Queries) CreateInvitationToken(ctx context.Context, invitationID pgtype.UUID, tokenHash string) (InvitationToken, error) {
	row := q.db.QueryRow(ctx, createInvitationToken, invitationID, tokenHash)
	var i InvitationToken
	err := row.Scan(
		&i.ID,
		&i.InvitationID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.Consumed,
		&i.ConsumedBy,
		&i.ConsumedAt,
	)
	return i, err
}

const createUserAccountRequest = `-- name: CreateUserAccountRequest :one
INSERT INTO user_account_requests (email, name, motivations, expires_at)
VALUES (
        $1,
        $2,
        $3,
        $4
    )
RETURNING id, email, name, motivations, status, created_at, expires_at, verified_at, cancelled_at
`

type CreateUserAccountRequestParams struct {
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	Motivations pgtype.Text        `json:"motivations"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUserAccountRequest(ctx context.Context, arg CreateUserAccountRequestParams) (UserAccountRequest, error) {
	row := q.db.QueryRow(ctx, createUserAccountRequest,
		arg.Email,
		arg.Name,
		arg.Motivations,
		arg.ExpiresAt,
	)
	var i UserAccountRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Motivations,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CancelledAt,
	)
	return i, err
}

const createUserAccountRequestToken = `-- name: CreateUserAccountRequestToken :one
INSERT INTO user_account_request_tokens (user_account_request_id, token_hash)
VALUES (
        $1,
        $2
    )
RETURNING id, user_account_request_id, token_hash, created_at, consumed, consumed_at
`

func (q *Queries) CreateUserAccountRequestToken(ctx context.Context, userAccountRequestID pgtype.UUID, tokenHash string) (UserAccountRequestToken, error) {
	row := q.db.QueryRow(ctx, createUserAccountRequestToken, userAccountRequestID, tokenHash)
	var i UserAccountRequestToken
	err := row.Scan(
		&i.ID,
		&i.UserAccountRequestID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.Consumed,
		&i.ConsumedAt,
	)
	return i, err
}

const createUserEmailChangeRequest = `-- name: CreateUserEmailChangeRequest :one
INSERT INTO user_email_change_requests (user_id, email, expires_at)
VALUES (
        $1,
        $2,
        $3
    )
RETURNING id, user_id, email, status, created_at, expires_at, verified_at, applied_at, cancelled_at
`

type CreateUserEmailChangeRequestParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUserEmailChangeRequest(ctx context.Context, arg CreateUserEmailChangeRequestParams) (UserEmailChangeRequest, error) {
	row := q.db.QueryRow(ctx, createUserEmailChangeRequest, arg.UserID, arg.Email, arg.ExpiresAt)
	var i UserEmailChangeRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.AppliedAt,
		&i.CancelledAt,
	)
	return i, err
}

const createUserEmailChangeRequestToken = `-- name: CreateUserEmailChangeRequestToken :one
INSERT INTO user_email_change_request_tokens (user_email_change_request_id, token_hash)
VALUES (
        $1,
        $2
    )
RETURNING id, user_email_change_request_id, token_hash, created_at, consumed, consumed_by, consumed_at
`

func (q *Queries) CreateUserEmailChangeRequestToken(ctx context.Context, userEmailChangeRequestID pgtype.UUID, tokenHash string) (UserEmailChangeRequestToken, error) {
	row := q.db.QueryRow(ctx, createUserEmailChangeRequestToken, userEmailChangeRequestID, tokenHash)
	var i UserEmailChangeRequestToken
	err := row.Scan(
		&i.ID,
		&i.UserEmailChangeRequestID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.Consumed,
		&i.ConsumedBy,
		&i.ConsumedAt,
	)
	return i, err
}

const createUserFromInvitationToken = `-- name: CreateUserFromInvitationToken :one
WITH invitation_row AS (
    SELECT i.id,
        i.email,
        i.role
    FROM invitations i
        JOIN invitation_tokens t ON t.invitation_id = i.id
    WHERE t.token_hash = $1
        AND t.consumed = false
        AND i.status = 'pending'
        AND i.expires_at > now()
    LIMIT 1
), inserted_user AS (
    INSERT INTO users (
            login,
            email,
            password_hash,
            role,
            first_name,
            last_name,
            organisation,
            contact,
            comments,
            email_verified_at
        )
    SELECT $2,
        invitation_row.email,
        $3,
        invitation_row.role,
        $4,
        $5,
        $6,
        $7,
        $8,
        now()
    FROM invitation_row
    RETURNING id, login, email, password_hash, role, first_name, last_name, organisation, contact, comments, full_name, active, email_verified_at
),
updated_invitation AS (
    UPDATE invitations
    SET status = 'redeemed',
        redeemed_at = now()
    WHERE id = (
            SELECT id
            FROM invitation_row
        )
    RETURNING id
),
updated_token AS (
    UPDATE invitation_tokens
    SET consumed = true,
        consumed_at = now(),
        consumed_by = (
            SELECT id
            FROM inserted_user
        )
    WHERE token_hash = $1
    RETURNING id
)
SELECT id, login, email, password_hash, role, first_name, last_name, organisation, contact, comments, full_name, active, email_verified_at
FROM inserted_user
`

type CreateUserFromInvitationTokenParams struct {
	TokenHash    string      `json:"token_hash"`
	Login        string      `json:"login"`
	PasswordHash string      `json:"password_hash"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	Organisation pgtype.Text `json:"organisation"`
	Contact      pgtype.Text `json:"contact"`
	Comments     pgtype.Text `json:"comments"`
}

type CreateUserFromInvitationTokenRow struct {
	ID              pgtype.UUID        `json:"id"`
	Login           string             `json:"login"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Role            UserRole           `json:"role"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Organisation    pgtype.Text        `json:"organisation"`
	Contact         pgtype.Text        `json:"contact"`
	Comments        pgtype.Text        `json:"comments"`
	FullName        pgtype.Text        `json:"full_name"`
	Active          bool               `json:"active"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

func (q *Queries) CreateUserFromInvitationToken(ctx context.Context, arg CreateUserFromInvitationTokenParams) (CreateUserFromInvitationTokenRow, error) {
	row := q.db.QueryRow(ctx, createUserFromInvitationToken,
		arg.TokenHash,
		arg.Login,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Organisation,
		arg.Contact,
		arg.Comments,
	)
	var i CreateUserFromInvitationTokenRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Organisation,
		&i.Contact,
		&i.Comments,
		&i.FullName,
		&i.Active,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT i.id, i.email, i.invitee_name, i.organisation, i.role, i.message, i.inviter_id, i.status, i.created_at, i.expires_at, i.redeemed_at, i.revoked_at, i.revoked_by
FROM invitations i
    JOIN invitation_tokens t ON t.invitation_id = i.id
WHERE t.token_hash = $1
    AND t.consumed = false
    AND i.status = 'pending'
    AND i.expires_at > now()
LIMIT 1
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviteeName,
		&i.Organisation,
		&i.Role,
		&i.Message,
		&i.InviterID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const getUserAccountRequestByTokenHash = `-- name: GetUserAccountRequestByTokenHash :one
SELECT r.id, r.email, r.name, r.motivations, r.status, r.created_at, r.expires_at, r.verified_at, r.cancelled_at
FROM user_account_requests r
    JOIN user_account_request_tokens t ON t.user_account_request_id = r.id
WHERE t.token_hash = $1
    AND t.consumed = false
    AND r.status = 'pending'
    AND r.expires_at > now()
LIMIT 1
`

func (q *Queries) GetUserAccountRequestByTokenHash(ctx context.Context, tokenHash string) (UserAccountRequest, error) {
	row := q.db.QueryRow(ctx, getUserAccountRequestByTokenHash, tokenHash)
	var i UserAccountRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Motivations,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getUserEmailChangeRequestByTokenHash = `-- name: GetUserEmailChangeRequestByTokenHash :one
SELECT r.id, r.user_id, r.email, r.status, r.created_at, r.expires_at, r.verified_at, r.applied_at, r.cancelled_at
FROM user_email_change_requests r
    JOIN user_email_change_request_tokens t ON t.user_email_change_request_id = r.id
WHERE t.token_hash = $1
    AND t.consumed = false
    AND r.status = 'pending'
    AND r.expires_at > now()
LIMIT 1
`

func (q *Queries) GetUserEmailChangeRequestByTokenHash(ctx context.Context, tokenHash string) (UserEmailChangeRequest, error) {
	row := q.db.QueryRow(ctx, getUserEmailChangeRequestByTokenHash, tokenHash)
	var i UserEmailChangeRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.AppliedAt,
		&i.CancelledAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1
WHERE id = $2
`

func (q *Queries) UpdateUserPassword(ctx context.Context, passwordHash string, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserPassword, passwordHash, userID)
	return err
}

const updateUserPersonalInfo = `-- name: UpdateUserPersonalInfo :one
UPDATE users
SET first_name = CASE
        WHEN $1::boolean THEN $2
        ELSE first_name
    END,
    last_name = CASE
        WHEN $3::boolean THEN $4
        ELSE last_name
    END,
    contact = CASE
        WHEN $5::boolean THEN $6
        ELSE contact
    END,
    organisation = CASE
        WHEN $7::boolean THEN $8
        ELSE organisation
    END
WHERE id = $9
RETURNING id, login, email, password_hash, role, first_name, last_name, organisation, contact, comments, full_name, active, email_verified_at
`

type UpdateUserPersonalInfoParams struct {
	FirstNameSet    bool        `json:"first_name_set"`
	FirstName       pgtype.Text `json:"first_name"`
	LastNameSet     bool        `json:"last_name_set"`
	LastName        pgtype.Text `json:"last_name"`
	ContactSet      bool        `json:"contact_set"`
	Contact         pgtype.Text `json:"contact"`
	OrganisationSet bool        `json:"organisation_set"`
	Organisation    pgtype.Text `json:"organisation"`
	UserID          pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateUserPersonalInfo(ctx context.Context, arg UpdateUserPersonalInfoParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPersonalInfo,
		arg.FirstNameSet,
		arg.FirstName,
		arg.LastNameSet,
		arg.LastName,
		arg.ContactSet,
		arg.Contact,
		arg.OrganisationSet,
		arg.Organisation,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Organisation,
		&i.Contact,
		&i.Comments,
		&i.FullName,
		&i.Active,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET role = $1
WHERE id = $2
`

func (q *Queries) UpdateUserRole(ctx context.Context, role UserRole, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserRole, role, userID)
	return err
}

const verifyUserAccountRequest = `-- name: VerifyUserAccountRequest :one
UPDATE user_account_requests
SET status = 'verified',
    verified_at = now()
WHERE id = $1
    AND status = 'pending'
RETURNING id, email, name, motivations, status, created_at, expires_at, verified_at, cancelled_at
`

func (q *Queries) VerifyUserAccountRequest(ctx context.Context, userAccountRequestID pgtype.UUID) (UserAccountRequest, error) {
	row := q.db.QueryRow(ctx, verifyUserAccountRequest, userAccountRequestID)
	var i UserAccountRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Motivations,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CancelledAt,
	)
	return i, err
}

const verifyUserEmailChangeRequest = `-- name: VerifyUserEmailChangeRequest :one
UPDATE user_email_change_requests
SET status = 'verified',
    verified_at = now()
WHERE id = $1
    AND status = 'pending'
RETURNING id, user_id, email, status, created_at, expires_at, verified_at, applied_at, cancelled_at
`

func (q *Queries) VerifyUserEmailChangeRequest(ctx context.Context, userEmailChangeRequestID pgtype.UUID) (UserEmailChangeRequest, error) {
	row := q.db.QueryRow(ctx, verifyUserEmailChangeRequest, userEmailChangeRequestID)
	var i UserEmailChangeRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.AppliedAt,
		&i.CancelledAt,
	)
	return i, err
}
