// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_invitations.sql

package biomedb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelInvitation = `-- name: CancelInvitation :one
UPDATE invitations
SET status = 'cancelled', revoked_at = now(), revoked_by = $1
WHERE id = $2 AND status = 'pending' AND expires_at > now()
RETURNING id, email, invitee_name, role, message, inviter_id, status, created_at, expires_at, redeemed_at, revoked_at, revoked_by
`

func (q *Queries) CancelInvitation(ctx context.Context, revokedBy pgtype.UUID, invitationID uuid.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, cancelInvitation, revokedBy, invitationID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviteeName,
		&i.Role,
		&i.Message,
		&i.InviterID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (
        email,
        invitee_name,
        role,
        message,
        inviter_id,
        expires_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    )
RETURNING id, email, invitee_name, role, message, inviter_id, status, created_at, expires_at, redeemed_at, revoked_at, revoked_by
`

type CreateInvitationParams struct {
	Email       string      `json:"email"`
	InviteeName string      `json:"invitee_name"`
	Role        UserRole    `json:"role"`
	Message     *string     `json:"message"`
	InviterID   pgtype.UUID `json:"inviter_id"`
	ExpiresAt   time.Time   `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Email,
		arg.InviteeName,
		arg.Role,
		arg.Message,
		arg.InviterID,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviteeName,
		&i.Role,
		&i.Message,
		&i.InviterID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const createInvitationToken = `-- name: CreateInvitationToken :one
INSERT INTO invitation_tokens (invitation_id, token_hash)
VALUES (
        $1,
        $2
    )
RETURNING id, invitation_id, token_hash, created_at, consumed, consumed_by, consumed_at
`

func (q *Queries) CreateInvitationToken(ctx context.Context, invitationID uuid.UUID, tokenHash string) (InvitationToken, error) {
	row := q.db.QueryRow(ctx, createInvitationToken, invitationID, tokenHash)
	var i InvitationToken
	err := row.Scan(
		&i.ID,
		&i.InvitationID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.Consumed,
		&i.ConsumedBy,
		&i.ConsumedAt,
	)
	return i, err
}

const createUserFromInvitationToken = `-- name: CreateUserFromInvitationToken :one
WITH invitation_row AS (
    SELECT i.id,
        i.email,
        i.role
    FROM invitations i
        JOIN invitation_tokens t ON t.invitation_id = i.id
    WHERE t.token_hash = $1
        AND t.consumed = false
        AND i.status = 'pending'
        AND i.expires_at > now()
    -- Lock the invitation too: different tokens must not redeem it concurrently.
    FOR UPDATE OF i, t
),
inserted_user AS (
    INSERT INTO users (
            login,
            email,
            password_hash,
            role,
            first_name,
            last_name,
            organisation,
            contact,
            bio,
            email_verified_at
        )
    SELECT $2,
        invitation_row.email,
        $3,
        invitation_row.role,
        $4,
        $5,
        $6,
        $7,
        $8,
        now()
    FROM invitation_row
    RETURNING id, login, email, password_hash, role, first_name, last_name, organisation, contact, bio, full_name, active, email_verified_at
),
updated_invitation AS (
    UPDATE invitations i
    SET status = 'redeemed',
        redeemed_at = now()
    FROM inserted_user iu
    WHERE i.id = (
            SELECT id
            FROM invitation_row
        )
    RETURNING i.id
),
updated_token AS (
    UPDATE invitation_tokens t
    SET consumed = true,
        consumed_at = now(),
        consumed_by = iu.id
    FROM inserted_user iu
    WHERE t.token_hash = $1
        AND t.consumed = false
    RETURNING t.id
)
SELECT id, login, email, password_hash, role, first_name, last_name, organisation, contact, bio, full_name, active, email_verified_at FROM inserted_user
`

type CreateUserFromInvitationTokenParams struct {
	TokenHash    string  `json:"token_hash"`
	Login        string  `json:"login"`
	PasswordHash string  `json:"password_hash"`
	FirstName    string  `json:"first_name"`
	LastName     string  `json:"last_name"`
	Organisation *string `json:"organisation"`
	Contact      *string `json:"contact"`
	Bio          *string `json:"bio"`
}

type CreateUserFromInvitationTokenRow struct {
	ID              uuid.UUID          `json:"id"`
	Login           string             `json:"login"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Role            UserRole           `json:"role"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Organisation    *string            `json:"organisation"`
	Contact         *string            `json:"contact"`
	Bio             *string            `json:"bio"`
	FullName        string             `json:"full_name"`
	Active          bool               `json:"active"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

// The table scan uses the pre-insert snapshot; return the INSERT output itself.
func (q *Queries) CreateUserFromInvitationToken(ctx context.Context, arg CreateUserFromInvitationTokenParams) (CreateUserFromInvitationTokenRow, error) {
	row := q.db.QueryRow(ctx, createUserFromInvitationToken,
		arg.TokenHash,
		arg.Login,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Organisation,
		arg.Contact,
		arg.Bio,
	)
	var i CreateUserFromInvitationTokenRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FirstName,
		&i.LastName,
		&i.Organisation,
		&i.Contact,
		&i.Bio,
		&i.FullName,
		&i.Active,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const expireInvitationsForEmail = `-- name: ExpireInvitationsForEmail :exec
UPDATE invitations
SET status = 'expired'
WHERE email = $1 AND status = 'pending' AND expires_at <= now()
`

func (q *Queries) ExpireInvitationsForEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, expireInvitationsForEmail, email)
	return err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT i.id, i.email, i.invitee_name, i.role, i.message, i.inviter_id, i.status, i.created_at, i.expires_at, i.redeemed_at, i.revoked_at, i.revoked_by
FROM invitations i
    JOIN invitation_tokens t ON t.invitation_id = i.id
WHERE t.token_hash = $1
    AND t.consumed = false
    AND i.status = 'pending'
    AND i.expires_at > now()
LIMIT 1
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InviteeName,
		&i.Role,
		&i.Message,
		&i.InviterID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
