//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var ImportBatchStatus = &struct {
	Created   postgres.StringExpression
	Staged    postgres.StringExpression
	Completed postgres.StringExpression
	Failed    postgres.StringExpression
	Canceled  postgres.StringExpression
}{
	Created:   postgres.NewEnumValue("created"),
	Staged:    postgres.NewEnumValue("staged"),
	Completed: postgres.NewEnumValue("completed"),
	Failed:    postgres.NewEnumValue("failed"),
	Canceled:  postgres.NewEnumValue("canceled"),
}
