//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var InvitationStatus = &struct {
	Pending   postgres.StringExpression
	Redeemed  postgres.StringExpression
	Cancelled postgres.StringExpression
	Expired   postgres.StringExpression
}{
	Pending:   postgres.NewEnumValue("pending"),
	Redeemed:  postgres.NewEnumValue("redeemed"),
	Cancelled: postgres.NewEnumValue("cancelled"),
	Expired:   postgres.NewEnumValue("expired"),
}
