//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var ResolutionStatus = &struct {
	Pending       postgres.StringExpression
	AutoResolved  postgres.StringExpression
	UserResolved  postgres.StringExpression
	NeedsDecision postgres.StringExpression
}{
	Pending:       postgres.NewEnumValue("pending"),
	AutoResolved:  postgres.NewEnumValue("auto_resolved"),
	UserResolved:  postgres.NewEnumValue("user_resolved"),
	NeedsDecision: postgres.NewEnumValue("needs_decision"),
}
