//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var TaxonMatchType = &struct {
	Exact    postgres.StringExpression
	Fuzzy    postgres.StringExpression
	NameOnly postgres.StringExpression
}{
	Exact:    postgres.NewEnumValue("exact"),
	Fuzzy:    postgres.NewEnumValue("fuzzy"),
	NameOnly: postgres.NewEnumValue("name_only"),
}
