//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type GbifImportStatus string

const (
	GbifImportStatus_Pending    GbifImportStatus = "pending"
	GbifImportStatus_InProgress GbifImportStatus = "in_progress"
	GbifImportStatus_Completed  GbifImportStatus = "completed"
	GbifImportStatus_Failed     GbifImportStatus = "failed"
)

var GbifImportStatusAllValues = []GbifImportStatus{
	GbifImportStatus_Pending,
	GbifImportStatus_InProgress,
	GbifImportStatus_Completed,
	GbifImportStatus_Failed,
}

func (e *GbifImportStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "pending":
		*e = GbifImportStatus_Pending
	case "in_progress":
		*e = GbifImportStatus_InProgress
	case "completed":
		*e = GbifImportStatus_Completed
	case "failed":
		*e = GbifImportStatus_Failed
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for GbifImportStatus enum")
	}

	return nil
}

func (e GbifImportStatus) String() string {
	return string(e)
}
