//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/lib/pq"
)

type GbifStaging struct {
	Key              int32 `sql:"primary_key"`
	Parent           *string
	ParentKey        *int32
	CanonicalName    string
	ScientificName   string
	Status           string
	Rank             string
	NameType         string
	KingdomKey       *int32
	PhylumKey        *int32
	ClassKey         *int32
	OrderKey         *int32
	FamilyKey        *int32
	GenusKey         *int32
	SpeciesKey       *int32
	HigherTaxonKeys  *pq.Int32Array
	HigherTaxonNames *pq.StringArray
	Authorship       *string
	NumDescendants   *int32
	AcceptedKey      *int32
	AcceptedName     *string
}
