//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"github.com/lib/pq"
	"time"
)

type ImportBatches struct {
	ID                      uuid.UUID `sql:"primary_key"`
	Label                   string
	Description             *string
	Status                  ImportBatchStatus
	AssembledBy             *pq.StringArray
	CreatedBy               uuid.UUID
	CreatedAt               time.Time
	CompletedAt             *time.Time
	CompletedBy             *uuid.UUID
	TaxonomicScope          int32
	ImportedFileName        string
	ImportedFileSize        int64
	ImportedFileHash        string
	ImportedFileContentType string
}
