//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type InvitationStatus string

const (
	InvitationStatus_Pending   InvitationStatus = "pending"
	InvitationStatus_Redeemed  InvitationStatus = "redeemed"
	InvitationStatus_Cancelled InvitationStatus = "cancelled"
	InvitationStatus_Expired   InvitationStatus = "expired"
)

var InvitationStatusAllValues = []InvitationStatus{
	InvitationStatus_Pending,
	InvitationStatus_Redeemed,
	InvitationStatus_Cancelled,
	InvitationStatus_Expired,
}

func (e *InvitationStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "pending":
		*e = InvitationStatus_Pending
	case "redeemed":
		*e = InvitationStatus_Redeemed
	case "cancelled":
		*e = InvitationStatus_Cancelled
	case "expired":
		*e = InvitationStatus_Expired
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for InvitationStatus enum")
	}

	return nil
}

func (e InvitationStatus) String() string {
	return string(e)
}
