//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type PublicationCandidateSource string

const (
	PublicationCandidateSource_Internal PublicationCandidateSource = "internal"
	PublicationCandidateSource_Crossref PublicationCandidateSource = "crossref"
	PublicationCandidateSource_Manual   PublicationCandidateSource = "manual"
)

var PublicationCandidateSourceAllValues = []PublicationCandidateSource{
	PublicationCandidateSource_Internal,
	PublicationCandidateSource_Crossref,
	PublicationCandidateSource_Manual,
}

func (e *PublicationCandidateSource) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "internal":
		*e = PublicationCandidateSource_Internal
	case "crossref":
		*e = PublicationCandidateSource_Crossref
	case "manual":
		*e = PublicationCandidateSource_Manual
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for PublicationCandidateSource enum")
	}

	return nil
}

func (e PublicationCandidateSource) String() string {
	return string(e)
}
