//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type ResolutionStatus string

const (
	ResolutionStatus_Pending       ResolutionStatus = "pending"
	ResolutionStatus_AutoResolved  ResolutionStatus = "auto_resolved"
	ResolutionStatus_UserResolved  ResolutionStatus = "user_resolved"
	ResolutionStatus_NeedsDecision ResolutionStatus = "needs_decision"
)

var ResolutionStatusAllValues = []ResolutionStatus{
	ResolutionStatus_Pending,
	ResolutionStatus_AutoResolved,
	ResolutionStatus_UserResolved,
	ResolutionStatus_NeedsDecision,
}

func (e *ResolutionStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "pending":
		*e = ResolutionStatus_Pending
	case "auto_resolved":
		*e = ResolutionStatus_AutoResolved
	case "user_resolved":
		*e = ResolutionStatus_UserResolved
	case "needs_decision":
		*e = ResolutionStatus_NeedsDecision
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for ResolutionStatus enum")
	}

	return nil
}

func (e ResolutionStatus) String() string {
	return string(e)
}
