//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Settings struct {
	ID                     int32 `sql:"primary_key"`
	AppName                string
	AppSubtitle            *string
	AppDescription         *string
	IsPublic               bool
	AccountRequestsEnabled bool
	AdminEmail             string
	SMTPSettingsValid      bool
	SMTPHost               *string
	SMTPPort               *int32
	SMTPUser               *string
	SMTPPassword           *string
	SMTPFromEmail          *string
	SMTPFromName           *string
	GeoapifyAPIKey         *string
	GeoapifyUsageLimit     int32
	GbifContactEmail       string
}
