//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type TaxonResolution struct {
	ID                  uuid.UUID `sql:"primary_key"`
	ImportID            uuid.UUID
	InputName           string
	InputAuthorship     *string
	InputRank           *string
	ScientificName      string
	Status              *ResolutionStatus
	GbifStatus          *TaxonGbifStatus
	FromResolutionID    *uuid.UUID
	SamplingTarget      bool
	ResolvedCandidateID *uuid.UUID
}
