//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserAccountRequestTokens struct {
	ID                   uuid.UUID `sql:"primary_key"`
	UserAccountRequestID uuid.UUID
	TokenHash            string
	CreatedAt            time.Time
	Consumed             bool
	ConsumedAt           *time.Time
}
