//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Users struct {
	ID              uuid.UUID `sql:"primary_key"`
	Login           string
	Email           string
	PasswordHash    string
	Role            UserRole
	FirstName       string
	LastName        string
	Organisation    *string
	Contact         *string
	Bio             *string
	FullName        string
	Active          bool
	EmailVerifiedAt *time.Time
}
