//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type UserAccountRequestStatus string

const (
	UserAccountRequestStatus_Pending   UserAccountRequestStatus = "pending"
	UserAccountRequestStatus_Verified  UserAccountRequestStatus = "verified"
	UserAccountRequestStatus_Cancelled UserAccountRequestStatus = "cancelled"
	UserAccountRequestStatus_Expired   UserAccountRequestStatus = "expired"
)

var UserAccountRequestStatusAllValues = []UserAccountRequestStatus{
	UserAccountRequestStatus_Pending,
	UserAccountRequestStatus_Verified,
	UserAccountRequestStatus_Cancelled,
	UserAccountRequestStatus_Expired,
}

func (e *UserAccountRequestStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "pending":
		*e = UserAccountRequestStatus_Pending
	case "verified":
		*e = UserAccountRequestStatus_Verified
	case "cancelled":
		*e = UserAccountRequestStatus_Cancelled
	case "expired":
		*e = UserAccountRequestStatus_Expired
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for UserAccountRequestStatus enum")
	}

	return nil
}

func (e UserAccountRequestStatus) String() string {
	return string(e)
}
