root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
delay = 1000
exclude_file = ["docs/docs.go"]
exclude_regex = ["_test\\.go", "_gen\\.go", "templates/.*_templ\\.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "templ", "html", "edgeql"]
include_file = ["./config.yml"]
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
# run code generation
pre_cmd = ["go generate", "templ generate", "cd ../client && pnpm gen-client"]
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_error = true

[color]
app = "red"
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
