<template>
  <v-container fluid class="d-flex flex-column ga-8">
    <v-card title="Identification" class="small-card-title border-md" variant="outlined">
      <v-divider></v-divider>
      <v-card-text>
        <IdentificationFormFields v-model="model.identification" :mode :errors />
      </v-card-text>
    </v-card>
    <v-card
      title="Content"
      subtitle="Quantity and composition of specimens in the sample"
      variant="outlined"
      class="small-card-title border-md"
      flat
    >
      <template #append>
        <v-switch v-model="hasContent" color="primary" hide-details density="compact"></v-switch>
      </template>
      <template #default v-if="hasContent">
        <v-divider></v-divider>
        <v-card-text>
          <v-row>
            <v-col>
              <QuantityPicker
                v-model="model.quantity"
                label="Specimen quantity"
                v-bind="schema('quantity')"
              />
            </v-col>
          </v-row>
          <v-row>
            <v-col>
              <v-text-field
                v-model="model.content_description"
                label="Content description"
                placeholder="e.g. 3 males, 5 females"
                v-bind="schema('content_description')"
              />
            </v-col>
          </v-row>
        </v-card-text>
      </template>
    </v-card>
    <v-card
      title="References"
      subtitle="Literature that relates to the occurrence"
      class="small-card-title border-md"
      variant="outlined"
      flat
    >
      <template #append>
        <v-switch
          v-model="hasReferences"
          @update:model-value="(v) => (model.published_in = v ? model.published_in : undefined)"
          color="primary"
          hide-details
          density="compact"
        ></v-switch>
      </template>
      <template #default v-if="hasReferences">
        <v-divider></v-divider>
        <v-card-text>
          <ArticlesPicker
            v-model="model.published_in"
            label="Published in"
            multiple
            clearable
            v-bind="schema('published_in')"
          />
        </v-card-text>
      </template>
    </v-card>
    <v-card
      title="Collections"
      subtitle="Where preserved material related to the occurrence can be found"
      class="small-card-title border-md"
      variant="outlined"
    >
      <template #append>
        <v-btn
          text="Add"
          variant="tonal"
          rounded="md"
          prepend-icon="mdi-plus"
          size="small"
          @click="addCollection()"
        ></v-btn>
      </template>
      <div class="d-flex ga-3 flex-column">
        <template v-for="(_, i) in model.collections">
          <v-divider></v-divider>
          <v-card flat>
            <v-card-text>
              <div class="d-flex align-center">
                <CollectionField
                  class="flex-grow-1"
                  v-model="model.collections![i]"
                ></CollectionField>
                <v-btn
                  icon="mdi-close"
                  size="small"
                  color="error"
                  rounded="100"
                  variant="text"
                  @click="model.collections!.splice(i, 1)"
                />
              </div>
            </v-card-text>
          </v-card>
        </template>
      </div>
    </v-card>
    <v-card
      title="Use custom code"
      subtitle="Occurrence code is automatically generated by default"
      class="small-card-title border-md"
      variant="outlined"
    >
      <template #append>
        <v-switch
          v-model="useCustomCode"
          @update:model-value="(v) => (model.code = v ? model.code : undefined)"
          color="primary"
          hide-details
          density="compact"
        ></v-switch>
      </template>
      <template #default v-if="useCustomCode">
        <v-divider></v-divider>
        <v-card-text>
          <v-row>
            <v-col>
              <v-text-field
                label="Code"
                persistent-placeholder
                v-model.trim="model.code"
                v-bind="schema('code')"
              >
              </v-text-field>
            </v-col>
          </v-row>
        </v-card-text>
      </template>
    </v-card>
    <v-divider></v-divider>
    <v-row>
      <v-col>
        <v-textarea
          label="Comments"
          v-model.trim="model.comments"
          v-bind="schema('comments')"
          hint="Additional information about the occurrence, e.g. preservation state, associated organisms, etc."
        ></v-textarea>
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup lang="ts">
import { $OccurrenceInput, $OccurrenceUpdate } from '@/api'
import { useSchema } from '@/composables/schema'
import { FormProps } from '@/lib/mutations'
import { BiomatModel } from '@/models'
import { reactiveComputed } from '@vueuse/core'
import ArticlesPicker from '@/features/registries/components/ArticlesPicker.vue'
import QuantityPicker from '@/components/forms/occurrence/QuantityPicker.vue'
import IdentificationFormFields from '@/components/forms/occurrence/IdentificationFormFields.vue'
import CollectionField from './CollectionField.vue'
import { ref } from 'vue'

const model = defineModel<BiomatModel.BiomatModel>({
  default: BiomatModel.initialModel
})

const { mode = 'Create' } = defineProps<FormProps>()

const {
  bind: { schema }
} = reactiveComputed(() => useSchema(mode === 'Create' ? $OccurrenceInput : $OccurrenceUpdate))

function addCollection() {
  if (!model.value.collections) {
    model.value.collections = []
  }
  model.value.collections.push({ name: '' })
}

const useCustomCode = ref(false)
const hasContent = ref(false)
const hasReferences = ref(false)
</script>

<style scoped lang="scss"></style>
