<template>
  <v-container fluid class="d-flex flex-column ga-8">
    <v-card title="Identification" class="small-card-title border-md" variant="outlined">
      <v-divider></v-divider>
      <v-card-text>
        <IdentificationFormFields v-model="model.identification" :mode :errors />
      </v-card-text>
    </v-card>
    <TogglableFormCard
      title="Content"
      subtitle="Quantity and composition of specimens in the sample"
      v-model="hasContent"
      @update:model-value="(v) => (model.quantity = v ? model.quantity : undefined)"
    >
      <v-card-text>
        <v-row>
          <v-col>
            <QuantityPicker
              v-model="model.quantity"
              label="Specimen quantity"
              v-bind="schema('quantity')"
            />
          </v-col>
        </v-row>
        <v-row>
          <v-col>
            <v-text-field
              v-model="model.content_description"
              label="Content description"
              placeholder="e.g. 3 males, 5 females"
              v-bind="schema('content_description')"
            />
          </v-col>
        </v-row>
      </v-card-text>
    </TogglableFormCard>

    <TogglableFormCard
      title="References"
      subtitle="Literature that relates to the occurrence"
      v-model="hasReferences"
      @update:model-value="(v) => (model.published_in = v ? model.published_in : undefined)"
    >
      <v-card-text>
        <ArticlesPicker
          v-model="model.published_in"
          label="Published in"
          item-value="id"
          multiple
          clearable
          v-bind="schema('published_in')"
        />
      </v-card-text>
    </TogglableFormCard>

    <TogglableFormCard
      title="Collections"
      subtitle="Where preserved material related to the occurrence can be found"
      :model-value="!!model.collections?.length"
    >
      <template #append>
        <v-btn
          text="Add"
          variant="tonal"
          rounded="md"
          prepend-icon="mdi-plus"
          size="small"
          @click="addCollection()"
        ></v-btn>
      </template>
      <div class="d-flex ga-3 flex-column">
        <template v-for="(_, i) in model.collections">
          <v-divider></v-divider>
          <v-card flat>
            <v-card-text>
              <div class="d-flex align-center">
                <CollectionField class="flex-grow-1" v-model="model.collections![i]" />
                <v-btn
                  icon="mdi-close"
                  size="small"
                  color="error"
                  rounded="100"
                  variant="text"
                  @click="model.collections!.splice(i, 1)"
                />
              </div>
            </v-card-text>
          </v-card>
        </template>
      </div>
    </TogglableFormCard>
    <!-- <v-card
      title="Collections"
      subtitle="Where preserved material related to the occurrence can be found"
      class="small-card-title border-md"
      variant="outlined"
    >
      <template #append>
        <v-btn
          text="Add"
          variant="tonal"
          rounded="md"
          prepend-icon="mdi-plus"
          size="small"
          @click="addCollection()"
        ></v-btn>
      </template>
      <div class="d-flex ga-3 flex-column">
        <template v-for="(_, i) in model.collections">
          <v-divider></v-divider>
          <v-card flat>
            <v-card-text>
              <div class="d-flex align-center">
                <CollectionField
                  class="flex-grow-1"
                  v-model="model.collections![i]"
                ></CollectionField>
                <v-btn
                  icon="mdi-close"
                  size="small"
                  color="error"
                  rounded="100"
                  variant="text"
                  @click="model.collections!.splice(i, 1)"
                />
              </div>
            </v-card-text>
          </v-card>
        </template>
      </div>
    </v-card> -->
    <!-- <v-card
      title="Use custom code"
      subtitle="Occurrence code is automatically generated by default"
      class="small-card-title border-md"
      variant="outlined"
    >
      <template #append>
        <v-switch
          v-model="useCustomCode"
          @update:model-value="(v) => (model.code = v ? model.code : undefined)"
          color="primary"
          hide-details
          density="compact"
        ></v-switch>
      </template>
      <template #default v-if="useCustomCode">
        <v-divider></v-divider>
        <v-card-text>
          <v-row>
            <v-col>
              <v-text-field
                label="Code"
                persistent-placeholder
                v-model.trim="model.code"
                v-bind="schema('code')"
              >
              </v-text-field>
            </v-col>
          </v-row>
        </v-card-text>
      </template>
    </v-card> -->
    <TogglableFormCard
      title="Datasets"
      subtitle="Optionally add the new occurrence to one or more datasets"
      v-model="withDatasets"
      @update:model-value="(v) => (model.datasets = v ? model.datasets : [])"
    >
      <v-card-text>
        <DatasetPicker label="" multiple clearable>
          <template #append>
            <v-btn text="New" prepend-icon="mdi-plus" variant="tonal" rounded="md"></v-btn>
          </template>
        </DatasetPicker>
      </v-card-text>
    </TogglableFormCard>

    <v-divider></v-divider>
    <v-row>
      <v-col>
        <v-textarea
          label="Comments"
          v-model.trim="model.comments"
          v-bind="schema('comments')"
          hint="Additional information about the occurrence, e.g. preservation state, associated organisms, etc."
        ></v-textarea>
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup lang="ts">
import { $OccurrenceInput, OccurrenceInput, SamplingInput } from '@/api'
import IdentificationFormFields from '@/components/forms/occurrence/IdentificationFormFields.vue'
import QuantityPicker from '@/components/forms/occurrence/QuantityPicker.vue'
import { useSchema } from '@/composables/schema'
import DatasetPicker from '@/features/datasets/components/DatasetPicker.vue'
import ArticlesPicker from '@/features/registries/components/ArticlesPicker.vue'
import { FormProps } from '@/lib/mutations'
import { BiomatModel, OccurrenceModel } from '@/models'
import { reactiveComputed } from '@vueuse/core'
import { ref } from 'vue'
import CollectionField from './CollectionField.vue'
import TogglableFormCard from './TogglableFormCard.vue'

type OccurrenceModel = OccurrenceInput & {
  sampling_id?: UUID
  sampling?: SamplingInput
}

const model = defineModel<OccurrenceModel>({
  default: BiomatModel.initialModel
})

const { mode = 'Create' } = defineProps<FormProps>()

const {
  bind: { schema }
} = reactiveComputed(() => useSchema($OccurrenceInput))

function addCollection() {
  if (!model.value.collections) {
    model.value.collections = []
  }
  model.value.collections.push({ name: '' })
}

const useCustomCode = ref(false)
const hasContent = ref(false)
const hasReferences = ref(false)
const withDatasets = ref(false)
</script>

<style scoped lang="scss"></style>
