version: "3"

vars:
  TEST_DB_NAME: testing
  EMPTY_DB_NAME: schema

tasks:
  install:
    desc: "Install Gel CLI"
    cmds: [curl --proto '=https' --tlsv1.2 -sSf https://www.geldata.com/sh | sh]
    status: [command -v gel >/dev/null 2>&1]

  init-schema:
    desc: Create empty schema database branch (used when resetting DB)
    dir: ..
    cmd: gel branch create {{.EMPTY_DB_NAME}}
    status:
      - gel branch list | grep "{{.EMPTY_DB_NAME}}"
    run: once

  init-testing:
    desc: "Create testing database branch"
    dir: ..
    cmd: gel branch create {{.TEST_DB_NAME}} --copy-data
    status:
      - gel branch list | grep "{{.TEST_DB_NAME}}"

  init:
    desc: "Create database instance"
    dir: ..
    interactive: true
    cmds:
      - gel project init
      - gel extension install postgis
      - gel project info
    status: [gel project info]
    deps: [install]
    run: once

  config-email:
    desc: "Run email settings configuration utility"
    interactive: true
    dir: seeds
    cmds:
      - go run ./cmd/email

  dl-countries-dataset:
    desc: "Download countries dataset"
    dir: ..
    cmds:
      - curl -L -o ./data/remote/countries.json https://github.com/lsdch/countries-boundaries/releases/latest/download/countries.json
    generates:
      - ./data/remote/countries.json

  seed:
    desc: "Initialize local database instance with initial content"
    interactive: true
    dir: seeds
    cmds:
      - cmd: echo "Seeding database..."
        silent: true
      - go run ./cmd/seed/
      - gel branch drop {{.TEST_DB_NAME}} --non-interactive
      - gel branch create {{.TEST_DB_NAME}} --copy-data
    deps: [dl-countries-dataset, migrate]

  reset:
    desc: "Wipe database and reset initial seed"
    dir: ..
    interactive: true
    prompt: This will wipe existing databases and re-run all migrations and seeds. Continue ?
    cmds:
      - cmd: rm data/remote/countries.json
        ignore_error: true
      - gel branch drop main --non-interactive
      - gel branch switch -c main
      - task: seed
    deps: [switch-schema]

  switch-schema:
    internal: true
    desc: "Switch to schema-only branch"
    status: ["gel branch current 2>&1 | grep {{.EMPTY_DB_NAME}}"]
    cmd: gel branch switch {{.EMPTY_DB_NAME}}
    deps: [init-schema]

  switch-main:
    internal: true
    desc: "Switch to schema-only branch"
    status: ["gel branch current 2>&1 | grep main"]
    cmd: gel branch switch main
    deps: [init-schema]

  migration:
    desc: "Extract database migration from current changes in schema"
    dir: ..
    interactive: true
    cmd: gel migration create

  migrate:
    desc: "Apply pending database migrations"
    dir: ..
    cmds:
      - gel migrate
      - gel branch drop {{.TEST_DB_NAME}} --non-interactive
      - gel branch create {{.TEST_DB_NAME}} --copy-data
      - gel branch drop {{.EMPTY_DB_NAME}} --non-interactive
      - gel branch create {{.EMPTY_DB_NAME}}
    deps: [init, init-testing, init-schema, switch-main]
