version: "3"

vars:
  TEST_DB_NAME: testing
  EMPTY_DB_NAME: schema

tasks:
  install:
    desc: "Install EdgeDB CLI"
    cmds: [curl https://sh.edgedb.com --proto '=https' -sSf1 | sh]
    status: [command -v edgedb >/dev/null 2>&1]

  init-schema:
    desc: Create empty schema database branch (used when resetting DB)
    dir: ..
    cmd: edgedb branch create {{.EMPTY_DB_NAME}}
    status:
      - edgedb branch list | grep "{{.EMPTY_DB_NAME}}"

  init-testing:
    desc: "Create testing database branch"
    dir: ..
    cmd: edgedb branch create {{.TEST_DB_NAME}} --copy-data
    status:
      - edgedb branch list | grep "{{.TEST_DB_NAME}}"

  init:
    desc: "Create database instance"
    dir: ..
    interactive: true
    cmds:
      - edgedb project init
      - edgedb project info
    status: [edgedb project info]
    deps: [install]
    run: once

  config-email:
    desc: "Run email settings configuration utility"
    interactive: true
    dir: seeds
    cmds:
      - go run ./cmd/email

  seed:
    desc: "Initialize local database instance with initial content"
    interactive: true
    dir: seeds
    cmds:
      - cmd: echo "Seeding database..."
        silent: true
      - go run ./cmd/seed/
      - edgedb branch drop {{.TEST_DB_NAME}} --non-interactive
      - edgedb branch create {{.TEST_DB_NAME}} --copy-data
    deps: [migrate]

  reset:
    desc: "Wipe database and reset initial seed"
    dir: ..
    interactive: true
    prompt: This will wipe existing databases and re-run all migrations and seeds. Continue ?
    cmds:
      - edgedb branch drop main --non-interactive
      - edgedb branch switch -c main
      - task: seed
    deps: [switch-schema]

  switch-schema:
    internal: true
    desc: "Switch to schema-only branch"
    status: ["edgedb branch current 2>&1 | grep {{.EMPTY_DB_NAME}}"]
    cmd: edgedb branch switch {{.EMPTY_DB_NAME}}
    deps: [init-schema]

  switch-main:
    internal: true
    desc: "Switch to schema-only branch"
    status: ["edgedb branch current 2>&1 | grep main"]
    cmd: edgedb branch switch main
    deps: [init-schema]

  migration:
    desc: "Extract database migration from current changes in schema"
    dir: ..
    interactive: true
    cmd: edgedb migration create

  migrate:
    desc: "Apply pending database migrations"
    dir: ..
    cmds:
      - edgedb migrate
      - edgedb branch drop {{.TEST_DB_NAME}} --non-interactive
      - edgedb branch create {{.TEST_DB_NAME}} --copy-data
      - edgedb branch drop {{.EMPTY_DB_NAME}} --non-interactive
      - edgedb branch create {{.EMPTY_DB_NAME}}
    deps: [init, init-testing, init-schema, switch-main]
