version: "3"

vars:
  TEST_DB_NAME: testing

tasks:
  install:
    cmds: [curl https://sh.edgedb.com --proto '=https' -sSf1 | sh]
    status: [command -v edgedb >/dev/null 2>&1]

  init-testing:
    dir: ..
    cmd: edgedb branch create {{.TEST_DB_NAME}} --copy-data
    status:
      - edgedb branch list | grep "{{.TEST_DB_NAME}}"

  init:
    dir: ..
    interactive: true
    cmds:
      - edgedb project init
      - edgedb project info
    status: [edgedb project info]
    deps: [install]
    run: once

  config-email:
    interactive: true
    dir: seeds
    cmds:
      - go run ./cmd/email

  seed:
    interactive: true
    dir: seeds
    cmds:
      - cmd: echo "Seeding database..."
        silent: true
      - go run ./cmd/seed/
      - edgedb branch drop {{.TEST_DB_NAME}} --non-interactive
      - edgedb branch create {{.TEST_DB_NAME}} --copy-data
    deps: [migrate]

  reset:
    dir: ..
    interactive: true
    prompt: This will wipe existing databases and re-run all migrations and seeds. Continue ?
    cmds:
      - edgedb branch wipe main
      - task: seed

  migration:
    dir: ..
    interactive: true
    cmd: edgedb migration create

  migrate:
    dir: ..
    cmds:
      - edgedb migrate
      - edgedb branch drop {{.TEST_DB_NAME}} --non-interactive
      - edgedb branch create {{.TEST_DB_NAME}} --copy-data
    deps: [init, init-testing]
