//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var GbifStaging = newGbifStagingTable("public", "gbif_staging", "")

type gbifStagingTable struct {
	postgres.Table

	// Columns
	Key              postgres.ColumnInteger
	Parent           postgres.ColumnString
	ParentKey        postgres.ColumnInteger
	CanonicalName    postgres.ColumnString
	ScientificName   postgres.ColumnString
	Status           postgres.ColumnString
	Rank             postgres.ColumnString
	NameType         postgres.ColumnString
	KingdomKey       postgres.ColumnInteger
	PhylumKey        postgres.ColumnInteger
	ClassKey         postgres.ColumnInteger
	OrderKey         postgres.ColumnInteger
	FamilyKey        postgres.ColumnInteger
	GenusKey         postgres.ColumnInteger
	SpeciesKey       postgres.ColumnInteger
	HigherTaxonKeys  postgres.ColumnIntegerArray
	HigherTaxonNames postgres.ColumnStringArray
	Authorship       postgres.ColumnString
	NumDescendants   postgres.ColumnInteger
	AcceptedKey      postgres.ColumnInteger
	AcceptedName     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type GbifStagingTable struct {
	gbifStagingTable

	EXCLUDED gbifStagingTable
}

// AS creates new GbifStagingTable with assigned alias
func (a GbifStagingTable) AS(alias string) *GbifStagingTable {
	return newGbifStagingTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GbifStagingTable with assigned schema name
func (a GbifStagingTable) FromSchema(schemaName string) *GbifStagingTable {
	return newGbifStagingTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GbifStagingTable with assigned table prefix
func (a GbifStagingTable) WithPrefix(prefix string) *GbifStagingTable {
	return newGbifStagingTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GbifStagingTable with assigned table suffix
func (a GbifStagingTable) WithSuffix(suffix string) *GbifStagingTable {
	return newGbifStagingTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGbifStagingTable(schemaName, tableName, alias string) *GbifStagingTable {
	return &GbifStagingTable{
		gbifStagingTable: newGbifStagingTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newGbifStagingTableImpl("", "excluded", ""),
	}
}

func newGbifStagingTableImpl(schemaName, tableName, alias string) gbifStagingTable {
	var (
		KeyColumn              = postgres.IntegerColumn("key")
		ParentColumn           = postgres.StringColumn("parent")
		ParentKeyColumn        = postgres.IntegerColumn("parent_key")
		CanonicalNameColumn    = postgres.StringColumn("canonical_name")
		ScientificNameColumn   = postgres.StringColumn("scientific_name")
		StatusColumn           = postgres.StringColumn("status")
		RankColumn             = postgres.StringColumn("rank")
		NameTypeColumn         = postgres.StringColumn("name_type")
		KingdomKeyColumn       = postgres.IntegerColumn("kingdom_key")
		PhylumKeyColumn        = postgres.IntegerColumn("phylum_key")
		ClassKeyColumn         = postgres.IntegerColumn("class_key")
		OrderKeyColumn         = postgres.IntegerColumn("order_key")
		FamilyKeyColumn        = postgres.IntegerColumn("family_key")
		GenusKeyColumn         = postgres.IntegerColumn("genus_key")
		SpeciesKeyColumn       = postgres.IntegerColumn("species_key")
		HigherTaxonKeysColumn  = postgres.IntegerArrayColumn("higher_taxon_keys")
		HigherTaxonNamesColumn = postgres.StringArrayColumn("higher_taxon_names")
		AuthorshipColumn       = postgres.StringColumn("authorship")
		NumDescendantsColumn   = postgres.IntegerColumn("num_descendants")
		AcceptedKeyColumn      = postgres.IntegerColumn("accepted_key")
		AcceptedNameColumn     = postgres.StringColumn("accepted_name")
		allColumns             = postgres.ColumnList{KeyColumn, ParentColumn, ParentKeyColumn, CanonicalNameColumn, ScientificNameColumn, StatusColumn, RankColumn, NameTypeColumn, KingdomKeyColumn, PhylumKeyColumn, ClassKeyColumn, OrderKeyColumn, FamilyKeyColumn, GenusKeyColumn, SpeciesKeyColumn, HigherTaxonKeysColumn, HigherTaxonNamesColumn, AuthorshipColumn, NumDescendantsColumn, AcceptedKeyColumn, AcceptedNameColumn}
		mutableColumns         = postgres.ColumnList{ParentColumn, ParentKeyColumn, CanonicalNameColumn, ScientificNameColumn, StatusColumn, RankColumn, NameTypeColumn, KingdomKeyColumn, PhylumKeyColumn, ClassKeyColumn, OrderKeyColumn, FamilyKeyColumn, GenusKeyColumn, SpeciesKeyColumn, HigherTaxonKeysColumn, HigherTaxonNamesColumn, AuthorshipColumn, NumDescendantsColumn, AcceptedKeyColumn, AcceptedNameColumn}
		defaultColumns         = postgres.ColumnList{}
	)

	return gbifStagingTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Key:              KeyColumn,
		Parent:           ParentColumn,
		ParentKey:        ParentKeyColumn,
		CanonicalName:    CanonicalNameColumn,
		ScientificName:   ScientificNameColumn,
		Status:           StatusColumn,
		Rank:             RankColumn,
		NameType:         NameTypeColumn,
		KingdomKey:       KingdomKeyColumn,
		PhylumKey:        PhylumKeyColumn,
		ClassKey:         ClassKeyColumn,
		OrderKey:         OrderKeyColumn,
		FamilyKey:        FamilyKeyColumn,
		GenusKey:         GenusKeyColumn,
		SpeciesKey:       SpeciesKeyColumn,
		HigherTaxonKeys:  HigherTaxonKeysColumn,
		HigherTaxonNames: HigherTaxonNamesColumn,
		Authorship:       AuthorshipColumn,
		NumDescendants:   NumDescendantsColumn,
		AcceptedKey:      AcceptedKeyColumn,
		AcceptedName:     AcceptedNameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
