//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var GeoapifyUsage = newGeoapifyUsageTable("public", "geoapify_usage", "")

type geoapifyUsageTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnInteger
	UsageDate     postgres.ColumnDate
	RequestsCount postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type GeoapifyUsageTable struct {
	geoapifyUsageTable

	EXCLUDED geoapifyUsageTable
}

// AS creates new GeoapifyUsageTable with assigned alias
func (a GeoapifyUsageTable) AS(alias string) *GeoapifyUsageTable {
	return newGeoapifyUsageTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GeoapifyUsageTable with assigned schema name
func (a GeoapifyUsageTable) FromSchema(schemaName string) *GeoapifyUsageTable {
	return newGeoapifyUsageTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GeoapifyUsageTable with assigned table prefix
func (a GeoapifyUsageTable) WithPrefix(prefix string) *GeoapifyUsageTable {
	return newGeoapifyUsageTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GeoapifyUsageTable with assigned table suffix
func (a GeoapifyUsageTable) WithSuffix(suffix string) *GeoapifyUsageTable {
	return newGeoapifyUsageTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGeoapifyUsageTable(schemaName, tableName, alias string) *GeoapifyUsageTable {
	return &GeoapifyUsageTable{
		geoapifyUsageTable: newGeoapifyUsageTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newGeoapifyUsageTableImpl("", "excluded", ""),
	}
}

func newGeoapifyUsageTableImpl(schemaName, tableName, alias string) geoapifyUsageTable {
	var (
		IDColumn            = postgres.IntegerColumn("id")
		UsageDateColumn     = postgres.DateColumn("usage_date")
		RequestsCountColumn = postgres.IntegerColumn("requests_count")
		allColumns          = postgres.ColumnList{IDColumn, UsageDateColumn, RequestsCountColumn}
		mutableColumns      = postgres.ColumnList{UsageDateColumn, RequestsCountColumn}
		defaultColumns      = postgres.ColumnList{IDColumn}
	)

	return geoapifyUsageTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		UsageDate:     UsageDateColumn,
		RequestsCount: RequestsCountColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
