//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ImportBatches = newImportBatchesTable("public", "import_batches", "")

type importBatchesTable struct {
	postgres.Table

	// Columns
	ID                      postgres.ColumnString
	Label                   postgres.ColumnString
	Description             postgres.ColumnString
	Status                  postgres.ColumnString
	AssembledBy             postgres.ColumnStringArray
	CreatedBy               postgres.ColumnString
	CreatedAt               postgres.ColumnTimestampz
	CompletedAt             postgres.ColumnTimestampz
	CompletedBy             postgres.ColumnString
	TaxonomicScope          postgres.ColumnInteger
	ImportedFileName        postgres.ColumnString
	ImportedFileSize        postgres.ColumnInteger
	ImportedFileHash        postgres.ColumnString
	ImportedFileContentType postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ImportBatchesTable struct {
	importBatchesTable

	EXCLUDED importBatchesTable
}

// AS creates new ImportBatchesTable with assigned alias
func (a ImportBatchesTable) AS(alias string) *ImportBatchesTable {
	return newImportBatchesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ImportBatchesTable with assigned schema name
func (a ImportBatchesTable) FromSchema(schemaName string) *ImportBatchesTable {
	return newImportBatchesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ImportBatchesTable with assigned table prefix
func (a ImportBatchesTable) WithPrefix(prefix string) *ImportBatchesTable {
	return newImportBatchesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ImportBatchesTable with assigned table suffix
func (a ImportBatchesTable) WithSuffix(suffix string) *ImportBatchesTable {
	return newImportBatchesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newImportBatchesTable(schemaName, tableName, alias string) *ImportBatchesTable {
	return &ImportBatchesTable{
		importBatchesTable: newImportBatchesTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newImportBatchesTableImpl("", "excluded", ""),
	}
}

func newImportBatchesTableImpl(schemaName, tableName, alias string) importBatchesTable {
	var (
		IDColumn                      = postgres.StringColumn("id")
		LabelColumn                   = postgres.StringColumn("label")
		DescriptionColumn             = postgres.StringColumn("description")
		StatusColumn                  = postgres.StringColumn("status")
		AssembledByColumn             = postgres.StringArrayColumn("assembled_by")
		CreatedByColumn               = postgres.StringColumn("created_by")
		CreatedAtColumn               = postgres.TimestampzColumn("created_at")
		CompletedAtColumn             = postgres.TimestampzColumn("completed_at")
		CompletedByColumn             = postgres.StringColumn("completed_by")
		TaxonomicScopeColumn          = postgres.IntegerColumn("taxonomic_scope")
		ImportedFileNameColumn        = postgres.StringColumn("imported_file_name")
		ImportedFileSizeColumn        = postgres.IntegerColumn("imported_file_size")
		ImportedFileHashColumn        = postgres.StringColumn("imported_file_hash")
		ImportedFileContentTypeColumn = postgres.StringColumn("imported_file_content_type")
		allColumns                    = postgres.ColumnList{IDColumn, LabelColumn, DescriptionColumn, StatusColumn, AssembledByColumn, CreatedByColumn, CreatedAtColumn, CompletedAtColumn, CompletedByColumn, TaxonomicScopeColumn, ImportedFileNameColumn, ImportedFileSizeColumn, ImportedFileHashColumn, ImportedFileContentTypeColumn}
		mutableColumns                = postgres.ColumnList{LabelColumn, DescriptionColumn, StatusColumn, AssembledByColumn, CreatedByColumn, CreatedAtColumn, CompletedAtColumn, CompletedByColumn, TaxonomicScopeColumn, ImportedFileNameColumn, ImportedFileSizeColumn, ImportedFileHashColumn, ImportedFileContentTypeColumn}
		defaultColumns                = postgres.ColumnList{IDColumn, StatusColumn, CreatedAtColumn}
	)

	return importBatchesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                      IDColumn,
		Label:                   LabelColumn,
		Description:             DescriptionColumn,
		Status:                  StatusColumn,
		AssembledBy:             AssembledByColumn,
		CreatedBy:               CreatedByColumn,
		CreatedAt:               CreatedAtColumn,
		CompletedAt:             CompletedAtColumn,
		CompletedBy:             CompletedByColumn,
		TaxonomicScope:          TaxonomicScopeColumn,
		ImportedFileName:        ImportedFileNameColumn,
		ImportedFileSize:        ImportedFileSizeColumn,
		ImportedFileHash:        ImportedFileHashColumn,
		ImportedFileContentType: ImportedFileContentTypeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
