//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ImportWorkflows = newImportWorkflowsTable("public", "import_workflows", "")

type importWorkflowsTable struct {
	postgres.Table

	// Columns
	ImportHash            postgres.ColumnString
	Label                 postgres.ColumnString
	GbifStatus            postgres.ColumnString
	GbifCandidatesTotal   postgres.ColumnInteger
	GbifCandidatesFetched postgres.ColumnInteger
	GbifClaimedAt         postgres.ColumnTimestampz
	GbifUpdatedAt         postgres.ColumnTimestampz
	CreatedAt             postgres.ColumnTimestampz
	CompletedAt           postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ImportWorkflowsTable struct {
	importWorkflowsTable

	EXCLUDED importWorkflowsTable
}

// AS creates new ImportWorkflowsTable with assigned alias
func (a ImportWorkflowsTable) AS(alias string) *ImportWorkflowsTable {
	return newImportWorkflowsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ImportWorkflowsTable with assigned schema name
func (a ImportWorkflowsTable) FromSchema(schemaName string) *ImportWorkflowsTable {
	return newImportWorkflowsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ImportWorkflowsTable with assigned table prefix
func (a ImportWorkflowsTable) WithPrefix(prefix string) *ImportWorkflowsTable {
	return newImportWorkflowsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ImportWorkflowsTable with assigned table suffix
func (a ImportWorkflowsTable) WithSuffix(suffix string) *ImportWorkflowsTable {
	return newImportWorkflowsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newImportWorkflowsTable(schemaName, tableName, alias string) *ImportWorkflowsTable {
	return &ImportWorkflowsTable{
		importWorkflowsTable: newImportWorkflowsTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newImportWorkflowsTableImpl("", "excluded", ""),
	}
}

func newImportWorkflowsTableImpl(schemaName, tableName, alias string) importWorkflowsTable {
	var (
		ImportHashColumn            = postgres.StringColumn("import_hash")
		LabelColumn                 = postgres.StringColumn("label")
		GbifStatusColumn            = postgres.StringColumn("gbif_status")
		GbifCandidatesTotalColumn   = postgres.IntegerColumn("gbif_candidates_total")
		GbifCandidatesFetchedColumn = postgres.IntegerColumn("gbif_candidates_fetched")
		GbifClaimedAtColumn         = postgres.TimestampzColumn("gbif_claimed_at")
		GbifUpdatedAtColumn         = postgres.TimestampzColumn("gbif_updated_at")
		CreatedAtColumn             = postgres.TimestampzColumn("created_at")
		CompletedAtColumn           = postgres.TimestampzColumn("completed_at")
		allColumns                  = postgres.ColumnList{ImportHashColumn, LabelColumn, GbifStatusColumn, GbifCandidatesTotalColumn, GbifCandidatesFetchedColumn, GbifClaimedAtColumn, GbifUpdatedAtColumn, CreatedAtColumn, CompletedAtColumn}
		mutableColumns              = postgres.ColumnList{LabelColumn, GbifStatusColumn, GbifCandidatesTotalColumn, GbifCandidatesFetchedColumn, GbifClaimedAtColumn, GbifUpdatedAtColumn, CreatedAtColumn, CompletedAtColumn}
		defaultColumns              = postgres.ColumnList{GbifStatusColumn, CreatedAtColumn}
	)

	return importWorkflowsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ImportHash:            ImportHashColumn,
		Label:                 LabelColumn,
		GbifStatus:            GbifStatusColumn,
		GbifCandidatesTotal:   GbifCandidatesTotalColumn,
		GbifCandidatesFetched: GbifCandidatesFetchedColumn,
		GbifClaimedAt:         GbifClaimedAtColumn,
		GbifUpdatedAt:         GbifUpdatedAtColumn,
		CreatedAt:             CreatedAtColumn,
		CompletedAt:           CompletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
