//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ImportWorkflows = newImportWorkflowsTable("public", "import_workflows", "")

type importWorkflowsTable struct {
	postgres.Table

	// Columns
	ImportID    postgres.ColumnString
	Label       postgres.ColumnString
	Description postgres.ColumnString
	AssembledBy postgres.ColumnStringArray
	CreatedBy   postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz
	CompletedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ImportWorkflowsTable struct {
	importWorkflowsTable

	EXCLUDED importWorkflowsTable
}

// AS creates new ImportWorkflowsTable with assigned alias
func (a ImportWorkflowsTable) AS(alias string) *ImportWorkflowsTable {
	return newImportWorkflowsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ImportWorkflowsTable with assigned schema name
func (a ImportWorkflowsTable) FromSchema(schemaName string) *ImportWorkflowsTable {
	return newImportWorkflowsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ImportWorkflowsTable with assigned table prefix
func (a ImportWorkflowsTable) WithPrefix(prefix string) *ImportWorkflowsTable {
	return newImportWorkflowsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ImportWorkflowsTable with assigned table suffix
func (a ImportWorkflowsTable) WithSuffix(suffix string) *ImportWorkflowsTable {
	return newImportWorkflowsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newImportWorkflowsTable(schemaName, tableName, alias string) *ImportWorkflowsTable {
	return &ImportWorkflowsTable{
		importWorkflowsTable: newImportWorkflowsTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newImportWorkflowsTableImpl("", "excluded", ""),
	}
}

func newImportWorkflowsTableImpl(schemaName, tableName, alias string) importWorkflowsTable {
	var (
		ImportIDColumn    = postgres.StringColumn("import_id")
		LabelColumn       = postgres.StringColumn("label")
		DescriptionColumn = postgres.StringColumn("description")
		AssembledByColumn = postgres.StringArrayColumn("assembled_by")
		CreatedByColumn   = postgres.StringColumn("created_by")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		CompletedAtColumn = postgres.TimestampzColumn("completed_at")
		allColumns        = postgres.ColumnList{ImportIDColumn, LabelColumn, DescriptionColumn, AssembledByColumn, CreatedByColumn, CreatedAtColumn, CompletedAtColumn}
		mutableColumns    = postgres.ColumnList{LabelColumn, DescriptionColumn, AssembledByColumn, CreatedByColumn, CreatedAtColumn, CompletedAtColumn}
		defaultColumns    = postgres.ColumnList{ImportIDColumn, CreatedAtColumn}
	)

	return importWorkflowsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ImportID:    ImportIDColumn,
		Label:       LabelColumn,
		Description: DescriptionColumn,
		AssembledBy: AssembledByColumn,
		CreatedBy:   CreatedByColumn,
		CreatedAt:   CreatedAtColumn,
		CompletedAt: CompletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
