//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Invitations = newInvitationsTable("public", "invitations", "")

type invitationsTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Email       postgres.ColumnString
	InviteeName postgres.ColumnString
	Role        postgres.ColumnString
	Message     postgres.ColumnString
	InviterID   postgres.ColumnString
	Status      postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz
	ExpiresAt   postgres.ColumnTimestampz
	RedeemedAt  postgres.ColumnTimestampz
	RevokedAt   postgres.ColumnTimestampz
	RevokedBy   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type InvitationsTable struct {
	invitationsTable

	EXCLUDED invitationsTable
}

// AS creates new InvitationsTable with assigned alias
func (a InvitationsTable) AS(alias string) *InvitationsTable {
	return newInvitationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new InvitationsTable with assigned schema name
func (a InvitationsTable) FromSchema(schemaName string) *InvitationsTable {
	return newInvitationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new InvitationsTable with assigned table prefix
func (a InvitationsTable) WithPrefix(prefix string) *InvitationsTable {
	return newInvitationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new InvitationsTable with assigned table suffix
func (a InvitationsTable) WithSuffix(suffix string) *InvitationsTable {
	return newInvitationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newInvitationsTable(schemaName, tableName, alias string) *InvitationsTable {
	return &InvitationsTable{
		invitationsTable: newInvitationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newInvitationsTableImpl("", "excluded", ""),
	}
}

func newInvitationsTableImpl(schemaName, tableName, alias string) invitationsTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		EmailColumn       = postgres.StringColumn("email")
		InviteeNameColumn = postgres.StringColumn("invitee_name")
		RoleColumn        = postgres.StringColumn("role")
		MessageColumn     = postgres.StringColumn("message")
		InviterIDColumn   = postgres.StringColumn("inviter_id")
		StatusColumn      = postgres.StringColumn("status")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		ExpiresAtColumn   = postgres.TimestampzColumn("expires_at")
		RedeemedAtColumn  = postgres.TimestampzColumn("redeemed_at")
		RevokedAtColumn   = postgres.TimestampzColumn("revoked_at")
		RevokedByColumn   = postgres.StringColumn("revoked_by")
		allColumns        = postgres.ColumnList{IDColumn, EmailColumn, InviteeNameColumn, RoleColumn, MessageColumn, InviterIDColumn, StatusColumn, CreatedAtColumn, ExpiresAtColumn, RedeemedAtColumn, RevokedAtColumn, RevokedByColumn}
		mutableColumns    = postgres.ColumnList{EmailColumn, InviteeNameColumn, RoleColumn, MessageColumn, InviterIDColumn, StatusColumn, CreatedAtColumn, ExpiresAtColumn, RedeemedAtColumn, RevokedAtColumn, RevokedByColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, RoleColumn, StatusColumn, CreatedAtColumn}
	)

	return invitationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Email:       EmailColumn,
		InviteeName: InviteeNameColumn,
		Role:        RoleColumn,
		Message:     MessageColumn,
		InviterID:   InviterIDColumn,
		Status:      StatusColumn,
		CreatedAt:   CreatedAtColumn,
		ExpiresAt:   ExpiresAtColumn,
		RedeemedAt:  RedeemedAtColumn,
		RevokedAt:   RevokedAtColumn,
		RevokedBy:   RevokedByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
