//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PublicationsStaging = newPublicationsStagingTable("public", "publications_staging", "")

type publicationsStagingTable struct {
	postgres.Table

	// Columns
	ID                  postgres.ColumnString
	ImportID            postgres.ColumnString
	OccurrenceRowNumber postgres.ColumnInteger
	Doi                 postgres.ColumnString
	Authors             postgres.ColumnStringArray
	Year                postgres.ColumnInteger
	Title               postgres.ColumnString
	Journal             postgres.ColumnString
	Verbatim            postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type PublicationsStagingTable struct {
	publicationsStagingTable

	EXCLUDED publicationsStagingTable
}

// AS creates new PublicationsStagingTable with assigned alias
func (a PublicationsStagingTable) AS(alias string) *PublicationsStagingTable {
	return newPublicationsStagingTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PublicationsStagingTable with assigned schema name
func (a PublicationsStagingTable) FromSchema(schemaName string) *PublicationsStagingTable {
	return newPublicationsStagingTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PublicationsStagingTable with assigned table prefix
func (a PublicationsStagingTable) WithPrefix(prefix string) *PublicationsStagingTable {
	return newPublicationsStagingTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PublicationsStagingTable with assigned table suffix
func (a PublicationsStagingTable) WithSuffix(suffix string) *PublicationsStagingTable {
	return newPublicationsStagingTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPublicationsStagingTable(schemaName, tableName, alias string) *PublicationsStagingTable {
	return &PublicationsStagingTable{
		publicationsStagingTable: newPublicationsStagingTableImpl(schemaName, tableName, alias),
		EXCLUDED:                 newPublicationsStagingTableImpl("", "excluded", ""),
	}
}

func newPublicationsStagingTableImpl(schemaName, tableName, alias string) publicationsStagingTable {
	var (
		IDColumn                  = postgres.StringColumn("id")
		ImportIDColumn            = postgres.StringColumn("import_id")
		OccurrenceRowNumberColumn = postgres.IntegerColumn("occurrence_row_number")
		DoiColumn                 = postgres.StringColumn("doi")
		AuthorsColumn             = postgres.StringArrayColumn("authors")
		YearColumn                = postgres.IntegerColumn("year")
		TitleColumn               = postgres.StringColumn("title")
		JournalColumn             = postgres.StringColumn("journal")
		VerbatimColumn            = postgres.StringColumn("verbatim")
		allColumns                = postgres.ColumnList{IDColumn, ImportIDColumn, OccurrenceRowNumberColumn, DoiColumn, AuthorsColumn, YearColumn, TitleColumn, JournalColumn, VerbatimColumn}
		mutableColumns            = postgres.ColumnList{ImportIDColumn, OccurrenceRowNumberColumn, DoiColumn, AuthorsColumn, YearColumn, TitleColumn, JournalColumn, VerbatimColumn}
		defaultColumns            = postgres.ColumnList{IDColumn}
	)

	return publicationsStagingTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                  IDColumn,
		ImportID:            ImportIDColumn,
		OccurrenceRowNumber: OccurrenceRowNumberColumn,
		Doi:                 DoiColumn,
		Authors:             AuthorsColumn,
		Year:                YearColumn,
		Title:               TitleColumn,
		Journal:             JournalColumn,
		Verbatim:            VerbatimColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
