//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SamplingsHabitats = newSamplingsHabitatsTable("public", "samplings_habitats", "")

type samplingsHabitatsTable struct {
	postgres.Table

	// Columns
	SamplingID postgres.ColumnString
	HabitatID  postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SamplingsHabitatsTable struct {
	samplingsHabitatsTable

	EXCLUDED samplingsHabitatsTable
}

// AS creates new SamplingsHabitatsTable with assigned alias
func (a SamplingsHabitatsTable) AS(alias string) *SamplingsHabitatsTable {
	return newSamplingsHabitatsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SamplingsHabitatsTable with assigned schema name
func (a SamplingsHabitatsTable) FromSchema(schemaName string) *SamplingsHabitatsTable {
	return newSamplingsHabitatsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SamplingsHabitatsTable with assigned table prefix
func (a SamplingsHabitatsTable) WithPrefix(prefix string) *SamplingsHabitatsTable {
	return newSamplingsHabitatsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SamplingsHabitatsTable with assigned table suffix
func (a SamplingsHabitatsTable) WithSuffix(suffix string) *SamplingsHabitatsTable {
	return newSamplingsHabitatsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSamplingsHabitatsTable(schemaName, tableName, alias string) *SamplingsHabitatsTable {
	return &SamplingsHabitatsTable{
		samplingsHabitatsTable: newSamplingsHabitatsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newSamplingsHabitatsTableImpl("", "excluded", ""),
	}
}

func newSamplingsHabitatsTableImpl(schemaName, tableName, alias string) samplingsHabitatsTable {
	var (
		SamplingIDColumn = postgres.StringColumn("sampling_id")
		HabitatIDColumn  = postgres.StringColumn("habitat_id")
		allColumns       = postgres.ColumnList{SamplingIDColumn, HabitatIDColumn}
		mutableColumns   = postgres.ColumnList{}
		defaultColumns   = postgres.ColumnList{}
	)

	return samplingsHabitatsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		SamplingID: SamplingIDColumn,
		HabitatID:  HabitatIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
