//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	AbioticMeasurements = AbioticMeasurements.FromSchema(schema)
	AbioticParams = AbioticParams.FromSchema(schema)
	Articles = Articles.FromSchema(schema)
	Countries = Countries.FromSchema(schema)
	Datasets = Datasets.FromSchema(schema)
	DatasetsCurators = DatasetsCurators.FromSchema(schema)
	DatasetsPublications = DatasetsPublications.FromSchema(schema)
	EventsSamplingMethods = EventsSamplingMethods.FromSchema(schema)
	Fixatives = Fixatives.FromSchema(schema)
	GbifDependencies = GbifDependencies.FromSchema(schema)
	GbifStaging = GbifStaging.FromSchema(schema)
	GeoapifyUsage = GeoapifyUsage.FromSchema(schema)
	HabitatGroups = HabitatGroups.FromSchema(schema)
	Habitats = Habitats.FromSchema(schema)
	ImportBatches = ImportBatches.FromSchema(schema)
	ImportSamplingsOccurrences = ImportSamplingsOccurrences.FromSchema(schema)
	ImportWorkflows = ImportWorkflows.FromSchema(schema)
	InvitationTokens = InvitationTokens.FromSchema(schema)
	Invitations = Invitations.FromSchema(schema)
	OccurrenceCodeHistory = OccurrenceCodeHistory.FromSchema(schema)
	OccurrenceCollections = OccurrenceCollections.FromSchema(schema)
	Occurrences = Occurrences.FromSchema(schema)
	OccurrencesArticles = OccurrencesArticles.FromSchema(schema)
	OccurrencesDatasets = OccurrencesDatasets.FromSchema(schema)
	SamplingMethods = SamplingMethods.FromSchema(schema)
	SamplingMethodsResolution = SamplingMethodsResolution.FromSchema(schema)
	SamplingTargetTaxa = SamplingTargetTaxa.FromSchema(schema)
	Samplings = Samplings.FromSchema(schema)
	SamplingsFixatives = SamplingsFixatives.FromSchema(schema)
	SamplingsHabitats = SamplingsHabitats.FromSchema(schema)
	Settings = Settings.FromSchema(schema)
	Taxa = Taxa.FromSchema(schema)
	TaxaClosure = TaxaClosure.FromSchema(schema)
	TaxaStaging = TaxaStaging.FromSchema(schema)
	TaxonCandidates = TaxonCandidates.FromSchema(schema)
	TaxonResolution = TaxonResolution.FromSchema(schema)
	UserAccountRequestTokens = UserAccountRequestTokens.FromSchema(schema)
	UserAccountRequests = UserAccountRequests.FromSchema(schema)
	UserEmailChangeRequestTokens = UserEmailChangeRequestTokens.FromSchema(schema)
	UserEmailChangeRequests = UserEmailChangeRequests.FromSchema(schema)
	UserSessions = UserSessions.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
