//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TaxaClosure = newTaxaClosureTable("public", "taxa_closure", "")

type taxaClosureTable struct {
	postgres.Table

	// Columns
	AncestorID   postgres.ColumnString
	DescendantID postgres.ColumnString
	Depth        postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TaxaClosureTable struct {
	taxaClosureTable

	EXCLUDED taxaClosureTable
}

// AS creates new TaxaClosureTable with assigned alias
func (a TaxaClosureTable) AS(alias string) *TaxaClosureTable {
	return newTaxaClosureTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TaxaClosureTable with assigned schema name
func (a TaxaClosureTable) FromSchema(schemaName string) *TaxaClosureTable {
	return newTaxaClosureTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TaxaClosureTable with assigned table prefix
func (a TaxaClosureTable) WithPrefix(prefix string) *TaxaClosureTable {
	return newTaxaClosureTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TaxaClosureTable with assigned table suffix
func (a TaxaClosureTable) WithSuffix(suffix string) *TaxaClosureTable {
	return newTaxaClosureTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTaxaClosureTable(schemaName, tableName, alias string) *TaxaClosureTable {
	return &TaxaClosureTable{
		taxaClosureTable: newTaxaClosureTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newTaxaClosureTableImpl("", "excluded", ""),
	}
}

func newTaxaClosureTableImpl(schemaName, tableName, alias string) taxaClosureTable {
	var (
		AncestorIDColumn   = postgres.StringColumn("ancestor_id")
		DescendantIDColumn = postgres.StringColumn("descendant_id")
		DepthColumn        = postgres.IntegerColumn("depth")
		allColumns         = postgres.ColumnList{AncestorIDColumn, DescendantIDColumn, DepthColumn}
		mutableColumns     = postgres.ColumnList{DepthColumn}
		defaultColumns     = postgres.ColumnList{}
	)

	return taxaClosureTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		AncestorID:   AncestorIDColumn,
		DescendantID: DescendantIDColumn,
		Depth:        DepthColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
