//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TaxonResolution = newTaxonResolutionTable("public", "taxon_resolution", "")

type taxonResolutionTable struct {
	postgres.Table

	// Columns
	ImportHash postgres.ColumnString
	InputName  postgres.ColumnString
	Source     postgres.ColumnString
	GbifID     postgres.ColumnInteger
	TaxonID    postgres.ColumnString
	StagingID  postgres.ColumnString
	Status     postgres.ColumnString
	GbifStatus postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TaxonResolutionTable struct {
	taxonResolutionTable

	EXCLUDED taxonResolutionTable
}

// AS creates new TaxonResolutionTable with assigned alias
func (a TaxonResolutionTable) AS(alias string) *TaxonResolutionTable {
	return newTaxonResolutionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TaxonResolutionTable with assigned schema name
func (a TaxonResolutionTable) FromSchema(schemaName string) *TaxonResolutionTable {
	return newTaxonResolutionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TaxonResolutionTable with assigned table prefix
func (a TaxonResolutionTable) WithPrefix(prefix string) *TaxonResolutionTable {
	return newTaxonResolutionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TaxonResolutionTable with assigned table suffix
func (a TaxonResolutionTable) WithSuffix(suffix string) *TaxonResolutionTable {
	return newTaxonResolutionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTaxonResolutionTable(schemaName, tableName, alias string) *TaxonResolutionTable {
	return &TaxonResolutionTable{
		taxonResolutionTable: newTaxonResolutionTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newTaxonResolutionTableImpl("", "excluded", ""),
	}
}

func newTaxonResolutionTableImpl(schemaName, tableName, alias string) taxonResolutionTable {
	var (
		ImportHashColumn = postgres.StringColumn("import_hash")
		InputNameColumn  = postgres.StringColumn("input_name")
		SourceColumn     = postgres.StringColumn("source")
		GbifIDColumn     = postgres.IntegerColumn("gbif_id")
		TaxonIDColumn    = postgres.StringColumn("taxon_id")
		StagingIDColumn  = postgres.StringColumn("staging_id")
		StatusColumn     = postgres.StringColumn("status")
		GbifStatusColumn = postgres.StringColumn("gbif_status")
		allColumns       = postgres.ColumnList{ImportHashColumn, InputNameColumn, SourceColumn, GbifIDColumn, TaxonIDColumn, StagingIDColumn, StatusColumn, GbifStatusColumn}
		mutableColumns   = postgres.ColumnList{SourceColumn, GbifIDColumn, TaxonIDColumn, StagingIDColumn, StatusColumn, GbifStatusColumn}
		defaultColumns   = postgres.ColumnList{StatusColumn, GbifStatusColumn}
	)

	return taxonResolutionTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ImportHash: ImportHashColumn,
		InputName:  InputNameColumn,
		Source:     SourceColumn,
		GbifID:     GbifIDColumn,
		TaxonID:    TaxonIDColumn,
		StagingID:  StagingIDColumn,
		Status:     StatusColumn,
		GbifStatus: GbifStatusColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
