//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserEmailChangeRequests = newUserEmailChangeRequestsTable("public", "user_email_change_requests", "")

type userEmailChangeRequestsTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	UserID      postgres.ColumnString
	Email       postgres.ColumnString
	Status      postgres.ColumnString
	CreatedAt   postgres.ColumnTimestampz
	ExpiresAt   postgres.ColumnTimestampz
	VerifiedAt  postgres.ColumnTimestampz
	AppliedAt   postgres.ColumnTimestampz
	CancelledAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserEmailChangeRequestsTable struct {
	userEmailChangeRequestsTable

	EXCLUDED userEmailChangeRequestsTable
}

// AS creates new UserEmailChangeRequestsTable with assigned alias
func (a UserEmailChangeRequestsTable) AS(alias string) *UserEmailChangeRequestsTable {
	return newUserEmailChangeRequestsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserEmailChangeRequestsTable with assigned schema name
func (a UserEmailChangeRequestsTable) FromSchema(schemaName string) *UserEmailChangeRequestsTable {
	return newUserEmailChangeRequestsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserEmailChangeRequestsTable with assigned table prefix
func (a UserEmailChangeRequestsTable) WithPrefix(prefix string) *UserEmailChangeRequestsTable {
	return newUserEmailChangeRequestsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserEmailChangeRequestsTable with assigned table suffix
func (a UserEmailChangeRequestsTable) WithSuffix(suffix string) *UserEmailChangeRequestsTable {
	return newUserEmailChangeRequestsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserEmailChangeRequestsTable(schemaName, tableName, alias string) *UserEmailChangeRequestsTable {
	return &UserEmailChangeRequestsTable{
		userEmailChangeRequestsTable: newUserEmailChangeRequestsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                     newUserEmailChangeRequestsTableImpl("", "excluded", ""),
	}
}

func newUserEmailChangeRequestsTableImpl(schemaName, tableName, alias string) userEmailChangeRequestsTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		UserIDColumn      = postgres.StringColumn("user_id")
		EmailColumn       = postgres.StringColumn("email")
		StatusColumn      = postgres.StringColumn("status")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		ExpiresAtColumn   = postgres.TimestampzColumn("expires_at")
		VerifiedAtColumn  = postgres.TimestampzColumn("verified_at")
		AppliedAtColumn   = postgres.TimestampzColumn("applied_at")
		CancelledAtColumn = postgres.TimestampzColumn("cancelled_at")
		allColumns        = postgres.ColumnList{IDColumn, UserIDColumn, EmailColumn, StatusColumn, CreatedAtColumn, ExpiresAtColumn, VerifiedAtColumn, AppliedAtColumn, CancelledAtColumn}
		mutableColumns    = postgres.ColumnList{UserIDColumn, EmailColumn, StatusColumn, CreatedAtColumn, ExpiresAtColumn, VerifiedAtColumn, AppliedAtColumn, CancelledAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, StatusColumn, CreatedAtColumn}
	)

	return userEmailChangeRequestsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		UserID:      UserIDColumn,
		Email:       EmailColumn,
		Status:      StatusColumn,
		CreatedAt:   CreatedAtColumn,
		ExpiresAt:   ExpiresAtColumn,
		VerifiedAt:  VerifiedAtColumn,
		AppliedAt:   AppliedAtColumn,
		CancelledAt: CancelledAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
