email:
    fromaddress: ""
    fromname: ""
    host: sandbox.smtp.mailtrap.io
    password: 3388056aecfd2d
    port: 587
    user: 63dd7ca9722fcf
instance:
    description: Prototype instance of BiOME for development and testing purposes.
    name: '[BiOME prototype]'
organisation:
    code: LEHNA
    kind: Lab
    name: Laboratoire d'Écologie des Hydrosystèmes Naturels et Anthropisés
superadmin:
    email: louis.duchemin@univ-lyon1.fr
    first_name: Louis
    last_name: Duchemin
    login: lsdch
    organisation: LEHNA
    password: superadmin
