version: 3

env: 
  DB_URL: postgres://dev:dev@localhost:5432/biomedb?sslmode=disable

tasks:
  drop: 
    interactive: true
    prompt: Are you sure you want to drop the dev database ?
    cmds: 
    -  psql {{.DB_URL}} -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
  generate:
    cmds: 
      - go generate ./      
      - go run generators/enums/generate_enums.go ./biomedb
    deps: 
      - generate-sqlc
      - generate-jet

  generate-sqlc:
    internal: true
    cmds: 
      - go tool sqlc generate
  generate-jet: 
    internal: true
    cmds: 
      - go run generators/jet-gen/jet_generator.go --dsn={{.DB_URL}} --schema=public --dest=./biomedb
  bootstrap:
    cmds: 
      - mkdir -p migrations
      - for f in schema/*.sql; do psql {{.DB_URL}} -f "$f"; done
  reset:
    cmds:
      - task: drop
      - task: bootstrap
      - task: generate
